[MVC 구현하기 - 1단계] 호호(유현호) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #113
Opened 2022-09-17 10:01 UTC by yhh1056

안녕하세요 배카라! 주말 잘 보내고 계신가요?

오늘은 날씨가 더운데 다음주 부터 쌀쌀해 질 것 같더라구요. 🥲 중요한 시기에 감기 안걸리도록 조심하셔요!

처음엔 어떻게 구현해야할지 막막했는데 구현하다보니 핸들러매퍼와 핸들러어댑터가 어떤 동작을 하는지 이해하게 되면서 재밌어지더라구요😃

가장 어려웠던 점은 테스트코드를 작성하는 거였어요. mock을 활용하여 테스트할 수 있는 부분을 테스트했습니다!

이번엔 로그도 신경을 써봤는데요. 실제 프레임워크는 debug와 trace를 활용하더라구요. 
미션이어서 편하게 보기위해 info레벨로 로깅을 했는데 추가적으로 로그를 작성하면 좋을 부분도 같이 고민해보면 좋을 것 같아요!

리뷰남겨주시면 열심히 고민해볼게요!!
배카라도 미션 화이팅입니다!!!☺️

2022-09-17 10:51 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +    }
<img width="1021" alt="스크린샷 2022-09-17 오후 7 46 32" src="https://user-images.githubusercontent.com/58363663/190853034-c49c2a11-7b5b-417c-b2ac-43b13d280378.png">

컨트롤러의 메서드는 하나인데 디버깅을 해보니까 3개가 나와서 null 처리를 해주었어요. 람다가 붙은 메서드는 왜 생긴걸까요?ㅜㅜ

2022-09-17 11:03 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +    }
<img width="1021" alt="스크린샷 2022-09-17 오후 7 46 32" src="https://user-images.githubusercontent.com/58363663/190853228-ad5a779d-e1f8-420a-aff6-cf1c561bc3e6.png">

람다메서드까지 가져와지는 걸 디버그 모드로 확인해서 null 처리를 해주었어요. 

그리고 pulbic 메서드만 조회하도록 `Modifier.isPublic(declaredMethod.getModifiers()` 을 사용했는데 괜찮은 방식인지 모르겠어요😂

2022-09-17 11:05 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +    }
<img width="1021" alt="스크린샷 2022-09-17 오후 7 46 32" src="https://user-images.githubusercontent.com/58363663/190853228-ad5a779d-e1f8-420a-aff6-cf1c561bc3e6.png">

람다메서드까지 가져와지는 걸 디버그 모드로 확인해서 null 처리를 해주었어요. 

그리고 pulbic 메서드만 조회하도록 `Modifier.isPublic(declaredMethod.getModifiers()` 을 사용했는데 괜찮은 방식인지 모르겠어요😂

2022-09-17 15:09 UTC, seong-wooo requested changes
# 안녕하세요 호호

일찍 구현해주셨네요! 
코드 보면서 아쉬웠던 부분에 대해서 리뷰 달았습니다!
그리고 코드보면서 전체적으로 `extract`로 시작하는 메소드가 많았는데요! 
이런 메소드들이 메소드명과 메소드가 하는 일이 일치하지 않는다고 느꼈어요.

물론 호호만의 이유가 존재한다면 메소드명을 고대로 놔두셔도 괜찮습니다 ㅎ 

리뷰에 대해서 궁금하시다면 바로 DM 날려주세요 !

2022-09-17 15:09 UTC, seong-wooo commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
> +        render(viewName, request, response);
이 부분은 아직 학습을 잘 진행해보지 않아서 질문 겸 리뷰해보겠습니다!

redirect 시에는 resoponse를 통해 redirect를 진행할 것인데, setAttributes를 먼저 해야할 필요가 있을까요?

2022-09-17 15:15 UTC, seong-wooo commented on mvc/src/test/java/nextstep/mvc/view/ModelAndViewTest.java
> +        assertThat(model.get("age")).isEqualTo("22");
`extracting`을 사용해보는 것은 어떨까요?

2022-09-17 15:34 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        }
static이 붙어버렸네요😭

해당 검증을 없앴어요. defalut가 이미 존재하고 `@GetMapping`, `@PostMapping`과 같은 어노테이션 기능으로 확장된다면 `@RequestMapping`은 반드시 메서드를 가질 필요가 없겠네요. 꼼꼼하게 봐주셔서 감사해요👍

2022-09-17 15:43 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        if (requestMapping != null) {
isAnnotationPresent 메서드도 존재하네요!👍👍

2022-09-17 16:13 UTC, yhh1056 commented on mvc/src/test/java/nextstep/mvc/view/ModelAndViewTest.java
> +        assertThat(model.get("age")).isEqualTo("22");
``` java
assertThat(modelAndView).extracting("model")
    .hasFieldOrPropertyWithValue("id", "1")
    .hasFieldOrPropertyWithValue("name", "hoho")
    .hasFieldOrPropertyWithValue("age", "22");
```
위 방식은 필드명이 수정되면 테스트도 꺠지게되는데 아래와 같은 코드로 작성할 수 있을 것 같아요.

``` java
assertThat(model).containsExactly(
    entry("id", "1"),
    entry("name", "hoho"),
    entry("age", "22"));
```

배카라는 어떤 방식으로 테스트하는 걸 선호하시나요?

2022-09-17 16:22 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            if (Modifier.isPublic(declaredMethod.getModifiers())) {
코멘트에 남긴것처럼 디버깅을 해보면 메서드 내부에서 사용하는 람다메서드도 가져오게 되요. 

init같은 경우에 어플리케이션이 실행될때 한번만 실행되어서 성능에 큰 신경을 쓰는게 의미가 있나싶지만 컨트롤러의 로직이 많아질경우 조회되는 메서드가 많아질텐데 좀 더 빠른 검증을 하기위해 사용했어요.
근데 Modifier.isPublic 메서드를 사용하는게 더 효율적인지 모르겠어서 코멘트남겼습니다! 다시 생각해보니 없어도 될거같아요ㅎㅎ

2022-09-17 16:32 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            execute(request, response, handlerAdapter, handler);
매번 핸들러를 반복했네요😂
수정했습니다~!!

2022-09-17 16:39 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
> +        render(viewName, request, response);
redirect request 객체를 재사용하지 않아서 forward 시점으로 옮길게요! 👍

2022-09-17 16:59 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        addHandlerExecutions(clazz, declaredMethod, uri, method[0]);
http 요청이 하나만 올 수 있는데 왜 배열을 받고있지 했었는데 여러 메서드를 공통으로 사용할 수 있는 상황도 있겠군요. 반복문으로 수정해야겠네요!!

2022-09-17 17:14 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            extractHandlerAdapter(request, response);
execute 와 handle 이라는 메서드로 수정해봤는데 아직 조금 어색하네요. 조금 더 괜찮은 네이밍있으면 추천부탁해요!!😃

2022-09-17 18:05 UTC, seong-wooo commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            execute(request, response, handlerAdapter, handler);
편 - 안 하네요 :)

2022-09-17 18:17 UTC, seong-wooo commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            execute(request, response, handlerAdapter, handler);
그런데 이 부분 조금 더 개선해볼 수 있을 것 같아요
handler가 여러 개 있을 때 handler를 처리할 수 있는 handlerAdapter가 실행 되었어도 for문을 계속 돌겠네요
`getHandler` 메소드의 방식처럼 먼저 handlerAdapter를 찾아오는 방법은 어떨까요?

2022-09-18 05:35 UTC, seong-wooo commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            extractHandlerAdapter(request, response);
개인적인 생각인데, try안의 로직을 하나의 메소드로 만들어서 이름 짓기가 어려운 것 같아요.
try 안의 로직을 조금 분리해보면 어떨까요?

예를 들어보자면 이런식으로요! 
```
        try {
            핸들러를 찾는다.
            핸들러어댑터를 찾는다.
            모델앤뷰를 만든다.
            렌더링한다.
        } 
```

지금은 `service`라는 메소드의 try 안에서 execute라는 메소드만 실행하는데,
이 excute가 뭘 실행하는 메소드인지 확인하려면 메소드를 계속 타고타고 들어가봐야하는 것 같아요.
`service` 메소드만 봤을 때 이 메소드가 대충 어떤 일을 하는 메소드 구나 라는 것을 알게 해주면 좋을 것 같아요!

2022-09-18 06:33 UTC, seong-wooo requested changes
# 안녕하세요 호호

이번이 1단계 마지막 리뷰일 것 같아요.
빠른 리뷰 반영 좋네요 ㅎ 

화이팅이에요

2022-09-18 06:33 UTC, seong-wooo commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        log();
어떤 로그를 남기는 걸까요? 메소드명을 통해서 알 수 있으면 좋을 것 같아요 ㅎ

2022-09-18 06:33 UTC, seong-wooo commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
> +        forward(model, request, response);
`isRedirect`라는 메소드가 boolean 값을 반환하는 것 뿐만 아니라 response 설정까지 진행하고 있어요. 
isRedirect 는 boolean 값만 반환하고, 조건문 내부에서 실행해야할 로직을 명시해주는 것이 더 보기 좋을 것 같아요!
```
      if (isRedirect()) {
            sendRedirect(response);
        }
        forward(model, request, response);
```
이 리뷰는 제 개인적인 생각이라서 과하다고 생각이 들면, 반영하지 않으셔도 될 것 같아요.

2022-09-18 06:37 UTC, seong-wooo commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            if (Modifier.isPublic(declaredMethod.getModifiers())) {
저는 이 부분에서 어차피 리플랙션으로 handler를 찾아올 것인데 private과 public이 의미가 있나? 생각이 들더라구요.
실제로 스프링에서 handler 메소드를 private으로 바꿔도 동작하기도 하구요. 
그리고 [코멘트](https://github.com/woowacourse/jwp-dashboard-mvc/pull/113#discussion_r973572897)에 남겨주신대로 다른 메소드들이 조회가 되어도 @RequestMapping 어노테이션이 안붙어있다면 의미없지 않을까요...? 
지극히 제 생각입니다 ㅋㅋ

2022-09-18 06:47 UTC, seong-wooo commented on mvc/src/test/java/nextstep/mvc/view/ModelAndViewTest.java
> +        assertThat(model.get("age")).isEqualTo("22");
저도 아래처럼 작성할 것 같아요! 

원래는 항상 이런식으로 진행했어요.
```
assertThat(model).extracting("id, "name", "age")
.containsExactly("1", "hoho", "22");
```

2022-09-18 12:46 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            if (Modifier.isPublic(declaredMethod.getModifiers())) {
ㅋㅋㅋㅋㅋ 저도 설명하다가 이게 왜 필요할까생각이 들어서 지워버렸어요👍👍

2022-09-18 12:54 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            extractHandlerAdapter(request, response);
오우... 배카라가 가이드한대로 분리하니까 훨씬 읽기 편해지고 분리가 잘되네요... 약간 감동받았어요🤩

2022-09-18 12:55 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            execute(request, response, handlerAdapter, handler);
위에 친절하게 try문 적어주신대로 해보니까 훨씬 간결해지네요!!!

2022-09-18 12:58 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        log();
클린코드에서 이름을 작성할 때 상대방이 모호하다고 느끼면 총맞을 각오하라는 마음으로 이름을 지으라 했는데 전 이미 죽었을거에요

2022-09-18 12:59 UTC, yhh1056 commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
> +        forward(model, request, response);
배카라 의견에 완전 공감하는 부분입니다!!
조회와 명령이 같은 곳에서 일어나고 있었네요. 분리하고나니까 더 깔끔해졌습니다!! 👍

2022-09-18 14:04 UTC, seong-wooo approved these changes
# 안녕하세요 호호

코드가 깔끔하네욥
2단계 시작하기 전에 한 가지 리뷰만 반영해주세요 ㅎ

1단계 고생 많으셨어요 !

2022-09-18 14:04 UTC, merged