[MVC 구현하기 - 1단계] 매트(최기현) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #120
Opened 2022-09-18 08:49 UTC by hyeonic

안녕하세요 짱구! 매트입니다 😃

**🚀 1단계 - @MVC 프레임워크 구현하기** 미션 제출합니다! 

미션을 진행하며 실제 Spring MVC의 동작 구조를 최대한 유사하게 가져가기 위해 참고하였습니다. 덕분에 구조 파악에는 용이 했습니다. 다만 미션 코드 내부에 `HandlerAdapter`의 존재를 확인 한 뒤, `DispatcherServlet에서 HandlerMapping 인터페이스를 활용하여 AnnotationHandlerMapping과 ManualHandlerMapping 둘다 처리`하기 위한 요구사항을 해결하기 위해 `HandlerAdapter` 구현체를 도입하게 되었습니다. 1단계 요구사항의 의도(둘다 처리할 수 있다)를 착각하여 2단계 요구사항을 조금 침범하게 되었네요... 이 부분은 감안하고 리뷰 주시면 감사하겠습니다 🥲

리뷰 잘 부탁드립니다! 감사합니다 🙇‍♂️

2022-09-20 04:10 UTC, sc0116 requested changes
매트! 저 짱군데요! 테스트까지 잘 작성해주셨네요!! 막 고쳐야할 부분이라기보단 궁금한 부분 몇가지 남겨두었어요! 확인하시구 디엠주시면 머지해드릴게요!

2022-09-20 04:10 UTC, sc0116 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +                .collect(toMap(this::toHandlerKey, method -> new HandlerExecution(controllerClazz, method)));
오... 이렇게도 할 수 있군요!! 굿굿

2022-09-20 04:10 UTC, sc0116 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
> +    private final Class<?> clazz;
매트는 controller(handler)대신 class<?>를 필드로 두셨군요! 이건 정말 궁금해서 그런데 혹시 clazz를 두신 이유가 있을까용??

2022-09-20 15:48 UTC, hyeonic commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +public class  AnnotationHandlerMapping implements HandlerMapping {
헉 그러네요! 감사합니다 😃

2022-09-21 01:20 UTC, hyeonic commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            view.render(modelAndView.getModel(), request, response);
실제 `Spring MVC`에 `View` 인터페이스를 살펴보면 아래와 같은 형식을 가지고 있습니다.

```java
public interface View {
        ...
	void render(@Nullable Map<String, ?> model, HttpServletRequest request, HttpServletResponse response)
			throws Exception;

}
```

제가 생각한 `View`의 책임은 외부에서 전달 받은 `model`을 통해 랜더링을 진행하여 온전한 view 파일을 생성하는 것이라 생각했어요. `ModelAndView`의 경우 공식 문서를 살펴보면 단순히 `Model`과 `View`에 대한 데이터를 담기 위한 용도라고 하네요! 때문에 실질적으로 render를 진행하는 주체는 View가 적절하다 판단합니다.

```
Holder for both Model and View in the web MVC framework. Note that these are entirely distinct. This class merely holds both to make it possible for a controller to return both model and view in a single return value.

웹 MVC 프레임워크에서 모델 및 뷰에 대한 홀더이다. 이 클래스는 컨트롤러가 모델과 뷰를 모두 단일 반환 값으로 반환할 수 있도록 하기 위해 두 가지 모두를 보유할 수 있다.
```

2022-09-21 01:26 UTC, hyeonic commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
> +    private final Class<?> clazz;
```java
     public ModelAndView handle(final HttpServletRequest request, final HttpServletResponse response) throws Exception {
        Class<?> clazz = method.getDeclaringClass();
        Constructor<?> constructor = clazz.getConstructor();
        Object instance = constructor.newInstance();
        return (ModelAndView) method.invoke(instance, request, response);
    }
```

2022-09-21 11:07 UTC, sc0116 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            view.render(modelAndView.getModel(), request, response);
헉 매트 저 짱군데요, 매트덕에 좋은 지식 알아갑니다!!! 오히려 제가 매트한테 리뷰받고 수정하네요!!!

2022-09-22 04:04 UTC, merged