[MVC 구현하기 - 1단계] 크리스(공병주) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #126
Opened 2022-09-18 12:47 UTC by Byeongju-Kong

라라~ 우테코 생활을 하면서 영상 근로로 만났지만, 학습 목적으로는 처음 만나네요!
잘 부탁드립니다~ 환절기인데, 감기 조심하시고요😀😀😀!

2022-09-19 17:26 UTC, sure-why-not requested changes
크리스 안녕하세요 😎
학습 목적으론 정말 처음 뵙네요 ㅋ_ㅋ 

미션 전체적으로 깔끔하게 잘 구현해주셨더라구요!
몇가지 궁금한점과 피드백 남겼으니 확인해주시면 감사하겠습니다 🦸🏼‍♀️
남은 미션도 화이팅 ~~~ 💪🏻💪🏻

2022-09-19 18:31 UTC, sure-why-not commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        }
추가적으로 알게된 내용이라 코멘트 남겨요!

```java
Object[] basePackage;
```

저도 basePackage가 여러개이니 for 문이나 stream 을 통해 하나씩 리플랙션해야한다고 생각했는데
`Object[]` 형태 그대로 넘겨도 각 패키지에 따라 잘 수행되더라구요.
그래서 따로 for문을 돌지 않고 `Reflections reflections = new Reflections(basePackage);`한번만 진행해도 될 것 같아요 ~

2022-09-20 06:56 UTC, Byeongju-Kong commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        }
오홍!!! 감사합니다~!

2022-09-20 07:01 UTC, Byeongju-Kong commented on mvc/src/main/java/nextstep/web/support/RequestMethod.java
> +    public static RequestMethod from(String requestMethod) {
제가 원래 final을 사용하지 않는데, 구구가 제공해주신 코드에는 final이 붙어있더라고요...!

제 style 대로 final 키워드 수정했습니다~

2022-09-20 07:01 UTC, Byeongju-Kong commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    private HandlerAdapter findHandlerAdapter(Object handler) {
제가 원래 final을 사용하지 않는데, 구구가 제공해주신 코드에는 final이 붙어있더라고요...!

제 style 대로 final 키워드 수정했습니다~

2022-09-20 07:04 UTC, Byeongju-Kong commented on app/src/main/java/com/techcourse/AppWebApplicationInitializer.java
> +        dispatcherServlet.addHandlerAdapter(new AnnotationHandlerAdapter());
실수로 빼먹었네요! AnnotaionHandlerMapping도 추가해주었습니다~!

2022-09-20 07:04 UTC, Byeongju-Kong commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
> +        return (ModelAndView) method.invoke(object, request, response);
🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️

2022-09-20 07:06 UTC, Byeongju-Kong commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
> +        if (viewName.startsWith(JspView.REDIRECT_PREFIX)) {
👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻

2022-09-20 07:08 UTC, Byeongju-Kong commented on app/src/test/java/com/techcourse/ManualHandlerAdapterTest.java
> +}
👍🏻👍🏻👍🏻👍🏻

2022-09-20 07:09 UTC, Byeongju-Kong commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +                requestMapping.method()[HTTP_REQUEST_METHOD_INDEX]);
저도 처음에는 그렇게 구현해야겠다고 생각했는데요!
묾론 그렇게 처리해줄 수 있지만, HttpRequest Method가 다르면 다른 동작을 한다고 생각을 했어요!

따라서, 하나의 HttpRequestMethod만을 허용하도록 했습니다~

2022-09-20 08:25 UTC, Byeongju-Kong commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    private final List<HandlerAdapter> handlerAdapters;
HandlerAdapter는 Handler를 유연하게 하게 해주는 역할이 있다고 생각해요!

Controller에서 String으로 된 viewname을 반환할 수도 있고, ModelAndView를 반환할 수도 있고, Json을 위한 데이터를 반환할 수도 있는 상황에서 결국 DispatcherServlet이 필요한 값은 ModelAndView라면 HandlerAdapter가 handler에서 반환한 값을 ModelAndView로 가공해는 것이라고 생각합니다!

제 생각이 잘못됐거나, 부족하다면 의견 주십쇼 라라!

2022-09-20 09:07 UTC, Byeongju-Kong commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
> +        requestDispatcher.forward(request, response);
redirect, 클라이언트에게 해당 resource로 다시 요청을 보내라라고 응답하는 것이라 생각해요. 그에 따라서, Http 요청 응답이 한번 더 발생하겠죠. 
forward는 a를 요청했는데, b가 응답이 되는 경우에 이를 리다이렉트 방식이 아닌, 한 HTTP 트랜잭션 내에서 처리하는 것으로 알고 있습니다!

2022-09-20 09:07 UTC, Byeongju-Kong commented
라라! 리뷰 반영했고 답변 남겨두었습니다! 부족한 점이 있다면 답글 달아주시면 감사하겠습니다~!😀😀😀😀

2022-09-20 12:56 UTC, sure-why-not commented
크리스 안녕하세요 🫡
피드백 반영한 내용 잘 확인했습니다! 👍🏻

더이상 피드백 드릴 내용은 없는 것 같아서 머지하도록 할게요~!
수고 많으셨습니다 ㅎㅎ 2단계도 화이팅! 💪🏻

2022-09-20 12:56 UTC, merged