[MVC 구현하기 - 1단계] 라쿤(이병훈) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #135
Opened 2022-09-18 15:25 UTC by nbalance97

연로그 안녕하세요~ MVC 구현하기 미션 잘부탁드립..니다😅

테스트 작성은 현재 너무 모호해서 추후에 추가하려고 합니다!ㅎㅎ 

목표는 최대한 깔끔하게 작성하려고 했는데.. Adapter 사용이 올바른지 모호하네요. 
또한 HandlerExecution에서도 결국 메서드 실행마다 객체를 하나 만들게 되기도 하고, 기본 생성자가 반드시 필요하게 되는 문제점도 있어서 이 부분을 어떻게 개선해야 할 지 고민중입니다.

바쁘실텐데 코드 리뷰하느라 시간 내주셔서 감사드리며.. 이번 미션 잘부탁드립니다 🫡

2022-09-19 06:57 UTC, yeon-06 requested changes
안녕하세요 라쿤~! 미션 고생 많으셨습니다 ㅎ.ㅎ

몇 가지 질문과 약간의 수정 요청이 있어서 request changes 해둘게요!
변경 후 다시 요청 주시면 감사합니다^ㅡ^

1. 변경 사항에는 없어서 코멘트 달지 못했지만 JspView의 TODO를 제거할 수 있는 방법은 없을까요?
2. 테스트 코드를 추가할 방법은 없을까요?

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            if (modelAndView == null) {
ModelAndView가 null이 되는 이유가 뭘까요?
해당 케이스에 대해 조사한 것이 있다고 말씀해주셔서 첨부 자료 부탁드립니다 ㅎ.ㅎ

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            view.render(modelAndView.getModel(), request, response);
ModelAndView에서 View를 get한 뒤에 render() 하기보다는 ModelAndView에서 실행시킬 수 있지 않을까요?

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>                  .findFirst()
많은 사람들이 findAny() vs findFirst() 선택이 갈릴 것 같은데요
findFirst()를 선택하신 이유가 있으실까요?

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>                  .orElseThrow();
아무런 Exception이 없네요!

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/adapter/ManualHandlerAdapter.java
> +    private void move(final String viewName, final HttpServletRequest request, final HttpServletResponse response) throws Exception {
이 메서드는 어떤 로직을 수행하고 있나요?
해당 로직은 누구의 책임이라고 생각하시나요?😄

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/adapter/ManualHandlerAdapter.java
> +        final var requestDispatcher = request.getRequestDispatcher(viewName);
final과 var형이 혼용되고 있네요
자체적으로 라쿤만의 컨벤션을 통일해주시면 좋을 것 같아요😄

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            Reflections reflections = new Reflections(eachPackage);
for문을 돌 필요 없이 Reflections안에 basePackage를 그대로 넣을 수 있어요 😄

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
>          return null;
```suggestion
    private void findRequestMappingFromMethod(Method[] methods) {
        for (Method method: methods) {
            addRequestMapping(method);
        }
```
이건 어떨까요ㅎ.ㅎ
메서드명도 이에 맞춰 변경해주시면 좋을 것 같아요~

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            for (RequestMethod requestMethod : requestMapping.method()) {
depth 줄일 방법은 없을까요? 👀

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
> +        Object instance = method.getDeclaringClass().getConstructors()[0].newInstance();
constructor를 하나만 가져오는 방법도 있지 않을까요?

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java
> +
👀

2022-09-19 06:57 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/adapter/ManualHandlerAdapter.java
> +        if (viewName.startsWith(JspView.REDIRECT_PREFIX)) {
`JspView.REDIRECT_PREFIX` 상수를 private화 할 수는 없을까요?

2022-09-19 23:47 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            if (modelAndView == null) {
https://ryoostar.tistory.com/105

예시로 Spring의 @responsebody 어노테이션을 붙였을 때, 따로 설정해주지 않는 이상 ModelAndView가 null이 리턴된다고 하네요.

2022-09-19 23:51 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            view.render(modelAndView.getModel(), request, response);
View 관점에서는 model이 꼭 필요하지 않다고 생각합니다. 

render의 온전한 책임은 View에 있으며, ModelAndView는 클래스명 그대로 model과 view를 가지고 있는 역할이라고 생각합니다.
렌더링의 역할까지 한다면 클래스명 자체도 ModelAndView가 아니라 Render이 포함된 클래스명이 될 거 같아요.

2022-09-19 23:53 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>                  .findFirst()
작성된 코드를 그대로 사용하였기는 한데.. findAny()는 병렬적으로 처리할 때는 성능 상 이점이 있는 걸로 알고 있습니다. 

현재 병렬로 처리할 만큼 handlerMapping이 양이 많은 것 같지 않습니다. 스트림을 병렬로 사용하고 있지 않으므로 findFirst를 사용하더라도 문제가 없지 않을까요??

2022-09-20 00:05 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>                  .orElseThrow();
아아.. 추가했습니다😇

2022-09-20 23:42 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            if (modelAndView == null) {
모두 modelAndView를 생성하도록 변경됨에 따라 현재는 null 체크의 의미가 없어 제거하였습니다~

2022-09-20 23:45 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/adapter/ManualHandlerAdapter.java
> +    private void move(final String viewName, final HttpServletRequest request, final HttpServletResponse response) throws Exception {
맞네요~ move는 사실상 렌더링이므로 렌더링에 책임이 있는 View에 존재하는것이 좋겠네요👍

2022-09-20 23:52 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/adapter/ManualHandlerAdapter.java
> +        final var requestDispatcher = request.getRequestDispatcher(viewName);
final은 모두 붙여주었고 var은 모두 제거하였습니다~

2022-09-20 23:53 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            Reflections reflections = new Reflections(eachPackage);
오.. 꿀팁 감사합니다 😇

2022-09-21 00:11 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
>          return null;
stream을 사용하도록 전체적으로 로직을 변경하였습니다~

2022-09-21 00:12 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            for (RequestMethod requestMethod : requestMapping.method()) {
위에서 stream을 사용하도록 변경하면서 depth가 줄어들었습니다ㅎㅎ

2022-09-21 00:15 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
> +        Object instance = method.getDeclaringClass().getConstructors()[0].newInstance();
맞네요~ getConstructor을 사용하도록 변경하였습니다~

2022-09-21 00:16 UTC, nbalance97 commented on mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java
> +
😱

2022-09-21 00:20 UTC, nbalance97 commented on mvc/src/main/java/nextstep/mvc/adapter/ManualHandlerAdapter.java
> +        if (viewName.startsWith(JspView.REDIRECT_PREFIX)) {
렌더링하는 로직을 JspView에 넘기면서 현재는 JspView에서 private로 가지고 있게 하도록 변경하였습니다.

고민인 부분은 REDIRECT_PREFIX가 JspView에 국한될 필요가 없어 보여서 추후에 View가 추가된다면 결국엔 public으로 열어줘야 될 것 같다고 생각되는데.. 연로그의 생각은 어떤가요?

2022-09-21 01:31 UTC, nbalance97 commented
안녕하세요 연로그~ 

테스트를 작성해 보려고 했는데, 대부분 Mock처리를 해주어야 하더라구요. 
Mock처리한 값을 검증하는 것이 의미가 없을것 같아서 현재는 추가하지 않았고, 조금 더 고민해 보겠습니다🙃

2022-09-22 04:15 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            if (modelAndView == null) {
자료 공유 감사합니다 ㅎㅎ

2022-09-22 04:20 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            view.render(modelAndView.getModel(), request, response);
캡슐화 관점에서 말씀을 드리고자 했는데요~

해당 로직에서 사용하고 있는 view와 model 둘 다 ModelAndView에 이미 존재하는 값이에요
ModelAndView에서 view의 render를 호출하는 메서드를 생성하면 getter를 통해 값을 꺼내서 사용할 필요가 없을 것 같아요 ㅎㅎ

근데 사소한 문제이기도 하고 이 정도는 취향 차이일 것 같아서 제 생각만 남기고 넘어가겠습니다😄
라쿤의 생각도 설명해주셔서 감사해요~

2022-09-22 04:22 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>                  .findFirst()
병렬로 처리할 만큼 많은 양의 기준이 어떻게 될까요?
그렇다면 DispatcherServlet은 사용자가 얼마만큼의 handlerMapping을 추가할지 미리 예측하고 있어야 하는걸까요?

문제가 발생하지는 않지만 제가 모르는 findFirst()를 사용함으로써 얻는 이점이 있을까하여 여쭤봤습니다 ㅎㅎ

2022-09-22 04:31 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/adapter/ManualHandlerAdapter.java
> +        if (viewName.startsWith(JspView.REDIRECT_PREFIX)) {
View가 추가되고 해당 View에서도 비슷한 상수가 필요하게 된다면...
View마다 REDIRECT_PREFIX 형식이 다를수도 있다고 생각하여 상수를 따로 정의해야한다고 생각하는 편입니다!

모든 View에서 공통적으로 사용해야하는 상수라면 View에서 정의할 수도 있을 것 같고요~
View에서 상수를 정의한다면 public이 아닌 default 정도로도 선언할 수 있겠네요!

2022-09-22 04:44 UTC, yeon-06 approved these changes
안녕하세요 라쿤~ 1단계 미션 고생 많으셨습니다😄
몇 가지 코멘트 달았는데 다음 단계에서 생각해주시고 이번 PR은 이만 approve할게요!

2022-09-22 04:44 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +                .orElseThrow(() -> new IllegalArgumentException("지원하는 어댑터가 존재하지 않습니다."));
`NoSuchElementException`은 어떨까요?😄

- `IllegalArgumentException`: Thrown to indicate that a method has been passed an illegal or inappropriate argument.
- `NoSuchElementException`: Thrown by various accessor methods to indicate that the element being requested does not exist.
(출처 Oracle Docs)

2022-09-22 04:44 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +                .forEach(this::addHandlerExecution);
👍

2022-09-22 04:44 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
> +        final Object instance = method.getDeclaringClass().getConstructor().newInstance();
다음 단계에서는 hanlde()이 호출될때마다 인스턴스를 새로 생성하지 않고 이미 생성한 인스턴스를 재활용할 방법도 생각해보시면 좋을 것 같아요 😄

2022-09-22 04:44 UTC, yeon-06 commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
>          });
중복 로직 같아요 🙂

2022-09-22 04:44 UTC, merged