[MVC 구현하기 - 1단계] 루나(남민정) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #138
Opened 2022-09-18 17:48 UTC by RunaNam

안녕하세요 제로! 
미션 진행하면서 개인적으로 많이 헤멨어서 적절한 구조가 맞는지 아직도 조금 헷갈리네요 ㅠㅠ 조금 더 구조에 대해서 고민하면서 고쳐보도록 하겠습니다 👍
테스트의 경우에는 조금 더 다양하게 짜고 싶었으나 방식을 제대로 찾지 못한 것 같아서 간단하게만 짰습니다. 
이해 안되는 부분이 있으면 편하게 DM 주세요! 감사합니다~

2022-09-20 04:19 UTC, asebn1 requested changes
루나~ 1단계 구현하시느라 고생하셨어요! 
저도 미션 진행하면서 많이 해맸는데 루나코드 리뷰하면서 오히려 제 코드에서 고쳐야 할 방향을 배우고가서 감사하네요 ㅎㅎ
테스트는 DispatcherSurvlet에서 Mock으로 테스트케이스를 추가해볼 수 있을 것 같습니다!
루나에게 코멘트 의견을 듣고싶어서 우선 RC 하겠습니다 👍

2022-09-20 04:19 UTC, asebn1 commented on mvc/src/main/java/nextstep/mvc/handlerMapping/AnnotationHandlerMapping.java
> +
`Set<Method> annotatedMethods`에서 변수를 복수형으로 했으니 여기서도 `Set<Class<?>> annotatedControllers`로 하는 건 어떤가요?

2022-09-20 12:41 UTC, RunaNam commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            modelAndView.render(request, response);
아래도 그렇지만 final 처리가 되어있는 부분이 있고 아닌 부분이 있네요 ㅠ 전체적으로 수정해보도록 하겠습니다! 👍

2022-09-20 12:43 UTC, RunaNam commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            .orElseThrow(() -> new IllegalArgumentException("handler를 찾을 수 없습니다."));
저는 딱히 커스텀 에러보다는 기존에 있는 에러를 재사용하는 편이긴 했는데 이번에는 제로가 말씀해주신대로 커스텀 에러로 바꿔보겠습니다.

2022-09-20 12:43 UTC, RunaNam commented on mvc/src/main/java/nextstep/mvc/handlerMapping/AnnotationHandlerMapping.java
> +        }
리팩토링을 한번 더 진행해보겠습니다~!

2022-09-20 12:44 UTC, RunaNam commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
>      public static final String REDIRECT_PREFIX = "redirect:";
수정하는걸 빼먹은 것 같습니다... 알려주셔서 감사해요!

2022-09-20 12:44 UTC, RunaNam commented on mvc/src/main/java/nextstep/mvc/handlerMapping/AnnotationHandlerMapping.java
> +
그렇네요...! 수정하겠습니다.

2022-09-20 14:37 UTC, RunaNam commented
꼼꼼한 리뷰 감사합니다~~!! 
리뷰주신 내용 바탕으로 수정해서 보내드려요! 👍

2022-09-21 01:28 UTC, asebn1 approved these changes
루나~ 고생하셨습니다! 피드백 반영 확인했습니다
전체적으로 깔끔하게 구현해주셔서 이만 머지하겠습니다!
다음 미션도 화이팅~!

2022-09-21 01:28 UTC, merged