[MVC 구현하기 - 1단계] 우기(박병욱) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #14
Opened 2021-09-06 14:49 UTC by jujubebat

안녕하세요 코다 우기 입니다! 

디스패처 서블릿 코드가 변경되지 않게 하면서, 다양한 종류의 핸들러(컨트롤러)가 동작할 수 있도록 핸들러 매핑, 핸들러 어댑터, 뷰 리졸버 등을 구현했습니다! 디스패처 서블릿 코드를 참고 하면서 진행했어요 

피드백 주시면 많이 배우면서 부족한 부분 적극적으로 개선 해보겠습니다 😃
리뷰감사합니다 ㅎㅎ

2021-09-09 06:42 UTC, yjksw requested changes
안녕하세요 우기 😊 코다 입니다 !! 
 
코드가 클래스별로 책임분리도 잘 되어 있고 기존에 있던 스켈레톤 코드를 적절히 수정해서 읽기 수월했어요 !! 
개인적으로  스프링 MVC DispatcherServlet과 굉장히 유사하게 구현이 되어서 많이 배우면서 했어요 ㅎㅎ 

몇가지 코멘트 남겼는데 확인하고 불분명한 부분이 있으면 코멘트나 DM 으로 같이 논의해보아도 좋을 것 같아요 ~~!!! 

앞으로도 화이팅 입니다 🙌🎉🚀

2021-09-09 06:42 UTC, yjksw commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            }
이 부분과 `addHandlerMapping()`에서 초기화 하는 과정이 겹쳐서 `ManualHandlerMapping`이 두번 초기화 되는거 같아요 ~!

2021-09-09 06:42 UTC, yjksw commented on app/src/main/java/com/techcourse/controller/LogoutController.java
> +        return "redirect:/index.jsp";
아마 `ForwardController`로 인해 `/` 로 redirect 해도 `/index.jsp`로 갈꺼에요 ~~!!

2021-09-09 10:53 UTC, jujubebat commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            }
작성해주신대로 읽기 좋게 한줄로 수정했습니다 😃

현재 initHandlerMappings 메서드에서는 AnnotationHandlerMapping 객체에 대한 초기화만 이루어집니다.  
ManualHandlerMapping 객체는 AppWebApplicationInitializer에서 한 개 생성되어 한 번 초기화가 이루어지는데, 다시 살펴주실 수 있나요??

2021-09-09 10:54 UTC, jujubebat commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            ControllerScanner controllerScanner = new ControllerScanner("com.techcourse.controller");
감사합니다 ㅎㅎ 사실 구구가 [여기](https://techcourse.woowahan.com/s/O1qsxIcH/ls/3MQShTa5)에서 힌트 주셔서 참고해서 진행했습니다!

2021-09-09 11:11 UTC, jujubebat commented on mvc/src/main/java/nextstep/web/annotation/RequestMapping.java
> +    RequestMethod method();
똑같은 uri 매핑을 가지면서, 다른 http method를 가지는 컨트롤러 메서드들이 있더라도 정상 동작하도록 리팩터링 했습니다!!

2021-09-09 11:19 UTC, jujubebat commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    }
현재 스프링 MVC에서 핸들러 매핑과 핸들러 어댑터 등의 인터페이스를 제공해주는데, 우리가 인터페이스를  직접구현한 커스텀 핸들러 매핑과 핸들러 어댑터를 빈으로 등록하여 사용할 수 있듯이 저도 그렇게 해봤습니다!

다시 말하자면 프레임워크가 기본적으로 제공하고 있는 핸들러 매핑, 핸들러 어댑터 외에 프레임워크 사용자가 커스텀한 핸들러 매핑과 핸들러 어댑터를 추가할 수 있는 확장 구조를 갖고 있게 했습니다.

지금 제가 구현한 MVC 프레임워크는 AnnotationHandlerMapping과 AnnotationHandlerAdaptor를 기본적으로 제공하고 있고,
프레임워크 사용자(app 모듈)가 커스텀한 핸들러 매핑, 핸들러 어댑터(ManualHandlerMapping, ManualHandlerAdaptor)를 추가하는 구조라고 생각하시면 될 것 같아요!! 

코다 생각은 어떠신가요??

2021-09-09 11:20 UTC, jujubebat commented on app/src/main/java/com/techcourse/controller/LogoutController.java
> +        return "redirect:/index.jsp";
오오 그렇군요 ㅎㅎ 수정했습니다!!

2021-09-10 06:26 UTC, yjksw commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            }
수정 감사합니다 ~! ㅎㅎㅎ 😊

<img width="1000" alt="스크린샷 2021-09-10 오후 3 09 48" src="https://user-images.githubusercontent.com/63405904/132807875-e892ab9b-558d-4623-b58c-ba7526f91c91.png">

로그에 이렇게 두번 initialize() 되는 부분이 찍혀서 확인해보니 
`addHandlerMapping()` 에서 먼저 초기화가 되고 `initHandlerMapping()`에서 handlerMapings 배열을 돌면서 `initialize()`할때 이미 들어가 있던 `ManualHandlerMapping`이 한번 더 초기화 되고 있는 것 같아요 ~!

2021-09-10 08:45 UTC, yjksw commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    }
오오 그래서 두 가지 경우 모두 HandlerMappings를 추가할 수 있도록 구현하신거군요 !! 👍😊
우기가 말해주신 부분은 저는 고려하지 못하고 구현을 했어서 대신 Spring MVC에서 어떻게 했는지 확인을 해봤어요~! 

확인 해보니까 `DispatcherServlet`내에 `initHandlerMappings()` 라는 메서드 내에서 우선 빈으로 등록된 `handlerMappings`들이 있는지 확인을 하고, 없다면 `DispatcherServlet.properties`에 `default`로 등록되어 있는 `handlerMappings` 들을 추가해주고 있더라구요 !! 

<p align="center"><img width="892" alt="스크린샷 2021-09-10 오후 5 41 14" src="https://user-images.githubusercontent.com/63405904/132826237-9f3fdd2c-ba6b-47b3-9a71-c1c57bac3a6f.png"><br>DispatcherServlet.properties 내에 선언된 default HandlerMappings</p>

<p align="center"><img width="1085" alt="스크린샷 2021-09-10 오후 5 41 41" src="https://user-images.githubusercontent.com/63405904/132826298-b908e521-0b59-49bc-8f6e-26916bdf9827.png"><br>DispatcherServlet.java 내에 빈으로 등록된 HandlerMappings들을 탐색하는 소스코드</p>

위 SpringMVC 구조는 다만 참고용이고 이 프레임워크가 꼭 맞는 구조라고 생각하지는 않아요ㅎㅎ 다만 여러 핸들러매핑을 한 메서드에서 추가하고 초기화 하면 관리 포인트가 줄어든다는 점에서 장점이 있을 것 같다는 생각이 드네요!! 

우기가 말씀하신 이유도 충분히 좋은 이유여서 우기가 설계하신대로 구현하거나 수정하셔도 될 것 같아요 👍

2021-09-10 08:47 UTC, yjksw approved these changes
안녕하세요 우기 ~!! 
리팩토링 한 부분들 잘 확인했어요 👍

우기가 남겨주신 의견도 잘 읽어보고 나름의 코멘트도 달았어요 !! 
기능은 이전에도 충분히 잘 동작하고 있었기 때문에 바로 머지하려고 해요 !! 

추가로 남긴 코멘트와 우기가 의견을 물어본 부분, 초기화 관련 이슈 확인하고 다음 단계 진행하면서 반영하거나 DM이나 코멘트로 의견을 남겨주시면 될 것 같습니다 😊

수고하셨어요 ~!! 환절기 감기 조심하세요 ㅎㅎ 🙌

2021-09-10 08:47 UTC, merged

2021-09-12 06:27 UTC, jujubebat commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    }
저도 핸들러 매핑 추가 부분을 한곳에서 하면 관리 포인트가 줄어든다는 코다 의견에 동의합니다ㅎㅎ
이렇게 내부구조 분석도 해주시고 공유해주셔서 너무 감사합니다!!!! 😃

2021-09-12 06:28 UTC, jujubebat commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            }
앗 제가 혼동이 있었나보네요 죄송합니다 ㅠㅠ 이부분 수정해서 2단계 미션 제출하도록 할께요 ㅎㅎ