[MVC 구현하기 - 1단계] 더즈(이동규) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #146
Opened 2022-09-19 06:54 UTC by ldk980130

안녕하세요 애쉬! 더즈입니다.

우선 아래 체크 리스트 요구 사항은 만족하였습니다.

- [x] AnnotationHandlerMappingTest가 정상 동작한다.
- [x] DispatcherServlet에서 HandlerMapping 인터페이스를 활용하여 AnnotationHandlerMapping과 ManualHandlerMapping 둘다 처리할 수 있다.

많이 부족한 코드이지만 잘 부탁드립니다!!

2022-09-19 15:34 UTC, dongho108 requested changes
안녕하세요 더즈!
전반적으로 코드가 깔끔해서 읽기도 편하고 리뷰하기도 편했습니다~
저도 더즈한테 배워가는 코드도 많았구요 ㅎㅎ 덕분에 제 코드 문제점도 알 수 있었습니다.

몇가지 코멘트 달아봤는데요. 궁금한점 있으면 언제든지 DM 주셔도되고 직접찾아주셔도 됩니다~!
고생하셨습니다!!

- a, c, r 의 의미
a : 반영하지 않아도 상관없습니다.
c : 고려해주셨으면 좋겠습니다.
r : 반영해주세요/

2022-09-19 15:34 UTC, dongho108 commented on mvc/src/main/java/nextstep/mvc/handler/HandlerExecution.java
> +        Object handler = createHandlerInstance(method.getDeclaringClass());
이렇게 클래스와 인스턴스를 가져오는 방법도 있었네요.. ㄷㄷ 배워갑니다.

2022-09-19 15:34 UTC, dongho108 commented on mvc/src/main/java/nextstep/mvc/handler/HandlerKey.java
> +        return new HandlerKey(requestMapping.value(), requestMapping.method()[0]);
만약 어노테이션이 이렇게 정의되어있다면 핸들러를 찾을 수 없을 것 같아요!
`@RequestMapping(value = "/post-test", method = {RequestMethod.POST, RequestMethod.GET})`

r: 한 url에 매핑된 여러 메서드도 다 등록할 수 있도록 수정해야할 것 같습니다!

2022-09-19 15:34 UTC, dongho108 commented on mvc/src/main/java/nextstep/mvc/handler/mapping/AnnotationHandlerMapping.java
> +        return handlerExecutions.get(HandlerKey.fromRequest(request));
c: 만약 존재하지 않는 key라면 예외를 반환할 것 같은데 검증을 추가해보는게 어떨까요?

2022-09-19 15:34 UTC, dongho108 commented on mvc/src/main/java/nextstep/mvc/handler/mapping/AnnotationHandlerMapping.java
> +    }
메서드의 용도나 로직을 보면 `findRequestMapping` 라는 메서드 이름이 어색하다는 느낌이 들어요
일단 이 메서드 자체는 RequestMapping이라는 것도 모르고 있는데 이름으로 가지고 있는것도 그렇구요!

c: 아래의 `addHandlerExecution`와 더불어서 메서드 이름을 다시한번 지어보는 것이 어떨까요?

(해당 메서드의 네이밍을 지은 이유가 있다면 달아주셔도 좋습니다. ㅎㅎ)

2022-09-19 15:34 UTC, dongho108 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            .orElseThrow();
r: 아무 Exception도 반환하지 않네요!

2022-09-19 15:34 UTC, dongho108 commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
> +        return viewName.startsWith(JspView.REDIRECT_PREFIX);
r: JspView에서 선언된 스태틱 상수이므로 JspView를 뗄 수 있지 않을까요?

그러면 상수를 private으로 지정해도될 것 같습니다!

```suggestion
        return viewName.startsWith(REDIRECT_PREFIX);
```

2022-09-20 12:33 UTC, ldk980130 commented on mvc/src/main/java/nextstep/mvc/handler/HandlerKey.java
> +        return new HandlerKey(requestMapping.value(), requestMapping.method()[0]);
아래 처럼 여러 메서드에 같은 로직을 처리할 수 있도록 변경하겠습니다!
```
for (RequestMethod method : requestMapping.method()) {
    handlerExecutions.put(
        new HandlerKey(requestMapping.value(), method),
        execution
    );
}
```

2022-09-21 04:17 UTC, dongho108 commented on mvc/src/main/java/nextstep/mvc/handler/mapping/AnnotationHandlerMapping.java
> +        return handlerExecutions.get(HandlerKey.fromRequest(request));
혹시 이 부분은 반영하지 않으신 이유가 있을까요?!

2022-09-21 05:55 UTC, ldk980130 commented on mvc/src/main/java/nextstep/mvc/handler/mapping/AnnotationHandlerMapping.java
> +        return handlerExecutions.get(HandlerKey.fromRequest(request));
```
private Object getHandler(final HttpServletRequest request) {
        return handlerMappings.stream()
                .map(handlerMapping -> handlerMapping.getHandler(request))
                .filter(Objects::nonNull)
                .findFirst()
                .orElseThrow(() -> new NoSuchElementException("매핑되는 핸들러가 없습니다."));
    }
```
해당 코드를 사용하는 클라이언트 코드쪽에서 null 체크를 하고 있어서 그대로 뒀던 것 같습니다. 코멘트 남기는 걸 깜빡했네요ㅠㅠ

그런데 AnnotationhandlerMapping이 null을 반환하는 것이 좋아 보이진 않으니 Optinal을 반환하도록 변경해보았습니다.

2022-09-22 07:14 UTC, dongho108 commented on mvc/src/main/java/nextstep/mvc/handler/mapping/AnnotationHandlerMapping.java
> +        return handlerExecutions.get(HandlerKey.fromRequest(request));
해당 코드를 사용하는 클라이언트 코드쪽에서 null 체크를 하고 있어서 저도 괜찮을 것 같다는 생각이 드네요 ..; ㅎㅎ
인터페이스를 변경해서 반영한 방식이 추후에 미션진행할때 혹시

2022-09-22 07:19 UTC, dongho108 approved these changes
더즈! 1단계 미션 진행하느라 고생하셨습니다.
코멘트 하나 남겼는데 읽어보시고 더즈가 판단해주세요!
머지하겠습니다~

2022-09-22 07:19 UTC, dongho108 commented on mvc/src/main/java/nextstep/mvc/handler/mapping/AnnotationHandlerMapping.java
> +    }
해당 코드를 사용하는 클라이언트 코드쪽에서 null 체크를 하고 있어서 저도 더즈가 원래했던 괜찮을 것 같다는 생각이 드네요 ..; ㅎㅎ

인터페이스를 변경해서 반영한 방식이 추후에 미션진행할때 혹시 영향이 갈까봐 저는 원래 더즈가 작성했던 방식도 괜찮을 것 같아요
일단 머지하고 더즈가 판단해서 유지할지 원래대로 변경할지 선택해서 반영해주세요~

2022-09-22 07:19 UTC, merged