[MVC 구현하기 - 1단계] 에덴(김성산) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #155
Opened 2022-09-19 11:27 UTC by leo0842

안녕하세요🙌 엘리!
MVC 구현하기 리뷰를 부탁드리게 된 에덴입니다:)

처음에는 annotation handler 를 등록만하고 제출하려했는데 사복 경찰에 걸려버렸어요 😢 
그래서 handler adapter 를 추가하여 처리가 가능하도록 로직을 추가하였습니다.

잘부탁드립니다 🙇‍♂️

2022-09-20 08:33 UTC, RIANAEH requested changes
안녕하세요🙌 에덴!
리뷰를 맡게된 엘리입니다~

전체적으로 객체 분리도 잘해주시고 깔끔하게 구현해주신 것 같아요💯
테스트도 추가해주신 모습 굿입니다~~
몇가지 코멘트 남겼는데, R(request) 부분은 꼭 확인해주셨으면 좋겠습니당!

2022-09-20 08:33 UTC, RIANAEH commented on app/src/main/java/com/techcourse/AppWebApplicationInitializer.java
> +        DispatcherServlet dispatcherServlet = new DispatcherServlet();
C: 전체적으로 `final var`를 제거하고 타입을 선언해주셨는데, 이렇게 한 이유가 있을까요?
에덴이 생각하는 `var` 키워드의 장/단점을 말해주세요!

2022-09-20 08:33 UTC, RIANAEH commented on app/src/main/java/com/techcourse/AppWebApplicationInitializer.java
> +        dispatcherServlet.addHandlerMapping(new AnnotationHandlerMapping(packageName));
A: 꼼꼼히 basePackage를 제한해 주셨네요!👏
저는 이 부분을 신경쓰지 못해 basePackage를 넣어주지 않았어서, 이런 경우 어디의 클래스를 스캔하는지 궁금해 살펴봤더니 .../main/java/* 모두를 스캔하더라구요ㅎㅎ 저도 추가해줘야겠네요:)

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    public void addHandlerAdapters(HandlerAdapter handlerAdapter) {
R: fina을 사용한 곳도 있고 사용하지 않은 곳도 있더라구요! 에덴만의 컨벤션을 정해 전체적으로 적용해주면 좋을 것 같아요!

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            ModelAndView mav = ha.handle(request, response, controller);
R: 변수명을 줄여쓴 특별한 이유가 있을까요?

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            view.render(mav.getModel(), request, response);
C: 현재 `ModelAndView`에서 두개의 필드를 가져와 사용하고 있는데, 에덴은 `render`의 책임이 어디에 있다고 생각하시나요?

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        }
C: stream을 사용하면 indent depth를 줄일 수 있지 않을까요?

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        throw new NoHandlerAdapterFoundException();
A: custom exception 사용 굿!👏

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>                  .orElseThrow();
R: `orElseThrow()`를 그냥 사용할 경우 어떠한 예외가 발생할까요? 세부적으로 예외를 처리해보면 어떨까요?

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            RequestMapping requestMapping = method.getDeclaredAnnotation(RequestMapping.class);
R: `@Controller`가 붙어있는 클래스 안에 `@RequestMapping`이 붙지 않은 메서드가 있는 경우 `NPE`가 발생하더라구요. 처리가 필요할 것 같아요~

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +    }
```suggestion
    private Object getInstance(Class<?> controller) {
        try {
            return controller.getConstructor().newInstance();
        } catch (InstantiationException | IllegalAccessException | InvocationTargetException |
                 NoSuchMethodException e) {
            throw new RuntimeException(e);
        }
    }
```
R: try에서 바로 return할 수도 있을 것 같은데, 로컬 변수로 선언해 return한 이유가 궁금해요~

추가적으로 checked exception을 RuntimeException으로 변환해 처리하신 이유도 궁금합니다~

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        }
A: 다음과 같이 여러 메서드를 받아서 처리할 수 있겠네요! 굿굿!!👏

```java
@RequestMapping(value = "/get-test", method = {RequestMethod.GET, RequestMethod.POST})
```

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutions.java
> +public class HandlerExecutions {
A: 일급컬렉션을 만들어 책임을 분리했군요! 굿!!👏

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/controller/tobe/ManualHandlerAdapter.java
> +        String value = controllerHandler.execute(request, response);
C: 변수명을 변경해 가독성을 높여보면 좋을 것 같아요~

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
> +        requestDispatcher.forward(request, response);
C: RequestDispatcher가 어떤 일을 해주는지 학습하셨는지 궁금합니다! 공유해주세요~

2022-09-20 08:33 UTC, RIANAEH commented on mvc/src/main/java/nextstep/web/support/RequestUrl.java
> +public class RequestUrl {
C: `RequestUrl`는 어떤 역할을 위한 객체인가요?

2022-09-20 17:42 UTC, leo0842 commented on app/src/main/java/com/techcourse/AppWebApplicationInitializer.java
> +        DispatcherServlet dispatcherServlet = new DispatcherServlet();
var 키워드는 Java 10 부터 도입된 변수로, 컴파일 시점에 타입 추론이 가능합니다.
처음에 `키워드` 라고 적었는데 키워드는 아니라고 하네요!
즉 
```
String int = "int";
```
은 불가능하지만
```
String var = "var";
는 가능합니다!

장점
- 명시적으로 타입을 지정하지 않기때문에, 코드를 작성하는 시점에서 반환 타입 수정 등을 조금 더 수월하게 해줄 수 있고
- 주워들은건데 람다식에서 var 를 이용하여 `(@Nonnull var s) -> ...` 처럼 사용이 가능

단점
- 컴파일하기 이전, 개발자가 코드를 읽는 시점에서 타입을 추론해야하기 때문에;; 가독성이 좋지 않고
- 장점으로 말한 반환 타입 수정 시 컴파일 시점 이전에는 예외를 알 수 없기때문에 불편

등을 생각해 보았습니다.

저는 var 의 장단점을 생각해보면서 올해에는 var 를 쓰지 않기로 다짐하였습니다!

2022-09-20 17:45 UTC, leo0842 commented on app/src/main/java/com/techcourse/AppWebApplicationInitializer.java
> +        dispatcherServlet.addHandlerMapping(new AnnotationHandlerMapping(packageName));
ㅎㅎㅎ 저도 null 을 넣으면 어떻게 되는지 생각지 못했는데, 엘리가 말씀해주셔서 알게 되었네요!
null 들어왔다고 예외를 반환하지 않고 모두 스캔하는 거 50-700

2022-09-20 17:47 UTC, leo0842 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +    public void addHandlerAdapters(HandlerAdapter handlerAdapter) {
매번 final 자동으로 붙게 IDE 설정해줘야지 생각만 하면서 차일피일 미루고 있었는데 이번 엘리의 리뷰를 계기로 직접 찾아서 설정했고, 기존의 코드들의 파라미터에는 수작업으로 final 을 모두 넣어주었습니다 😄 

혹시 final IDE 설정이 궁금하시다면 제게 물어보세여 ㅎㅎ

2022-09-20 17:48 UTC, leo0842 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            ModelAndView mav = ha.handle(request, response, controller);
DispatcherServlet 의 내부에 저렇게 되어있길래 좀 유식해보이려고 저도 ha 로 써봤습니다 haha~

바로 `handlerAdapter` 로 수정했습니당

2022-09-20 17:52 UTC, leo0842 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            view.render(mav.getModel(), request, response);
이 부분은 엘리가 리뷰에 내포한 의도 그대로 코드 작성 시점에 생각해 보았었어요!

`ModelAndView` 에서 render 를 하는게 맞을까 아니면 `DispatcherServlet` 에서 꺼내서 사용하는 것이 맞을까 고민을 했었는데, getter 를 지양하라는 불문율이 있지만 이 부분에서는 `ModelAndView` 가 render 의 역할을 맡는 것이 다소 어색하다고 느껴, getter 로 꺼내 `DispatcherServlet` 에서 해당 역할을 수행하도록 작성해보았습니다!

엘리는 이 부분에 대해 어떻게 생각하시나요~? 😜😜

2022-09-20 17:53 UTC, leo0842 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        }
지당한 말씀입니다.. 제 코드와 DispatcherServlet 과의 의존성을 줄이도록 노력하겠습니다!!

2022-09-20 17:53 UTC, leo0842 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>                  .orElseThrow();
DIY 로 예외 클래스를 작성하였습니다~!

2022-09-20 18:02 UTC, leo0842 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            RequestMapping requestMapping = method.getDeclaredAnnotation(RequestMapping.class);
정말 꼼꼼하시네요 👀 꼼꼼걸
NPE 예외 로직 처리하였습니다!

2022-09-20 18:08 UTC, leo0842 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +    }
이유라기보다는 해당 메서드가 나온 정황을 말씀드리자면 IDE 의 도움을 받아 `.var` 로 변수를 만들어 주었고 IDE 의 도움을 또 받아 try catch 를 자동으로 만들어 주는 과정에서 발생한 코드입니다,, 잘못을 알았으니 앞으로 주의하겠습니다.

RuntimeException 으로 generic 하게 한 이유는 catch 되는 exception 이 많아서 그랬는데, 조금 더 명시적으로 예외를 처리하기 위해 InstanceInitializationException 이라는 클래스를 만들어 예외를 처리하였습니다!

지적 감사드립니다 🙇

2022-09-20 18:11 UTC, leo0842 commented on mvc/src/main/java/nextstep/web/support/RequestUrl.java
> +public class RequestUrl {
현재는 아무 일도 하지 않는 베짱이 객체여서 validate 를 간단하게 추가해 보았습니다!

추후에는 request url 을 찾을 때 조금 더 로직이 추가될 예정으로 생각할 예정입니다.

2022-09-20 18:49 UTC, leo0842 commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
> +        requestDispatcher.forward(request, response);
RequestDispatcher 는 요청한 자원을 wrap 하고 해당 자원으로 보내주는 역할을 합니다.

현재 로직에서는 `getRequestDispatcher()` 가 호출되면 ApplicationContext 객체에서 request 를 process 해서 ApplicationDispatcher 를 생성해줍니다!

ApplicationDispatcher 는 Wrapper class 로 uri, path, query string 정보들을 가지고 있습니다.
forward 는 가지고 있는 요청 관련 정보들(uri, path, query string)을 request와 response의 attribute 에 setAttribute 메서드를 통해 세팅해줍니다. 그리고 이 request 와 response 를 가지고 쭉쭉 가다보면 JspServlet 을 만나고 HttpJspBase 추상 클래스의 service 메서드에서 해당 resource 에 맞는 body 를 읽는 것 같은데 이 클래스는 디버깅이 안되네요

```
@Override
    public final void service(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException
    {
        _jspService(request, response);
    }
```

2022-09-21 06:53 UTC, RIANAEH commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            view.render(mav.getModel(), request, response);
저도 현재는 getter로 view와 model을 꺼내와 render를 수행하는 구조를 가지고 있어요. 
이렇게 했던 이유는 render의 책임을 Spring MVC의 ViewResolver가 가지고 있는 것 처럼 다른 객체에 넘겨줄 수 있겠다고 생각했지만, 현재 JSP view만 사용 중이고 JSON view까지 추가됐을 때 어떻게 진행될지 감이 잡히지 않아 현재 상황에서는 따로 객체를 생성하지 않고 단순히 DispatcherServlet에서 view.render()를 호출하도록 구현했던 것 이었어요. 
고민이 되는 부분이라 에덴의 생각이 궁금했었답니다~🎶

2022-09-21 06:58 UTC, RIANAEH approved these changes
안녕하세요🙌 에덴!

리뷰 반영해준 부분 모두 확인했습니다:)
리뷰를 너무 많이 남긴게 아닌가 하는 걱정이 있었는데, 
모든 리뷰에 정성들여 답글 남겨주셔서 감동이었답니다👏 최고!!

이만 머지하겠습니다~ 다음 단계에서 만나요👋

2022-09-21 06:58 UTC, merged