[MVC 구현하기 - 1단계] 토닉(최우석) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #162
Opened 2022-09-19 17:05 UTC by tonic523

포키! 너무 반갑네요 ㅎㅎ
포키 리뷰를 받을 수 있다니.. 너무 떨리네요
잘 부탁드립니다! 😄

이번 구현은 크게 3가지로 분리했습니다.
- AnnotationHandlerMapping을 통해 요청에 따라 어노테이션이 붙은 클래스를 가져오기
- HandlerAdapter로 기존의 ManualHandlerMapping과 AnnotationHandlerMapping 둘 다 활용하기
- DispatcherServlet에 있는 View 관련 로직을 JspView로 옮기기

HandlerAdapter를 enum으로 구현했어요. enum을 정말 좋아하는 편이라.. 기존의 인터페이스로 구현했다가 enum으로 수정했습니다.
제 생각에 enum으로 했을 때 장점과 단점이 있는데요.
장점
- 중복 코드 제거
- dispatcherServlet의 역할 분리 (support -> handle)의 작업을 하나로 통합
- 하나의 파일에서 모든 Adapter를 관리할 수 있다.
- 정적 자원이기 때문에 싱글톤보다 조금 빠르다.

단점
- 추상화, oop의 이점을 누리지 못한다.
- Adapter가 늘어나거나 로직의 복잡도에 따라 하나의 파일에 코드량이 많아져 가독성이 떨어진다.

현재는 2개의 Adapter이기도 하고 코드의 양도 적어 enum이 적합하다고 생각해서 구현했는데 혹시 제가 고려하지 못한 내용이 있거나 의견 공유 부탁드립니다!

추가로 요구사항 중 2개의 HandlerMapping을 사용할 수 있도록 구현하기 위해 하나의 컨트롤러에 `Controller` 를 구현하고 어노테이션도 붙어있습니다. 그러다 보니 `AnnotationHandlerMapping`에서 리플렉션으로 Method를 가져올 때 GetDefaultMethod가 아닌 GetMethod로 가져오고 null 체크로 하는 형식으로 바뀌었어요. 이 부분을 어떻게 수정해야할 지는 현재 고민중입니다.

2022-09-20 07:43 UTC, YJGwon commented on app/src/main/java/com/techcourse/ManualHandlerMapping.java
> +        log.info("Initialized Manual Handler Mapping!");
controller 초기화가 모두 끝난 후에 Initialized log가 찍히는게 좋지 않을까요?

2022-09-20 07:47 UTC, YJGwon commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            final var handler = getHandler(request);
어떤 변수는 `final`, `var` 키워드로 선언되어 있고 어떤 변수는 type으로 선언되어 있어요. 변수 마다 특별한 이유가 있는게 아니라면, 코드 스타일을 통일해보는건 어떤가요?

2022-09-20 07:51 UTC, YJGwon commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            initHandlerExecutions(getInstance(controllerClass), controllerClass.getMethods());
어차피 `@RequestMapping` annotation이 달리지 않은 method는 `HandlerExecution`이 되지 않을텐데, 이 단계에서 `@RequestMapping` annotation을 가진 method만 가져올 방법은 없을까요?

2022-09-20 07:55 UTC, YJGwon commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        for (RequestMethod requestMethod : requestMapping.method()) {
indent 줄이기를 시도해볼까요 👀

2022-09-20 08:12 UTC, YJGwon commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerAdapter.java
> +public enum HandlerAdapter {
enum을 잘 활용해주셨네요 👍
HandlerAdapter를 추상화했을때와 비교하면, 토닉이 말씀해주신 장점 중에

- dispatcherServlet의 역할 분리 (support -> handle)의 작업을 하나로 통합
- 하나의 파일에서 모든 Adapter를 관리할 수 있다.

이렇게 두 가지가 가장 와닿는 장점인 것 같아요.
그러나 말씀하신 대로 HandlerAdapter가 많아지고 복잡해진다면 오히려 관리하기 불편할 수도 있을 것 같은데요, 실제로 [Spring HandlerAdapter](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/HandlerAdapter.html) 인터페이스의 All Known Implementing Classes도 6개더라고요.
위의 두 가지 장점은 일급 컬렉션으로도 얻어볼 수 있지 않을까 하는 생각이 드네요!

2022-09-20 08:23 UTC, YJGwon requested changes
안녕하세요 ~우석씨~토닉!! 이렇게 리뷰어와 리뷰이로 만나게 되어서 저도 반갑네요 🤭
먼저 실수로 리뷰를 모두 single comment로 달아버린점,,사과드립니다 ㅠ
Enum을 통한 처리에 대해서는 제 생각을 comment에 달아두었어요.
이해되지 않거나 논의해보고 싶으신 부분에 대해서는 언제든 편한 방법으로 연락주세요!

(+) Test 작성이 되어있지 않은데, `AnnotationHandlerMappingTest`의 mock test를 참고해서 토닉이 작성해주신 로직에 대해서도 Test를 작성해보면 좋을 것 같습니다.

2022-09-21 16:04 UTC, tonic523 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            final var handler = getHandler(request);
그렇네요! 타입 선언으로 통일하겠습니다

2022-09-21 16:18 UTC, tonic523 reviewed
포키 꼼꼼한 리뷰 감사합니다 ㅎㅎ
점점 이래저래 핑계로 테스트 작성을 소홀하게 되네요.. 반성합니다 😥
mock을 활용하니 어느정도 구현한 기능에 대한 테스트가 가능하네요!
추가로 컨트롤러 테스트를 구현하고 싶은데 이 부분은 2단계를 구현하면서 추가하겠습니다.

2022-09-21 16:18 UTC, tonic523 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            final var handler = getHandler(request);
그렇네요! 타입 선언으로 통일하겠습니다

2022-09-21 16:18 UTC, tonic523 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            initHandlerExecutions(getInstance(controllerClass), controllerClass.getMethods());
```java
List<Method> methods = Arrays.stream(controllerClass.getMethods())
.filter(method -> method.isAnnotationPresent(RequestMapping.class))
.collect(Collectors.toList());
```
클래스 타입에서 특정 어노테이션이 있는 메서드만 조회하는 메서드를 찾지 못했어요.
대신 public 메서드를 모두 조회하여 `isAnnotationPresent` 메서드로 필터링하는 방법으로 구현했습니다.

2022-09-21 16:18 UTC, tonic523 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        for (RequestMethod requestMethod : requestMapping.method()) {
Method for문에 대한 인덴트 줄이기를 말씀하시는건가요?

2022-09-21 16:18 UTC, tonic523 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +    private Object getInstance(Class<?> controller) {
getInstance() → toInstance() 로 수정했습니다.

2022-09-21 16:18 UTC, tonic523 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerAdapter.java
> +public enum HandlerAdapter {
오 문서에서 보니 확실히 enum 하나로 구현하기에는 너무 무거워지겠네요!
Adapter의 역할이 많아지면 포키가 알려준 일급 컬렉션과 인터페이스로 클래스를 분리해보겠습니다!

2022-09-22 09:57 UTC, YJGwon approved these changes
토닉 수고하셨습니다~! 테스트를 통해서 techcourse 패키지의 코드 수정 없이도 로직이 잘 작성된 것을 확인할 수 있게 되었네요!! 이번 단계는 머지하도록 하겠습니다. 데모데이 화이팅 💪 2단계에서 만나요 👋

2022-09-22 09:57 UTC, YJGwon commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        for (RequestMethod requestMethod : requestMapping.method()) {
아 인덴트 1이었네요 죄송합니다 💦

2022-09-22 09:57 UTC, merged