[MVC 구현하기 - 2단계] 마루(송채원) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #232
Opened 2022-09-25 12:35 UTC by chawani

주디 안녕하세요!🐰 마루입니다😊
2단계 미션 리뷰도 잘부탁드립니다~!

2022-09-25 14:34 UTC, jurlring reviewed
마루 안녕하세요~!
2단계를 잘 구현해주셨네요!!
요구사항은 다 만족하신 것 같은데 코드에 궁금한 부분이 있어서 코멘트를 남겨봤어요!
확인 후에 다시 요청 보내주세요!!

2022-09-25 14:34 UTC, jurlring commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        modelAndView.getView().render(modelAndView.getModel(), request, response);
dispatcherServlet에서 메서드를 분리하는 것이 아니라 modelAndView 내부에서 할 수 있지 않을까요?

2022-09-25 14:34 UTC, jurlring commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +    private void putHandlerExecutions(Class<?> controller, Object declaredObject) {
어떤 메서드 파라미터엔 final이 붙어 있고 어디엔 없네용?!
이유가 있으실까요?

2022-09-25 14:34 UTC, jurlring commented on mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java
> +            throw new RuntimeException(e);
RuntimeException을 throw하신 이유가 있나요?

2022-09-25 14:36 UTC, jurlring requested changes
앗 comment로 달아서 알람이 안가네요 ㅠ.ㅠ
코멘트를 달았으니 확인 부탁드려요!!

2022-09-26 04:03 UTC, chawani commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        modelAndView.getView().render(modelAndView.getModel(), request, response);
그러네용! 감사합니다!!

2022-09-26 04:04 UTC, chawani commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +    private void putHandlerExecutions(Class<?> controller, Object declaredObject) {
앗 기존에 final이 붙어있었는데 저는 final을 안붙이는 스타일이다보니 일관성이 사라져버렸네요🥲 최대한 맞춰보겠습니다!

2022-09-26 06:46 UTC, chawani commented on mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java
> +            throw new RuntimeException(e);
생각해보니 RuntimeException으로는 어떤 상황에 예외가 발생했는지 알기 어려울 것 같아 커스텀 예외를 생성하여 throw 하도록 하였습니다!

2022-09-26 11:58 UTC, jurlring approved these changes
마루 2단계 요구사항을 다 맞추신 것 같아서 다음 미션을 위해서 이만 머지할게요!
고생하셨습니다 🍔

2022-09-26 11:58 UTC, merged