[MVC 구현하기 - 3단계] 라라(박세은) 미션 제출합니다
woowacourse/jwp-dashboard-mvc pull request #236
Opened 2022-09-25 15:47 UTC by sure-why-not

루나 안녕하세요 💞
3단계 요구사항 완료하여 리뷰 요청 드립니다~
잘 부탁드려용 🙇🏻‍♀️

- [x] 힌트에서 제공한 UserController 컨트롤러가 json 형태로 응답을 반환한다.
- [x] 레거시 코드를 삭제하고 서버를 띄워도 정상 동작한다.
  - [x] app 모듈에 있는 모든 컨트롤러를 어노테이션 기반 MVC로 변경한다.

2022-09-26 06:05 UTC, RunaNam requested changes
라라 빠른 구현 수고하셨습니다~! 👍👍
간단하게 리뷰 몇가지만 드릴게요!

2022-09-26 06:05 UTC, RunaNam commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        return objectMapper.writeValueAsString(model);
👍 요구사항에 맞춰주셨군요!

2022-09-26 06:05 UTC, RunaNam commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +    private static final String LOGIN_REQUEST_PARAMETER_PASSWORD_KEY = "password";
해당 부분도 전부 상수로 빼신건 관리의 용이성을 위해서일까요?

2022-09-26 16:56 UTC, sure-why-not commented on app/src/main/java/com/techcourse/controller/RegisterViewController.java
> +        return new ModelAndView(new JspView(REGISTER_JSP_VIEW_NAME));
오 좋은 의견이네요!! Login / Register 관련 기능들을 한 Controller 에서 처리하도록 수정했습니다! 😎

2022-09-26 16:56 UTC, sure-why-not commented on app/src/main/java/com/techcourse/controller/LoginController.java
>          }
하핳 분리 좀 해보았습니다 😇

2022-09-26 16:56 UTC, sure-why-not commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        return objectMapper.writeValueAsString(model);
🤭

2022-09-26 16:57 UTC, sure-why-not commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +    private static final String LOGIN_REQUEST_PARAMETER_PASSWORD_KEY = "password";
상수로 분리해서 의미를 명확하게 하고싶었어요!! 😄

2022-09-26 16:58 UTC, sure-why-not commented
루나 안녕하세요!! 🦸🏼‍♀️
리뷰 반영했습니다 ㅎㅎ
1,2,3단계동안 값진 리뷰해주셔서 감사해용 ~~~~~~ 💘

2022-09-27 07:33 UTC, sojukang commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +    private static final String LOGIN_REQUEST_PARAMETER_PASSWORD_KEY = "password";
의미를 파악하기 더 힘들어진 것 같아요

2022-09-27 07:54 UTC, RunaNam commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +    private static final String LOGIN_REQUEST_PARAMETER_PASSWORD_KEY = "password";
라고 하시네요 저도 한곳에서 쓰는 경우에는 크게 분리하지는 않는 편입니다 👍

2022-09-27 08:33 UTC, RunaNam requested changes
빠른 구현 수고하셨습니다~! 
구현된 부분에서 테스트만 조금 더 추가하면 좋을 것 같아요! 👍

2022-09-27 14:02 UTC, sure-why-not commented on app/src/main/java/com/techcourse/controller/UserController.java
> +    public ModelAndView show(HttpServletRequest request, HttpServletResponse response) {
앗 추가했습니다 !!!

2022-09-27 14:02 UTC, sure-why-not commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        return objectMapper.writeValueAsString(model);
좋네요 ㅎㅎ 추가했습니다~ 😄

2022-09-28 11:13 UTC, RunaNam approved these changes
깔끔하게 잘 구현해주셨네요! 
이번 미션도 수고하셨습니다~~!! 👍👍👍

2022-09-28 11:13 UTC, merged