[MVC 구현하기 - 3단계] 후니(최재훈) 미션 제출합니다
woowacourse/jwp-dashboard-mvc pull request #252
Opened 2022-09-26 06:33 UTC by jayjaehunchoi

안녕하세요 에덴 !

3단계 미션 제출합니다!
감사합니다 ㅎㅎ

2022-09-27 13:26 UTC, sure-why-not commented on mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java
> +
테스트가 없네요. 😈

2022-09-28 02:37 UTC, leo0842 commented on mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java
> +
> 

관심가져주셔서 감사합니당 ㅎ-ㅎ

2022-09-28 03:56 UTC, leo0842 requested changes
안녕하세요 후니! 에덴입니다 😄 

3단계도 깔끔하게 잘 구현해 주셨네요!!

로직상 크게 고쳐야할 부분이 없어서 자잘한 부분에 리뷰 남겨봤어요!

확인해주시고, 반영할 부분에 반영해주시면 됩니다!!

2022-09-28 03:56 UTC, leo0842 commented on app/src/main/java/com/techcourse/domain/User.java
> +    }
password 도 함께 응답하고 있네용!!

2022-09-28 03:56 UTC, leo0842 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +                .forEach(key -> log.info("Path : {}, Controller : {}", key.getUrl(), key.getRequestMethod()));
꼼꼼한 로깅 배워갑니다 😄

2022-09-28 03:56 UTC, leo0842 commented on app/src/main/java/com/techcourse/controller/LoginViewController.java
> +public class LoginViewController {
LoginViewController 와 LogoutController 는 LoginController와 같은 aspect 인 것 같은데 LoginController 로 통합해보는건 어떨까요??

2022-09-28 12:37 UTC, merged