[MVC 구현하기 - 3단계] 스컬(김윤기) 미션 제출합니다
woowacourse/jwp-dashboard-mvc pull request #254
Opened 2022-09-26 07:34 UTC by skullkim

마지막 단계도 잘부탁해요😊

2022-09-27 04:39 UTC, SuyeonChoi requested changes
안녕하세요 스컬! 벌써 MVC 구현하기의 마지막 PR이네요🥳🥳
3단계도 매우 빠르게 구현해주셨군요👍
저번 PR을 머지하면서 마지막에 요청드린 테스트까지 꼼꼼하게 구현해주셨네요! 
수고 정말정말 많으셨습니다〰️👏👏👏

이번에도 RCA 룰에 맞춰서 리뷰 했습니다!
제 주관적인 견해도 있으니 `c`와 `a`에 해당하는 리뷰는 스컬의 마음에 맡길게요ㅎㅎ
그럼 조금만 더 화이팅바리🔥🔥!!!
```
👩🏻‍⚖️ RCA 룰?
r: 꼭 반영해 주세요. (Request changes)
c: 웬만하면 반영해 주세요. (Comment)
a: 그냥 사소한 의견입니다. (Approve)
```

2022-09-27 04:39 UTC, SuyeonChoi commented on app/src/main/java/com/techcourse/controller/RegisterController.java
> +    @RequestMapping(value = "/register/view", method = RequestMethod.GET)
a: 이제 RequestMethod로 요청 타입에 대해 구분이 가능하니 `/view`같은 추가적인 문자열을 제거하면 더 간단한 uri로 표현할 수 있겠네요!

2022-09-27 04:39 UTC, SuyeonChoi commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +                .write(body);
r: _model에 값이 하나인 경우 값을 그대로 반환한다._ 라는 요구사항을 만족하도록 추가적인 로직이 필요해보입니다🤓
<img width="942" alt="image" src="https://user-images.githubusercontent.com/28749734/192431153-9aad3514-1c1d-468d-94d3-52738b93f881.png">

2022-09-27 04:39 UTC, SuyeonChoi commented on mvc/src/main/java/nextstep/web/support/Header.java
> +}
a: Header 클래스 구현!! 저는 생각도 못해봤는데 꼼꼼하시군요👍👍

2022-09-27 04:39 UTC, SuyeonChoi commented on mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java
> +import org.junit.jupiter.api.DisplayName;
a: 사용되지 않는 import문이있네요! 삭제하거나 테스트에 `@DisplayName`을 사용하면 좋을거 같습니다😋

2022-09-27 04:39 UTC, SuyeonChoi commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +                .write(body);
c: 해당 클래스에 대한 테스트도 추가하면 좋을거 같아요😉😉

2022-09-27 05:30 UTC, skullkim commented on app/src/main/java/com/techcourse/controller/RegisterController.java
> +    @RequestMapping(value = "/register/view", method = RequestMethod.GET)
수정할게요~

2022-09-27 06:04 UTC, skullkim commented on mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java
> +import org.junit.jupiter.api.DisplayName;
삭제할게요~

2022-09-28 01:52 UTC, SuyeonChoi approved these changes
안녕하세요 스컬~!
리뷰 반영해주신거 확인했습니다👍👍
정말 수고 많으셨어요!!
요구사항이 모두 만족되었으니 미션은 여기서 마무리할께요!!

다음 미션도 화이팅입니다🔥🔥

2022-09-28 03:48 UTC, merged