[MVC 구현하기 - 3단계] 티키(방영호) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #269
Opened 2022-09-26 11:11 UTC by yh20studio

안녕하세요 코린 3단계 미션 구현 완료했습니다.
Legacy Controller를 모두 어노테이션 기반으로 변경하고, 어플리케이션을 실행해보았을 때 문제 없는 것까지 확인 했습니다.

다만, 기존에 있던 ManualController를 지원하기 위해서 필요했던 코드들은 삭제하지 않았는데요. 이에 코린은 어떻게 하는 것이 좋아 보이는지 의견 물어봅니다!

2022-09-27 06:59 UTC, hamcheeseburger requested changes
티키 안녕하세요~! 3단계 미션 빠르게 구현해주신거 확인했습니다!!
기존 ManualController를 지원하기 위한 코드들 중 mvc 패키지에 존재하는 것들은 유지하는게 좋다고 생각합니다! 사용자가 원하는 대로 구현할 수 있는 확장성을 열어두는 것이라고 생각해요.
다만 app 패키지는 사용자가 구현하는 코드이기 때문에, 현재 사용하지 않는 `ManualHandlerMapping`은 제거해도 좋을 것 같아요!!

아직 merge기간이 좀 남았기 때문에 일단은 RC 드리겠습니다~~!!!

2022-09-27 06:59 UTC, hamcheeseburger commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        }
👍🏻

2022-09-27 06:59 UTC, hamcheeseburger commented on mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java
> +        manualHandlerMapping.initialize();
DispatcherServletTest니까 DispatcherServlet의 `init()`을 사용해도 될것같군요!

2022-09-27 07:01 UTC, hamcheeseburger commented on mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java
> +        manualHandlerMapping.initialize();
저번 단계 때 달았어야 했는데, Handler랑 HandlerAdapter를 찾지 못했을 때 예외가 발생하는 케이스도 테스트 하면 좋을 것 같아요 :)

2022-09-28 10:50 UTC, yh20studio commented on app/src/main/java/com/techcourse/controller/LoginViewController.java
> +    @RequestMapping(value = "/login/view", method = RequestMethod.GET)
네! 반영했습니다 훨씬 깔끔해졌네요

2022-09-28 12:17 UTC, yh20studio commented on app/src/main/java/com/techcourse/controller/LoginViewController.java
> +                    return new ModelAndView(new JspView("redirect:/index.jsp"));
맞네요! 공감합니다 변경하겠습니다

2022-09-28 12:32 UTC, yh20studio commented on mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java
> +        manualHandlerMapping.initialize();
네 추가했습니다!

2022-09-29 08:06 UTC, merged