[MVC 구현하기 - 1단계] 코다(김윤정) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #28
Opened 2021-09-08 11:43 UTC by yjksw

에어 안녕하세요 ~~!!! 코다입니다 :)

모듈간 의존하고 있는 구조와 스프링 MVC의  DispatcherServlet 에서 HandlerAdapter, HandlerMapping, ModelAndView를 어떻게 처리하는지 공부하느라 시간이 좀 걸린 것 같아요 ~~!!! 

두개의 controllerMapping(기존의 controller interface 형식, annotation 형식)이 공존하는지 확인하기 위해서 
login에 관련된 컨트롤러 메서드를 AnnotationLoginController에 어노테이션 형식으로 옮기고 기존 Controller를 ManualHandlerMapping에서 제거했습니다. 🙌

이번에 하면서 ManualHandlerMapping은 app 모듈에 있는데 AnnotationHandlerMapping은 mvc 프레임 영역에 가깝다고 생각이 들어서 mvc 모듈에 포함했어요 !! 살짝 어색한 것도 같긴 한데 ,, 에어는 어떻게 생각하나요 ?? 

나름 보면서 비슷하게 구현하려고 했는데 `AnnotationHandlerMapping` 의 `initialize()`부분의 코드가 지저분한거 같네요 ㅠㅠㅠ 

엄청난 리뷰 기대할게요 ...^^ 
리뷰 잘 부탁드립니다 ~~!! 😊🎉

2021-09-08 17:57 UTC, KJunseo requested changes
코다~ 역시 구현 잘해주셨네요 👍🏻👍🏻 정말 고생 많으셨어요!!

엄청난 리뷰를 바라셨는데 기대를 충족시키지 못할까 걱정이네요 😭.. 그래도 꼼꼼히 봤습니다 ㅎㅎ
더 봐 줬으면 하는 부분이나, 제 의견이 궁금한 부분이 있으면 언제든지 연락주세요!

몇 가지 코멘트 남겼습니다! 제 의견일 뿐이니 다 반영하실 필요는 없을 것 같아요! 코멘트 보시고 다시 요청해주세요!

2021-09-08 17:57 UTC, KJunseo commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
>      public void initialize() {
initialize()의 내부 로직을 분리해도 좋을 것 같아요!

지금 initialize()가 크게 아래의 과정을 수행하는 것 같아요
1. `@Controller`가 붙은 모든 클래스 찾기
2. 찾은 클래스 내부에서 `@RequestMapping`이 붙은 모든 메서드 찾기
3. 메서드를 순회하면서 handlerExecution 생성

이 각각을 클래스나 메서드로 분리해주면 어떨까요?

```java
// 이런 느낌..? 참고만 해주세요 ㅎ..
public void initialize() {
    findControllers();
    for (controller) {
        findMethods();
        registerHandlerExecution();
    } 
}
```

2021-09-08 17:57 UTC, KJunseo commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
> +            clazz.getConstructor().newInstance(),
HandlerExecution의 필드로 클래스타입을 가지고 있게 하신 이유가 있을까요?? 필드로 실제 인스턴스를 가지게 하는 건 어떻게 생각하시나요??

현재 구조는 HandlerExecution의 handle() 메서드 내에서 클래스 타입을 통해 인스턴스를 생성하는 것 같아요! 
이런 경우 동일한 컨트롤러 클래스 내의 메서드여도 요청에 따라 매번 컨트롤러 클래스 인스턴스 자체를 새로 생성하는 문제가 있을 것 같아요!

만들어두신 `AnnotationLoginController`를 예를 들면,  `AnnotationLoginController` 내부에는 login, loginView, logout 3가지 컨트롤러 메서드가 존재하는데, 각 요청에 따라 `AnnotationLoginController`를 계속 생성하는 문제가 있을 것 같아요! `AnnotationLoginController`를 하나만 만들어놓고 가져다 쓰면 좋지 않을까요??

2021-09-08 17:57 UTC, KJunseo commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        Map<String, ? extends Class<?>> controllers = reflections
실제 인스턴스를 만들지 않고 클래스 타입만 가지고 있게 구현하신 이유가 있으실까요??

2021-09-08 17:57 UTC, KJunseo commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            .filter(method -> method.getDeclaredAnnotation(RequestMapping.class) != null)
isAnnotationPresent을 사용해도 되겠네요!
```suggestion
           .filter(method -> method.isAnnotationPresent(RequestMapping.class))
```

2021-09-08 17:57 UTC, KJunseo commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +    private void addHandlerExecution(Map<String, ? extends Class<?>> controllers, Method method, String value, RequestMethod[] requestMethods) {
파라미터가 4개나 되는데 줄여 볼 수 있지 않을까요? 
initialize()를 클래스나 메서드 분리해가면 줄일 수 있을 것 같아요!

2021-09-08 17:57 UTC, KJunseo commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            log.info("Path : {}, Controller : {}", value, method.getDeclaringClass().getSimpleName());
이건 사소한 부분이긴한데 로그를 보고 조금 헷갈리더라구요!
<img width="916" alt="스크린샷 2021-09-09 오전 2 43 55" src="https://user-images.githubusercontent.com/45876793/132558720-6a494794-99e2-42c0-826c-469053e424b9.png">

HTTP method와 url, HandlerExecution 관련 정보(어떤 컨트롤러의 어떤 메서드인지)를 찍어주면 더 보기 편할 것 같다는 개인적인 생각입니다!

2021-09-08 18:16 UTC, KJunseo commented
>이번에 하면서 ManualHandlerMapping은 app 모듈에 있는데 AnnotationHandlerMapping은 mvc 프레임 영역에 가깝다고 생각이 들어서 mvc 모듈에 포함했어요 !! 살짝 어색한 것도 같긴 한데 ,, 에어는 어떻게 생각하나요 ??

저도 이번에 구현해보면서 고민해 본 부분이에요! 우선 저는 `ManualHandlerMapping`과 `AnnotationHandlerMapping` 둘 다 mvc 모듈에 뒀어요! 그 이유는 둘 다 프레임워크에서 지원하는 HandlerMapping이라는 생각이 들어서에요.

`AnnotationHandlerMapping`같은 경우는 프레임워크에서 제공하는 어노테이션기반으로 핸들러를 찾아주기 때문에 프레임워크 영역이라고 생각했어요! 
`ManualHandlerMapping`같은 경우는 보는 관점에 따라 다를 수 있다고 생각해요. 
1) app 모듈에 존재하는 컨트롤러를 직접 등록해주기 때문에 app 모듈이다. 프레임워크에서 제공하는 HandlerMapping 인터페이스를 커스텀했다고 생각할 수 있다.  
2) 프레임워크에서 제공하는 HandlerMapping 인터페이스를 구현하고있기 때문에 프레임워크 영역이다. 

저는 2번의 경우로 생각을 하고 구현을 했어요! 그러나 이 경우 app 모듈에 존재하는 컨트롤러를 mvc 모듈내에서 등록하는 건 이상하다고 생각했어요. 그래서 mvc 모듈 내에서 직접 app 모듈의 컨트롤러를 등록하지 않고, mvc 모듈에 `HandlerConfigurer`라는 인터페이스를 만들고 app 모듈에서는 `HandlerConfigurer`를 구현하여 app모듈에서 사용자가 직접 컨트롤러를 등록하도록 구현했어요. 

예를 들어 스프링부트를 사용시,  인터셉터를 등록할 때 `WebMvcConfigurer`를 구현하여 직접 등록해주는 느낌?으로 구현했어요. 인터셉터 처리 자체는 프레임워크가 관리하지만, 사용자가 app단에서 직접 인터셉터를 등록하듯이?? 그래서 `ManualHandlerMapping`자체는 mvc 모듈에 두고, `ManualHandlerMapping` 내부 컨트롤러들은 app 모듈에서 등록해줄 수 있게 처리했습니다!

결론적으로 저는 현재 코다 구조도 괜찮다고 생각해요! 위에서 말했듯 관점의 차이인 것 같아요!

2021-09-11 14:40 UTC, yjksw commented on app/src/main/java/com/techcourse/controller/annotationcontroller/AnnotationLoginController.java
> +    @RequestMapping(value = "/login", method = {RequestMethod.GET, RequestMethod.POST})
엇 사실 이건 어떤 요청이 어떤 요청으로 오는지 잘 모르겠어서 가능성 있는 거 다 넣어버렸어요 ㅋㅋㅋㅋㅋ 다시 수정했습니다 ~!!

2021-09-11 15:03 UTC, yjksw commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +            .filter(method -> method.getDeclaredAnnotation(RequestMapping.class) != null)
대박 이런게 있다니 !!

2021-09-11 16:31 UTC, yjksw commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
> +            clazz.getConstructor().newInstance(),
그러네요!! 지금 구조로 보았을 때는 handle을 할때마다 인스턴스를 계속 생성해주고 있는 엄청난 문제가 있었네요 ㅠㅠㅠㅠ 

어디서 인스턴스를 만드는 것이 좋을까 checked Exception이 리플렉션으로 인스턴스 생성시에 자꾸 따라와서 생성 위치가 고민이 하다가 Component를 찾아서 주입해주는 `ComponentScanner`를 구현했습니다 !!

2021-09-11 16:36 UTC, yjksw commented on learning/src/test/java/reflection/Junit3TestRunner.java
>  class Junit3TestRunner {
왕 이거 짱이다 !!!

2021-09-11 16:59 UTC, yjksw commented
안녕하세요 에어~~!! 
왜인지 피드백 반영이 늦었습니다 ..ㅠㅠ 시간이 왜이렇게 금방금방 가는지 ㅠㅠ

기대했던 대로 좋은 피드백 해주셔서 넘 좋았어요 !! 😊
덕분에 `AnnotationHandlerMapping` 부분이 훨씬 깔끔해지고 새로운 테스트 기법도 알게 되었습니다 ㅎㅎ 

이번에 피드백 해주신대로, 핸들러를 class가 아닌 인스턴스로 한번만 생성해서 주입해주는 형식으로 리팩토링을 하려고 하다보니, Component scan을 해주는 클래스가 필수적으로 필요하다는것을 느낄 수 있었어요!! 

그래서 에어가 구현한 엄청난 `ApplicationContext` 만큼은 아니지만, basePackage와 어노테이션을 인자로 넘겨주면 해당 클래스 object를 스캔 및 생성해서 반환해주는 `ComponentScanner`라는 클래스를 구현했습니다. 
 
현재는 utility 처럼 static으로 구현되어 있는데요,, bean 처럼 싱글톤 생명주기를 가지게 하려면 이렇게하기보다 빈 등록을 한번에 시켜놓은 다음 재활용해서 반환하는게 맞다고 생각해요!! (스프링도 그렇게 하고 있는 걸까요?) 

현재는 static하게 구현하여 사용하도록 되어 있습니다 !!
보고 어색하거나 오류가 생길법한 지점이 있다면 피드백 해주세요 ~!! 

감사합니다 :)

2021-09-12 08:31 UTC, KJunseo approved these changes
안녕하세요 코다! 그쵸 시간이 정말 빨리가는 것 같아요.. 뭐 많이하지도 못했는데..
피드백 반영 잘해주셨네요ㅎㅎ 👍🏻👍🏻👍🏻 
물론 원래도 잘해주셨지만 AnnotationHandlerMapping 부분이 많이 깔끔해진 것 같아요! 
이번 단계는 이만 머지하겠습니당!

추가로 질문 주신 부분에 답을 드리자면 저도 아직 확실하게는 잘 모르지만 제가 알고있는 선에서 조금 말씀드릴게요.
스프링은 처음에 바로 빈 인스턴스를 생성하지는 않고, 빈에 대한 메타데이터를 정의하는 BeanDefinition을 생성해서 내부 Map에 저장해요. 이렇게 하는 이유가 빈의 스코프 때문인데요. 싱글톤인 경우는 빈 인스턴스를 하나만 생성해도 되지만, 프로토타입인 경우는 매번 인스턴스를 새로 생성해야 하기 때문이에요. 그래서 BeanDefinition을 저장해두고, 실제로 빈을 사용할 때 BeanDefinition을 통해 빈 인스턴스를 생성하고 스코프가 싱글톤이면 Map에 저장해두고 다음 요청시 꺼내쓰고, 프로토 타입인 경우는 항상 새로 만들어서 반환해서 쓰는 것 같더라구요. 
그래서 스프링에서는 아마 코다가 만드신 ComponentScanner를 싱글톤으로 사용할 경우 제일 처음 호출할 때 생성될 것 같네요! 그 후에 또 쓰인다면 Map에서 꺼내서 반환해 줄 것 같습니다!(저도 아직 다 까보질 못해서 아닐수도 있어요..)

2021-09-12 08:31 UTC, KJunseo commented on mvc/src/main/java/nextstep/mvc/ComponentScanner.java
> +public class ComponentScanner {
static하게 쓰지 않으려면 `AnnotationHandlerMapping`에 주입해주는 식으로 사용할 수도 있을 것 같네요!

```java
public class AnnotationHandlerMapping implements HandlerMapping {

    private final Object[] basePackage;
    private final Map<HandlerKey, HandlerExecution> handlerExecutions;
    private final ComponentScanner componentScanner;

    public AnnotationHandlerMapping(Object... basePackage) {
        this.basePackage = basePackage;
        this.handlerExecutions = new HashMap<>();
        this.componentScanner = new ComponentScanner(basePackage);
    }
```
```java
public class ComponentScanner {
    Reflections reflections = new Reflections(basePackage);

    public ComponentScanner(Object... basePackage) {
        reflections = new Reflections(basePackage);
    }
}
```
아니면 아에 DispatcherServlet 생성시, ComponentScanner도 생성해서 주입해줘도 될 것 같네요

2021-09-12 08:31 UTC, KJunseo commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +    private List<Method> getRequestMappingMethods(Map<String, Object> controllers) {
오.. 많이 깔끔해졌네요!! 👍🏻👍🏻👍🏻

2021-09-12 08:32 UTC, merged