[MVC 구현하기 - 3단계] 판다(김건웅) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #307
Opened 2022-09-27 04:28 UTC by woong7

안녕하세요 후니! 
MVC 3단계 미션 구현해서 제출합니다. 

- [x] 힌트에서 제공한 UserController 컨트롤러가 json 형태로 응답을 반환한다.
- [x] 레거시 코드를 삭제하고 서버를 띄워도 정상 동작한다.

늘 감사합니다!

2022-09-27 11:49 UTC, jayjaehunchoi requested changes
판다 안녕하세요.

몇가지 리뷰를 남겼습니다! 고민해보시고 한 번 생각하신대로 수정해주세요
만약 딱히 동의하지 않는다면 댓글로 남겨주시고 리뷰 요청 주셔도 됩니다~

2022-09-29 01:00 UTC, woong7 commented on app/src/main/java/com/techcourse/ManualHandlerMapping.java
> +        //controllers.put("/", new ForwardController("/index.jsp"));
넵!

2022-09-29 02:17 UTC, woong7 commented on app/src/main/java/com/techcourse/controller/UserController.java
> +    @RequestMapping(value = "/api/user", method = RequestMethod.GET)
로그인된 경우 우측 드롭다운의 `내 정보` 버튼을 통해 사용자 정보를 호출할 수 있도록, `index.jsp` 파일을 수정했습니다!

2022-09-29 02:45 UTC, woong7 commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +            return new ModelAndView(new JspView("redirect:/index.jsp"));
ModelAndView에서 결정하도록 변경하였는데요, 의도하신 바가 맞는지 애매한 것 같습니다.

2022-09-29 04:28 UTC, jayjaehunchoi approved these changes
안녕하세요 판다!

반영해주신 내용 확인했습니다.
수고하셨어요~~

2022-09-29 04:29 UTC, jayjaehunchoi commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +            return new ModelAndView(new JspView("redirect:/index.jsp"));
생성자 내부에서 JspView만 사용하게끔 만들어져있네요.

단점이 있을 것 같아요. 저는 처리해야하는 확장자명에 따라 view를 렌더링하게 만들어줄 것 같아요.
개인적으로 한 번 해보셔도 좋겠네요 ㅎㅎ

2022-09-29 04:29 UTC, merged