[MVC 구현하기 - 3단계] 아스피(신동석) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #314
Opened 2022-09-27 05:18 UTC by shindong96

안녕하세요 마루! 아스핍니다 :)
마루의 피드백 덕에 코드가 더 깔끔해졌어요!
이번에도 잘 부탁드리겠습니당ㅎㅎ
피드백 기다릴게요!

2022-09-28 01:23 UTC, chawani requested changes
안녕하세요 아스피~~ 마루입니당!
코드를 잘 짜주셔서 리뷰하는 데에 어려움이 없었네요😎👍
몇가지 코멘트 달아드렸어요! 확인해주세요😃

2022-09-28 01:23 UTC, chawani commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        }
jsonValue를 얻는 동작을 따로 메서드로 빼면 한결 깔끔해 질 것 같네요!👍

2022-09-28 01:23 UTC, chawani commented on mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java
> +class JsonViewTest {
테스트 굿👍👍

2022-09-29 08:32 UTC, shindong96 commented on app/src/main/java/com/techcourse/controller/RegisterController.java
>                  req.getParameter("email"));
헉 그러네요!!

2022-09-29 08:38 UTC, shindong96 commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        }
반영했습니다!!

2022-09-29 08:55 UTC, shindong96 commented on app/src/main/java/com/techcourse/controller/ForwardController.java
> +    }
반영했습니다!!!

2022-09-29 08:56 UTC, shindong96 commented
안뇽하세요 마루!! 아스핍니다 :)
덕분에 코드가 좀 더 멋있어졌어요!! 감사합니다 👍 
추가 피드백이 있다면 기다리겠습니다!!

2022-09-29 09:59 UTC, chawani commented on app/src/main/java/com/techcourse/controller/RegisterController.java
>                  req.getParameter("email"));
InMemoryUserRepository로부터 user수를 가져오고 id를 증가시켜주는 방법을 써봐도 좋을 것같아요! 고생하셨습니당

2022-09-29 10:02 UTC, chawani approved these changes
아스피 고생 많으셨습니다~👍 코멘트 추가로 하나 남겼는데 확인만 해주세요! 머지하겠습니다😁

2022-09-29 10:03 UTC, merged