[MVC 구현하기 - 2, 3단계] 필즈(조성우) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #316
Opened 2022-09-27 05:44 UTC by progress0407

리차드 ~!! 안녕하세요 필즈에요!

저번에 양질의 코드 리뷰를 받아서 정말 영광이었어요 :) 

덕분에 여러 생각을 정리하면서 오랜만에 클린 코드에 대해 탐구해볼 수 있었어요!

미션 이외에 해본 챌린지는 아래의 것들이에요 !!

1. 기존과 같은 DI를 할 수 있어야 하고. (스프링 컨테이너)(여기서는 `PeanutBox` 라고 명명했어요)
2. `Controller -> Service -> Repository` 와 같은 여러 의존관계를 가지는 DI를 할 수 있어야 한다.
3. `ObjectMapper`와 같이 매번 생성하는 것이 무거운 객체의 경우 `@Bean` 처럼 명시적 수동 등록을 할 수 있는 기능을 추가한다.

2022-09-27 06:01 UTC, progress0407 commented on mvc/src/main/java/nextstep/context/PeanutBox.java
> +
DI를 해주는 PeanutBox를 추가했어요 :)
이 역할은 스프링 DI Container의 구조를 모방해서 만들었습니다.

2022-09-27 08:44 UTC, HJ-Rich requested changes
필즈 안녕하세요~!

필즈 코드 보면서 많이 배웠습니다 ㅎㅎ
특히 JsonView로 쓰여진 OutputStream을 테스트하는 부분은 정말 크게 배웠어요! 👏

필즈가 더 멋진 코드로 만들어가실 수 있을 것 같아서
열심히 피드백 남겨봤습니다! 

이번에도 필수로 반영해주셔야 하는 내용은 없습니다.
다만 필즈의 구현 의도와 의견을 공유해주시고, 선택적으로 반영해주시면 좋을 것 같습니다.

마지막 3단계 화이팅! 🎶

2022-09-27 08:44 UTC, HJ-Rich commented on README.md
> +  - 하지만 필자는 제거하지 않으려 한다...
1. 필자 라는 표현에 대해서 조금 알아보면 어떨까요? 😃
2. 왜 제거하지 않으려 하는지도 작성해주시면 좋을 것 같아요.
3. README 는 다른 사람들에게 읽히기 위한 문서이기에 `...` 과 같은 표현 보다는 보다 격식있는 표현을 사용하면 어떨까 하는 개인적인 생각입니다!

http://world.kbs.co.kr/service/contents_view.htm?lang=k&menu_cate=learnkorean&id=&board_seq=229333&page=224&board_code=net_lang

2022-09-27 08:44 UTC, HJ-Rich commented on README.md
> +- [x] `PeanutBox` (**땅콩박스**)에서 `@Controller`가 붙은 클래스를 찾을 수 있다.
이렇게 작성되면 미션의 요구사항으로 오인될 소지가 있을 것 같은데 필즈 생각은 어떠세요?!

2022-09-27 08:44 UTC, HJ-Rich commented on app/src/main/java/com/techcourse/ManualHandlerMapper.java
> +        controllers.put("/old/register", new RegisterOldController(userRepository));
`app 모듈에 있는 모든 컨트롤러를 어노테이션 기반 MVC로 변경한다.`

요구사항에선 애너테이션 기반으로 리팩터링하길 요구하고 있는데요,
혹시 어떤 이유에서 기존 방식을 유지했는지 알 수 있을까요?~!

머지 조건에 해당하는 체크리스트에는 아래와 같은 내용이 있어요! 👀

- [ ] 레거시 코드를 삭제하고 서버를 띄워도 정상 동작한다.

2022-09-27 08:44 UTC, HJ-Rich commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +    }
getWriter()는 PrintWriter를 반환하는군요~!
PrintWriter는 추상클래스 Writer를 상속했고, Writer는 AutoClosable을 구현했습니다~!
그리고 PrintWriter는 close 메서드를 재정의했구요! 내부에선 스트림을 닫아주고 있습니다.

try-with-resources를 이용해 스트림 사용 완료 후 닫아주는 건 어떨까요?

2022-09-27 08:44 UTC, HJ-Rich commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +    }
<img width="607" alt="image" src="https://user-images.githubusercontent.com/62681566/192474641-156bb4e8-b9f5-4971-b16b-4773d2b676c3.png">

- `model에 데이터가 1개면 값을 그대로 반환하고 2개 이상이면 Map 형태 그대로 JSON으로 변환해서 반환한다.`

이 부분은 제가 요구사항을 정확히 이해하지 못해서 여쭤보는 건데요!
요구사항 내용만 봐서는 필즈 구현이 맞는 것 같으면서도,
View의 이름이 JsonView인 걸 생각해보면 또 Json형태가 아닌 반환을 하는 게 맞나 하는 생각도 들어요 ㅋㅋ

저는 1개일 경우 depth 1로 value만 Json으로 내보내도록 구현했는데요,
필즈 생각은 어떠세요?~!

2022-09-27 08:44 UTC, HJ-Rich commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +                .forEach(key -> log.debug("attribute name : {}, value : {}", key, model.get(key)));
먼저 호출되는 logModelEntry 메서드를 상위로 올리면 어떨까요?! 😃

2022-09-27 08:44 UTC, HJ-Rich commented on mvc/src/main/java/nextstep/context/PeanutBox.java
> +
PeanutBox와 PeanutContainer의 역할에 대해 조금 더 설명해주실 수 있을까요?~!

2022-09-27 08:44 UTC, HJ-Rich commented on mvc/src/main/java/nextstep/context/PeanutBox.java
> +    }
getPeanut 메서드를 상위로 끌어올리면 어떨까요?

이 객체의 가장 중요한 책임을 드러내는 메서드인 것 같아서요~! 😃

2022-09-27 08:44 UTC, HJ-Rich commented on mvc/src/main/java/nextstep/context/PeanutBox.java
> +    }
오늘 실습에서 다뤄졌던 내용을 벌써 적용하셨군요!!
대단대단합니다... 하지만 유지보수하기에는 다소 어렵게 느껴지는 것 같아요.. 😅

혹시 dfs 메서드를 재구조화해볼 수 있을까요?
getBean과 createBean 두 메서드로 나눠서 구현해보는 방식은 어떠세요?
컨트롤러, 서비스, 리포지토리로 이어지는 연쇄작업을 적어봤는데요,
getBean, createBean 두 가지 메서드로 구현하면 보다 가볍게 구현할 수도 있을 것 같아요~!

```java
- getBean(컨트롤러) → 컨테이너에 없음 → createBean(컨트롤러)
    - createBean(컨트롤러) → 생성자 매개변수 가져오기 위해 getBean(서비스)
        - getBean(서비스) → 컨테이너에 없음 → createBean(서비스)
            - createBean(서비스) → 생성자 매개변수 가져오기 위해 getBean(리포지토리)
                - getBean(리포지토리) → 컨테이너에 없음 → createBean(리포지토리)
                    - createBean(리포지토리) → 리포지토리 생성, 컨테이너에 담고, 반환
                - createBean(리포지토리) 반환값 받아서 getBean(리포지토리) 반환
            - getBean(리포지토리)  반환 받아서 createBean(서비스) 반환
        - createBean(서비스) 반환 받아서 getBean(서비스) 반환
    - getBean(서비스) 반환 받아서 createBean(컨트롤러) 반환
- createBean(컨트롤러) 반환 받아서 getBean(컨트롤러 반환)
```

2022-09-27 08:44 UTC, HJ-Rich commented on mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java
> +    void render() throws Exception {
DisplayName에 `model의 사이즈가 2 이상일 경우,` 라는 전제 조건을 함께 명시해주면 어떨까요?

2022-09-27 08:44 UTC, HJ-Rich commented on mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java
> +    void renderOneValue() throws Exception {
model의 사이즈가 1일 경우에도 객체를 통해 테스트해보면 어떨까요?

2022-09-27 08:44 UTC, HJ-Rich commented on mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java
> +    }
와우.. 이 부분을 어떻게 테스트할지 고민하다가 저는 결국 구현하지 못했거든요.
이런 방법이 있군요.. 배워갑니다!! 👍

2022-09-27 08:44 UTC, HJ-Rich commented on mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java
> +}
<img width="189" alt="image" src="https://user-images.githubusercontent.com/62681566/192477351-78db5627-43e8-4175-be22-d7122ba7e347.png">

😅

2022-09-27 08:45 UTC, HJ-Rich commented
![image](https://user-images.githubusercontent.com/62681566/192478582-f6d1dd79-44f6-446b-a494-1b6fb7559e1f.png)

테스트 케이스가 하나 깨지고 있어요~ ㅠ.ㅠㅠ
이부분도 확인 부탁드릴게요!

2022-09-27 14:28 UTC, progress0407 commented on mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java
> +    }
오.. 아뇨 ㅠㅠ 먼저 다른 크루분의 코드를 보고 참고하여 작성한 부분이에요 :)

2022-09-29 02:07 UTC, progress0407 commented on mvc/src/main/java/nextstep/context/PeanutBox.java
> +
- asis: `PeanutContainer` 에서  tobe `PeanutBox` 로 변경되었어요!
- 코드를 병합하는 과정에서 이전 파일이 남았던 것 같네요, 제거할게요 !

2022-09-29 02:40 UTC, progress0407 commented on README.md
> +  - 하지만 필자는 제거하지 않으려 한다...
### 필자

헉... `필자`란 표현이 제 3자가 쓰는 표현이었군요!!
평상시 많이 사용하던 말인데 사용하지 않는게 좋겠네요 :)
README가 다른 사람들과 같이 읽는 문서라는 것을 잊고 작성했던 것 같아요!
`본인, 나` 라는 표현도 자제했습니다 :)

대략 아래와 같이 수정했어요 !

![image](https://user-images.githubusercontent.com/66164361/192925626-bbb5f6fa-54b0-4840-828f-9d6effec2564.png)

2022-09-29 02:41 UTC, progress0407 commented on README.md
> +- [x] `PeanutBox` (**땅콩박스**)에서 `@Controller`가 붙은 클래스를 찾을 수 있다.
![image](https://user-images.githubusercontent.com/66164361/192926428-1d689005-785d-4d4f-a827-01bbcdc988f2.png)

위와와 같이 변경을 해보았어요 !

2022-09-29 08:29 UTC, progress0407 commented on app/src/main/java/com/techcourse/ManualHandlerMapper.java
> +        controllers.put("/old/register", new RegisterOldController(userRepository));
- [ ] 레거시 코드를 삭제하고 서버를 띄워도 정상 동작한다

미션 요구사항으로 인지를 하고 있었으나 
실제 프로덕션에서 기존의 매핑, 어댑터를 통해 작성된 핸들러가 정상 동작하는 것을 확인하고자 남겨 두었어요 !

2022-09-29 08:37 UTC, progress0407 commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +    }
네 ! 리차드 말이 맞아요!

map의 key-value 쌍이 2개 이상일 떄 

```js
var response  = {
  "key-1" : "value-1",
  "key-2": "value-2"
}
```

1개일 때 

```js
var response = {
  "value-1"
}
```

위와 같은 구조로 나타내고자 했어요 !

2022-09-29 08:38 UTC, progress0407 commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +                .forEach(key -> log.debug("attribute name : {}, value : {}", key, model.get(key)));
좋습니다 !! :)

2022-09-29 08:41 UTC, progress0407 commented on mvc/src/main/java/nextstep/context/PeanutBox.java
> +    }
아....... 이게 상황에 따라 다중 분기문으로 처리하는 것에 대한 로직이 맞는 건가요??
굉장히 정성스레 적어주셔서 여러 번 읽어 보았습니다만... 이 경우에 대해서는 DFS로 경우를 처리하는 것이 맞는 것 같아요 !

2022-09-29 08:42 UTC, progress0407 commented on mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java
> +    void render() throws Exception {
아하 ! 좋습니다 :)

2022-09-29 08:45 UTC, progress0407 commented on mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java
> +    void renderOneValue() throws Exception {
`DummyPrintWriter` 객체를 말하는 것이라면 그러고 있습니다 :)

2022-09-29 08:46 UTC, progress0407 commented on mvc/src/main/java/nextstep/context/PeanutBox.java
> +    }
맞습니다 ! 모든 `public` 메서드를 최상위로 끌어 올렸어요 !

2022-09-29 08:46 UTC, progress0407 commented on mvc/src/main/java/nextstep/context/PeanutBox.java
> +    }
정확히 현재는 두 dfs 메서드를 통해서 상호작용하는 방식으로 구현되어 있어요 ! ...

2022-09-29 08:57 UTC, progress0407 commented
리차드 ~! 반가워요! 
모든 리뷰는 아니지만 몇 가지 반영하여 Pull Request 드려요! :)

2022-09-29 09:21 UTC, progress0407 commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +    }
으음... 제가 이해를 못한 걸까요? ㅠㅠ

아래와 같이 `try-with-resources` 자원 반납 블록을 지정해보았지만

![image](https://user-images.githubusercontent.com/66164361/192993381-3ff030c0-2f96-4e49-95c0-0a1fac3917e8.png)

디버거를 타서 자원 해제를 해주는 모습을 발견할 수는 없었어요...

![image](https://user-images.githubusercontent.com/66164361/192993461-8d08e3b0-b231-4ee1-8d1b-ec8b6505d929.png)

2022-09-29 09:21 UTC, HJ-Rich commented
<img width="705" alt="image" src="https://user-images.githubusercontent.com/62681566/192993711-f45d9adc-8218-43d7-832f-b0797ef9b0b0.png">
테스트가 여전히 깨지고 있네요... ;ㅅ;

2022-09-29 09:25 UTC, HJ-Rich commented
<img width="728" alt="image" src="https://user-images.githubusercontent.com/62681566/192994501-ac3a679f-6cf2-4432-adf3-cbd9bbeb9bfa.png">

모델 사이즈가1일때 json 형태로 내보내지지 않고 있어요 ;ㅅ;

2022-09-29 09:32 UTC, HJ-Rich commented
<img width="525" alt="image" src="https://user-images.githubusercontent.com/62681566/192994934-f27c5c53-f683-492e-95bb-99bca22aa870.png">
<img width="320" alt="image" src="https://user-images.githubusercontent.com/62681566/192995059-d951b4ef-aa83-451f-b055-f8bc01b8a939.png">
<img width="646" alt="image" src="https://user-images.githubusercontent.com/62681566/192995630-f1208a48-c025-4eb8-846f-fb3e845860c5.png">
<img width="801" alt="image" src="https://user-images.githubusercontent.com/62681566/192995944-6bb243c5-4f14-4c99-bbca-a672854381c3.png">

<br><br>

레거시 코드를 삭제 하고 나서도 정상 동작하는 것이 머지 조건인데요,
이를 확인하기 위해 필즈 코드에서 제가 레거시 코드에 해당하는 클래스들을 삭제하고 기동해서 테스트 진행했어요.

확인 결과 첫번째 요구사항인 json응답에 대해서 모델 사이즈가 1일 경우 정상응답되지 않고 있네요.
[이전 피드백](https://github.com/woowacourse/jwp-dashboard-mvc/pull/316#discussion_r980928286)에서도 남겨드렸던 내용인데 혹시 이 부분 확인해보셨나요?

2022-09-29 09:33 UTC, HJ-Rich commented
필즈 고생 많으셨습니다~!

다음 미션도 화이팅하세요!

2022-09-29 09:33 UTC, merged