[MVC 구현하기 - 3단계] 알파(배철환) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #332
Opened 2022-09-27 08:32 UTC by bcc0830

안녕하세요 소주캉!
이번 미션은 2, 3단계를 같이 구현하였습니다
부족하지만 잘부탁드립니다

2022-09-27 12:21 UTC, sojukang requested changes
안녕하세요 알파👋👋 MVC 미션 3단계 리뷰드리는 소주캉입니다. 
깔끔하게 코드 짜주셔서 파악하기 굉장히 쉬웠습니다👍.

그런데 아직 테스트 코드가 하나도 없네요 😥. 중요한 로직 위주라도 작성해주시면 좋을 것 같습니다!

약간의 피드백 남겼습니다.

2022-09-27 12:21 UTC, sojukang commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            throw new IllegalArgumentException();
단순히 IllegalArgumentException만 반환하면 오히려 기본 NotFoundExecption보다 디버깅하기 힘들어질 것 같습니다!

2022-09-27 12:21 UTC, sojukang commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        Optional<Object> handler = handlerMappingRegistry.getHandler(request);
현재 로직대로면 Optional을 바로 받는 것보다 `.orElseThrow`를 사용하는 건 어떨까요?

2022-09-27 12:21 UTC, sojukang commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        ControllerScanner controllerScanner = new ControllerScanner(new Reflections(basePackage));
Reflections를 외부에서 넣어주는 게 아니라 객체 내부에서 생성하게 하면 어떨까요?

2022-09-27 12:21 UTC, sojukang commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        modelAndView.getView().render(modelAndView.getModel(), request, response);
modelAndView에서 getView를 호출하지 않고 ModelAndView에 처리하도록 하면 어떨까요?

2022-09-28 05:14 UTC, bcc0830 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            throw new IllegalArgumentException();
에러 메세지 추가했습니다

2022-09-28 05:16 UTC, bcc0830 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        Optional<Object> handler = handlerMappingRegistry.getHandler(request);
수정하였습니다

2022-09-28 05:19 UTC, bcc0830 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +        ControllerScanner controllerScanner = new ControllerScanner(new Reflections(basePackage));
수정하였습니다

2022-09-28 05:27 UTC, bcc0830 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +        modelAndView.getView().render(modelAndView.getModel(), request, response);
수정하였습니다

2022-09-29 08:44 UTC, sojukang commented
안녕하세요 알파👋👋 MVC 미션 3단계 리뷰 드리는 소주캉입니다. 
팀 프로젝트 바쁘신 와중에도 MVC 미션 잘 수행하시느라 고생 많이 하셨습니다👍👍👍
깔끔하게 코드 짜주셔서 쉽게 이해할 수 있었습니다. 
미션 고생하셨습니다!!!

2022-09-29 08:44 UTC, merged