[MVC 구현하기 1단계] 하디(전동혁) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #352
Opened 2023-09-13 04:01 UTC by jundonghyuk

안녕하세요 폴로 하디입니다.

구현하는데 고민이 많았습니다. 

1. ReflectionUtils는 사용하려 했으나 제가 봤을 때 뭔가 .. 더 가독성이 떨어져 보여서 사용하지 않았습니다.

2. ControllerScanner를 통해 어노테이션 클래스 끌어오기

3. 기본 생성자가 존재하고 필드가 없는 `@Controller` 어노테이션이 붙은 클래스만 생성가능
 - 인자가 있으면 어떤 값으로 초기화해야할지 몰라서 일단은 이렇게 구현했습니다 !
감사합니다

2023-09-14 01:50 UTC, green-kong requested changes
안녕하세요 하디!
평소에 하디의 코드를 볼일이 없었어서 몰랐는데,
굉장히 세심하게 코드를 작성하시네요!!
제가 생각하지 못한 부분들이 하디의 코드에선 처리되고 있는 것을 보고 많이 반성하고 배울 수 있었습니다!

약간의 코멘트 남겨두었는데요.
하디의 의견이 궁금해서 Request Changes로 해둘게요!
의견만 남겨주시고, 반영은 2단계 때 하셔도 무방합니다~
수고많으셨어요!

2023-09-14 01:50 UTC, green-kong commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +            String url = requestMapping.value();
method.getAnnotation()의 내부를 확인해보시면,
```java
public <T extends Annotation> T getAnnotation(Class<T> annotationClass) {
        Objects.requireNonNull(annotationClass);
        return annotationClass.cast(declaredAnnotations().get(annotationClass));
    }
```
요런 식으로 구현되어있어요.
declaredAnnotation()의 반환값이 Map자료구조 인데요.
Map에서 get을 해오는 방식이라, null이 반환 될수도 있을것 같네요!
method가 특정 어노테이션을 포함하고 있는지 체크할 수 있는 메서드가 있는데(isAnnotationPresent()) 이걸 한번 사용해보시면 어떨까요?
근데 사실 isAnnotationPresent()가 내부적으로 getAnnotation을 사용하고 있어서, null체크만 해주어도 될것같긴 하네요~

2023-09-14 01:50 UTC, green-kong commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
>      }
@RequestMapping 의 value와 method의 default가 각각 ""(빈스트링) 빈배열이라 이런 검증을 추가 해주신 것 같아요!
개인적인 의견인데, value가 빈스트링이거나, method가 빈배열이라면 예외가 발생해야 되는것 아닐까요?
흠. 얘네개 왜 default를 이렇게 설정했는지 궁금해지네요..

그건 그렇고 이런부분까지 세심하게 검증을 하시는게 놀랍네요! 전 안했거든요ㅋㅋ👍

2023-09-14 01:50 UTC, green-kong commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +                log.info("uri = {}, method = {}, name = {} is mapped!", url, requestMethod.name(), method.getName());
세심한 로그👍

2023-09-14 01:50 UTC, green-kong commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/ControllerScanner.java
> +public class ControllerScanner {
getControllers() 를 통해서 @Controller 어노테이션이 붙은 클래스를 가져오는 역할을 하네요!
이번 미션에서는 컨트롤러만 스캔을 하지만, 원래라면 다른 어노테이션에 대해서도 스캔이 필요할 것 같아요(@Service, @Repository, 등등..)
모든 어노테이션 마다 Scanner클래스를 만들기는 힘들 것 같으니,
이 클래스를 어노테이션.class를 인자로 받아 인자로 받은 어노테이션이 붙은 클래스들을 스캔할 수 있는 클래스로 변경해보면 범용적으로 쓸 수 있는 클래스가 될것 같은데,
어떻게 생각하시나요??

2023-09-14 12:03 UTC, jundonghyuk commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
감사합니다. 가변인자를 받고 있었네요 ..!

열어보지 않아서 몰랐습니다. 수정 하겠습니다 !

2023-09-14 12:15 UTC, jundonghyuk commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/ControllerScanner.java
> +    }
폴로 스트림 활용을 정말 잘하시네요 ㅎㅎ 많이 배웁니다 !

인스턴스만 생성해주는 `generateInstance`만 따로 빼놔서 오히려 가독성이 더 좋아지는것 같아요 반영하게습니다 ㅎㅎ

2023-09-14 12:25 UTC, jundonghyuk commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +            String url = requestMapping.value();
```
    private List<Method> getRequestMappingMethods(Class<?> handler) {
        return Arrays.stream(handler.getMethods())
                .filter(method -> method.isAnnotationPresent(RequestMapping.class))
                .collect(Collectors.toList());
    }
```

현재 `AnnotationHandlerMapping.java`의  58 ~ 62번 라인입니다 !

메서드 리스트를 가져올 때 `RequestMapping`이 달려있는 것만 가져오고 있는데요 !

혹시 이 로직을 말씀하신걸까요 ?

2023-09-14 12:38 UTC, jundonghyuk commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
>      }
공감합니다 ..ㅋㅋㅋㅋ 사실 어노테이션을 열어보고 디폴트 값이 설정되어 있길래 그거로 잡았습니다 ㅎㅅㅎ

2023-09-14 12:56 UTC, jundonghyuk commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/ControllerScanner.java
> +public class ControllerScanner {
너무 좋습니다 ! 특정 어노테이션이 달린 클래스나 인터페이스만 가져와보도록 수정해보겠습니다 ~!

👍

2023-09-15 05:15 UTC, green-kong commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +            String url = requestMapping.value();
앗 제가 이부분을 놓쳤네요 죄송합니다죄송합니다죄송합니다

2023-09-15 05:18 UTC, green-kong approved these changes
부족한 리뷰였을텐데 꼼꼼히 반영해주셔서 감사합니다!
Scanner가 범용적으로 사용될 수 있을 것 같아서 아주 탐나네요.
제 커밋으로 훔쳐가도록 하겠습니다 ㅋㅋ
1단계는 merge 하겠습니다!
2단계에서 만나용~

2023-09-15 05:21 UTC, merged