[MVC 구현하기 - 1단계] 성하(김성훈) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #379
Opened 2023-09-13 10:48 UTC by sh111-coder

안녕하세요 글렌!! 😃 성하입니다!

이번 미션에서 리플렉션을 처음 사용해봐서 조금 헤맸네요 ㅠㅠ

리뷰 잘 부탁드립니다!! ㅎ_ㅎ 🙇🏻‍♂️

2023-09-13 11:29 UTC, seokjin8678 requested changes
안녕하세요 성하 🏰👋
이번 1단계 코드는 그렇게 많지 않아 빠르게 리뷰가 가능했습니다!

이번 단계에서는 `AnnotationHandlerMapping` 클래스를 조금 더 리팩터링하면 될 것 같아요!
파이팅!!

2023-09-13 11:29 UTC, seokjin8678 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/exception/NotFoundHandlerException.java
> +public class NotFoundHandlerException extends RuntimeException {
사소한 부분이긴 한데.. `HandlerNotFoundException`은 어떨까요?
참고로 실제 스프링 코드에서는 `NoHandlerFoundException` 네이밍을 사용하고 있어요!

2023-09-13 11:29 UTC, seokjin8678 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
>      }
메서드의 파라미터 수가 많은 것 같아요!
메소드를 조금 더 분리할 수 있을것 같은데.. 해주실 수 있을까요? 😉

2023-09-13 11:29 UTC, seokjin8678 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    }
코드의 흐름을 살펴보니, `Reflections.getTypesAnnotatedWith()` 메서드로 `@Controller` 어노테이션이 붙은 클래스를 불러온 뒤,
`getRequestMappingMethods()` 메서드로 `@RequestMapping` 어노테이션이 붙은 메소드를 모두 불러오고, 다시 `Method.getDeclaringClass()` 메서드를 통해 메서드가 속한 클래스를 다시 가져오고 있네요!
나쁜 방법은 아니지만, 기존에 꺼내온 `Class`가 있지만 다시 `Class`를 가져오는 방법은 효율적이지 않은 것 같아요..
더 효율적인 방법이 있을 것 같은데...
밑의 `putHandlerExecutions()` 메서드의 파리미터 수를 줄여보며 같이 리팩터링 해보는 것은 어떨까요?

2023-09-13 11:29 UTC, seokjin8678 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    private final Object[] basePackages;
👍

2023-09-13 11:37 UTC, sh111-coder commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/exception/NotFoundHandlerException.java
> +public class NotFoundHandlerException extends RuntimeException {
저는 NotFoundXxx가 익숙해서 이렇게 작성했는데,
HandlerNotFoundException도 좋은 것 같아요! 
수정했습니다!! 👍🏻
실제 스프링 코드 네이밍도 알려주셔서 감사합니다 ㅎㅎ 😃

2023-09-13 11:44 UTC, sh111-coder commented on mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMethod.java
> +    }
앗! `valueOf()` 메소드를 사용해본 적이 없었어서 몰랐었네요 ㅠㅠ 😃
덕분에 하나 또 알아갑니다 ㅎㅎㅎㅎ

기존 구현 시에는 methodName에 해당하는 ReqeustMethod가 없다면,
실제 스프링에서도 NotAllowedMethodException이 발생하기 때문에
NotAllowedMethodException을 발생시키고 싶었어요!

`valueOf()`로 리팩토링한 후에 테스트를 돌려보니,
 methodName에 해당하는 ReqeustMethod가 없으면 IllegalArgumentException이 발생하네요!
try-catch로 NotAllowedMethodException를 발생시키기 보다는,
현재 코드가 더 익숙하고 가독성이 좋다고 생각되어서 놔두도록 하겠습니다!!!

메소드 제안까지.. 역시 갓글렌 감사합니다!! 🙇🏻‍♂️

2023-09-13 11:48 UTC, seokjin8678 commented on mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMethod.java
> +    }
참고로 `NotAllowedMethodException`을 반환해서 405 상태코드를 반환하실 생각이시면, 다음과 같이 Response 헤더에 `Allow` 헤더를 명시해줘야 하니 참고해주세요~!
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

2023-09-13 12:21 UTC, sh111-coder commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    }
역시 글렌! 꼼꼼하시네요!!! 👍🏻

기존 : Controllers 가져오기 -> Controllers의 모든 RequestMapping 메소드 불러오기 -> 불러온 Method의 클래스 가져오기 -> Map에 put
리팩토링 후 : Controllers 가져오기 -> Controller별 반복 : (RequestMapping 메소드 불러오기 -> Map에 put)

한 과정 줄고 효율적으로 되었습니다!! 감사합니다!! 🙇🏻‍♂️

2023-09-13 12:30 UTC, seokjin8678 requested changes
안녕하세요 성하 🏰👋
빠르게 답변을 주셨네요 😁
저도 빠르게 리뷰 남겨드리겠습니다..!
정말 사소한 한 가지 부분만 검토해주세요!!

2023-09-13 12:30 UTC, seokjin8678 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    }
`new HandlerExecution()`으로 새로운 인스턴스를 생성할 때 파라미터로 들어가는 첫 번째 인자는 `@Controller` 어노테이션이 붙은 클래스의 인스턴스겠네요!
해당 인스턴스는 클래스 당 한 번만 생성되면 될 것 같아요!
힌트를 드리자면.. `putHandlerExecutionsForMethod()` 메소드의 파라미터 타입만 바꾸면 될 것 같아요...!

2023-09-14 00:05 UTC, sh111-coder commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    }
수정했습니다!! 꼼꼼한 리뷰 감사합니다 글렌 !!! 🌈🌈

2023-09-14 00:45 UTC, seokjin8678 approved these changes
안녕하세요 성하 🏰👋
작은 코드임에도 많은 요청을 드려 귀찮으셨을텐데, 적절하게 반영해주셔서 좋았습니다. 👍👍👍
이제 2단계 출발하시죠~~

2023-09-14 00:45 UTC, merged