[MVC 구현하기 - 2단계] 제이(이재윤) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #442
Opened 2023-09-15 07:53 UTC by sosow0212

안녕하세요 우르~

2단계 리뷰도 잘 부탁드립니다.
이번 단계 플로우는 다음과 같습니다.

[커밋 범위](https://github.com/woowacourse/jwp-dashboard-mvc/pull/441/files/2cea1336213ece6011d22e8d96bfc38be5ef4bdd..3d6bd07913c66f6df38ca8e73c94587cd67b7ba8)

## 플로우
![IMG_3ED58B3CE73B-1](https://github.com/woowacourse/jwp-dashboard-mvc/assets/63213487/f7e065f0-80c9-43a5-aec2-4a6debd847b7)

---

Legacy MVC와 어노테이션 기반 MVC가 공존할 수 있도록 구현을 했습니다.
이번 스텝에서는 `Register (GET, POST)`부분은 모두 어노테이션 기반 작동으로 변경해두었습니다.

현재는 `DispatcherServlet`에서 뷰를 반환해줄 때 `ModelAndView`인지 판단하고 분기에 따라 뷰를 내려주게 되는데요.

이 부분은 3단계 진행하면서 리팩토링 하도록 하겠습니다🙇🏻‍♂️

2023-09-18 06:38 UTC, java-saeng requested changes
안녕하세요 제이 ~~

미션하시느라 고생 많으셨습니다.

책임 분리가 잘 이뤄져있어서 코드 읽기가 쉬웠습니다 !!

이번 리뷰에서는 다른 Mapper가 추가된다면 변경될만한 곳을 최소한으로 줄여보는 것에 대해 같이 의견 다시 나눠보고 싶어서 Request Changes 하도록 하겠습니다 !!

2023-09-18 06:38 UTC, java-saeng commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            HandlerAdapter adapter = handlerAdapters.getHandlerAdapter(handler);
👍

2023-09-18 06:38 UTC, java-saeng commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/handler/adapter/HandlerAdapters.java
> +    public HandlerAdapter getHandlerAdapter(final Object controller) {
handlerAdapter를 찾는 것인데, 파라미터 이름이 controller여서 제 생각에는 조금 어색해보인다라는 생각이 들어요.

handler를 받아서 해당 handler에 맞는 adapter를 찾는거니까요~~?

2023-09-18 06:52 UTC, sosow0212 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/handler/mapper/HandlerExecution.java
> +    public ModelAndView execute(final HttpServletRequest req, final HttpServletResponse res) throws Exception {
`handler.handle()`보다 `handler.execute()`가 실행에 있어서 더욱 명확한 뜻을 가지고 있다고 생각해서 바꾸었습니다!

혹시 우르는 이에 대해 다른 의견을 가지고 계신가요?

2023-09-18 06:56 UTC, sosow0212 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        setupAnnotationHandler();
`Mapper`는 request를 처리해줄 HandlerMapper를 찾아주는 역할을 하고,

`Adapter`는 Mapper에서 받은 handler를 처리해줄 수 있는 HandlerAdapter를 찾아줍니다.
(기존 Controller 인터페이스 기반 컨트롤러와, 새로운 어노테이션 기반 컨트롤러는 실행될 수 있는 조건이 다르기 때문입니다!)

그리고 Adapter에서 반환받은 handler(method)를 실행한다면 사용자에게 응답이 내려지는 구조로 되어있습니다.

2023-09-18 06:58 UTC, sosow0212 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/handler/adapter/HandlerAdapters.java
> +    public HandlerAdapter getHandlerAdapter(final Object controller) {
리팩토링 하면서 이 부분을 바꾸지 못했네요~ 감사합니다.

현재 구조에서 말씀하신 것처럼 매개변수는 `controller`라는 네이밍보다는 `handler`가 적절한 것 같습니다~

2023-09-18 07:28 UTC, sosow0212 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        setupAnnotationHandler();
무조건 1:1은 아닙니다~
`handlerAdapter.isSupported(handler)` 메서드를 통해 핸들러에 해당하는 adapter를 찾아주는 구조로 되어있습니다.

따라서 Adapter에서 `isSupported`메서드의 내용이 변경된다면 1:1이 될 수도 있고, 1:N이 될 수도 있습니다.

다만 현재 미션에서는 1:N이 되는 경우는 없기 때문에, 기존 코드처럼 `DispatcherServlet`에서 `setup...Handler()`와 같은 메서드를 만들었습니다.

만약 1:N이 되는 경우도 고려해야한다면 `HandlerManagers`객체에서 `add()`를 통해 추가해줄 수 있습니다.

위에서 리뷰 남겨주신 것처럼 변경될만한 곳을 줄이기 위해서 `HandlerManager`객체를 만들고, 이 안에 `HandlerMappers`와 `HandlerAdapters` 객체를 두었습니다.

`HandlerManagers` 객체를 통해서 1:1인 관계를 등록해주는 메서드를 등록했고, 만약 1:N 관계도 필요하다면 `add~()` 메서드를 추가하면 될 것 같습니다. (현재는 그런 구조가 없기 때문에 만들지 않았습니다.)

2023-09-19 02:18 UTC, java-saeng commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/handler/mapper/HandlerExecution.java
> +    public ModelAndView execute(final HttpServletRequest req, final HttpServletResponse res) throws Exception {
별다른 이유는 없습니다 !

메서드 이름만 바꾸셨길래 무슨 계기가 있으셨나해서 여쭤봤어요!

handle, execute 모두 좋아보입니다

2023-09-19 04:22 UTC, java-saeng requested changes
리뷰 반영하시느라 고생 많으셨습니다!

이번 리뷰에서는 제이의 생각을 여쭤보는 부분만 있습니다.
편하게 제이의 생각을 말씀해주시면 좋을 것 같아요!!

2023-09-19 04:22 UTC, java-saeng commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/handler/HandlerManager.java
> +    public HandlerManager() {
Manager라는게 너무 추상적인 이름이지 않나라는 생각이 듭니다!

제가 처음에 Manager를 보면서 든 생각을 적어볼게요

핸들러를 매니징한다는게 무슨 뜻일까??
handlerMapper와 handlerAdapter를 매니징하는걸까?
핸들러를 매니징하는데 왜 Mapper와 Adapter가 있는거지?

라는 생각이 듭니다.

이 부분에 대해서 제이의 생각을 듣고 싶습니다!!

2023-09-19 08:45 UTC, sosow0212 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/handler/HandlerManager.java
> +public class HandlerManager {
기존에는 DispatcherServlet에서 `HandlerMappers`, `HandlerAdapters`를 관리한 반면에 이 둘을 한 곳으로 모아서 관리해주는 역할을 하게 돼서 책임이 분리 됐고 이 둘을 관리하기 편해졌다고 생각합니다.

하지만, Mapper와 Adapter의 전략이 바뀐다면 (예를 든다면 HandlerMapper라는 인터페이스 말고 추가적인 기능을 하는 인터페이스가 필요하다든지) 문제가 될 수 있을 것 같습니다.

우르는 이에 대해 어떻게 생각하시나요?

2023-09-19 08:52 UTC, sosow0212 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/handler/HandlerManager.java
> +    public HandlerManager() {
리뷰를 보니 말씀하신대로 Manager가 추상적인 네이밍인 것 같습니다.

HandlerAdapter, HandlerMapper를 초기 등록을 하고,
후에 찾아서 쓰니깐, `HandlerRegistry`로 변경하는게 그나마 뜻이 더 명확할 것 같습니다.

2023-09-20 00:58 UTC, java-saeng commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/handler/HandlerManager.java
> +public class HandlerManager {
저도 Manager(아래에서는 Registry라고 수정하셨지만)가 두 가지 역할을 모두 하는게 맞을까? 라는 생각이 듭니다.

제가 전 리뷰와 같이 말을 했던 이유는 DispatcherServlet에서 초기화하는 역할이 있었는데 이게 DispatcherServlet의 역할이 맞을까 라는 생각이 들었습니다.

HandlerMappers나 HandlerAdapters와 같은 일급 컬렉션이 존재하는데 여기서 초기화 할 수 있지 않았을까? 라는 생각에 리뷰를 드렸습니다.

> "하나의 클래스에서 두 가지 역할(Adapter, Mapper)을 수행할 수 있지 않나?" 라는 생각으로 단일책임원칙 위반 같기도 한데, 우르는 이에 대해 어떻게 생각하시나요?

"단일 책임 원칙 위반이어서 좋은 것은 아니다."라는 생각보다는 Manager 안에 Adapter, Mapper가 책임지는게 맞는걸까? 라는 관점에서 보면 좋을 것 같아요.

무조건 하나의 책임을 해야한다기보다는 해당 클래스가 하는 일이 맞을까? 라는 관점으로요!!

저라면 위에서 말씀드린대로 일급 컬렉션에서 초기화나 추가하는 것들을 행할 것 같아요!

2023-09-20 00:58 UTC, java-saeng commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/handler/HandlerManager.java
> +    public HandlerManager() {
[여기](https://github.com/woowacourse/jwp-dashboard-mvc/pull/442#discussion_r1330840138)에 같은 답이 될 것 같네요!

2023-09-20 00:59 UTC, java-saeng approved these changes
제이의 생각을 말씀해주셔서 감사합니다 !!

제가 남긴 내용은 제 생각이므로 무조건 반영하지 않아도 됩니다.
그냥 이런 생각이 있고, 제이는 어떤 생각을 했는지 얘기만 해도 충분한 것 같아요 ~~

제가 남긴 것에 대해서 궁금한 점 있으시면 편하게 DM 주시거나 comment 남겨주시면 좋을 것 같습니다 !!

이번 단계는 머지하고 다음 단계에서 뵙겠습니다 !!

2023-09-20 00:59 UTC, merged