[MVC 구현하기 2단계] 지토(김지민) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #445
Opened 2023-09-16 10:38 UTC by apptie

안녕하세요 이리내 
1단계 리뷰 정말 감사합니다 빠르게 진행하려다가 놓친 부분이 많았는데 덕분에 많이 잡을 수 있었습니다...감사합니다..

---

이번에는 그림을 좀 그려봤는데 생각보다 그림그리기가 어렵네요 
흐름은 대충 다음과 같습니다 
![제목 없는 다이어그램 drawio](https://github.com/woowacourse/jwp-dashboard-mvc/assets/57691173/8c844be8-9bc8-4c7d-bd23-7e82f6e80961)
1. DispatcherServlet이 HandlerMappings에서 Handler 조회
1-1. Handler가 없으면 null을 반환합니다 (요청을 처리할 핸들러가 없다고 판단해 404를 반환하기 위함)
2. DispatcherServlet이 HandlerAdapter에서 HandlerAdapter 조회
2-1. 여기서 해당 요청을 처리할 수 있는 Handler가 있다면 무조건 그 HandlerAdapter도 존재해야한다고 생각해 예외를 터뜨렸습니다
3. DispatcherServlet이 HandlerAdapter.execute()로 요청을 처리
4. HandlerAdapter는 요청을 처리하고 그 결과로 반환값을 ModelAndView로 통일해 반환

---

최대한 주어진 클래스나 메서드 시그니처를 지키려고 노력했습니다 
그리고 패키지..는...app만 얼추 해놨는데...좀 애매하네요 
mvc는 asis랑 tobe 패키지의 의미가 도대체 뭔지 몰라서 일단 방치했습니다...

이번 리뷰도 잘 부탁드립니다!

2023-09-19 05:13 UTC, hectick requested changes
안녕하세요 지토~! 코드 잘 보았습니다! 기존 코드를 유지하면서 작업하신 방식이 인상깊었어요~
코멘트랑 질문 몇자 남겨보았으니 확인 부탁드립니다용

그리고 저도 asis, tobe 패키지가 뭔가해서 검색을 좀 해봤는데 아래처럼 나오더라고요.
AS-IS: 현재의 상태나 모습
TO-BE:미래의 이상적인 상태나 목표

여기에 기반한 저의 뇌피셜은 아래와 같습니당! 참고해주세요
asis -> 레거시, Controller 인터페이스 사용 관련 패키지
tobe -> `@Controller` 어노테이션 사용 관련 패키지

2023-09-19 05:13 UTC, hectick commented on app/src/main/java/com/techcourse/support/web/adapter/HandlerAdapters.java
> +        final AnnotationHandlerAdapter annotationHandlerAdapter = new AnnotationHandlerAdapter();
사소한 부분이긴 한데, 변수 선언을 할 때 인터페이스를 통해 선언하는 것은 어떤가요?
만들어진 두 객체가 HandlerAdapter의 구현체라는게 더 잘 보일 것 같아요.

```suggestion
        final HandlerAdapter manualHandlerMappingAdapter = new ManualHandlerMappingAdapter(viewResolvers);
        final HandlerAdapter annotationHandlerAdapter = new AnnotationHandlerAdapter();
```

2023-09-19 07:22 UTC, apptie commented on app/src/main/java/com/techcourse/support/web/mapping/ManualHandlerMapping.java
>      }
이렇게 생각한 이유는 미션 2단계에서 `기존 코드를 유지하면서 신규 기능을 추가해야 한다.`라고 언급된 부분 때문이었습니다 
이전 톰캣 미션할 때도 구구가 코드를 변경하지 말라고 한 점과, 기존 코드를 유지하라는 것에서 구구가 의도하신 내용이 기존 코드의 변경이 아예 없거나 최소화하는 방향을 원한다고 생각했었습니다 

그래서 그냥...지켜주는 식으로 진행했습니다
사실 저도 이게 미션이 아니었다면 이리내가 하셨던대로 ManualHandlerMapping를 변경해줬을 것 같습니다

2023-09-19 07:24 UTC, apptie commented on app/src/main/java/com/techcourse/support/web/adapter/ManualHandlerMappingAdapter.java
> +    }
저는 jsp를 뷰로 렌더링할 때 직접 jsp 파일을 읽고 세션에 저장된 데이터 등등을 제가 직접 대체하면서 진행해야 한다고 생각했었습니다
그래서 세션에 있는 값을 조금 더 편하게 처리해주기 위해 request로 옮겨준 것이었는데 
알고보니 아니더라고요...그래서 해당 코드는 삭제할 생각입니다 ㅎㅎ;

2023-09-19 07:27 UTC, apptie commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +            final HandlerExecution handlerExecution = new HandlerExecution(handler, method);
이전에는 하나의 HandlerKey에 모든 requestMapping.method(배열)을 저장해줬는데, 이 경우 요청이 올 때마다 배열에서 해당 HttpMethod가 존재하는지 확인하는 로직이 필요했었습니다 
그래서 GET, POST와 같이 HttpMethod가 여러 개인 경우에는 항상 반복문을 통해 확인해야 했었는데

HandlerKey에 단일 HttpMethod를 만들게 된다면 생성 시에는 비용이 이전보다 더 소모되겠지만 조회 시에는 이전보다 비용이 덜 들것이라고 판단했고, 생성보다는 조회하는 횟수가 더 클 것이라고 판단해서 이렇게 분리하게 되었습니다

2023-09-19 07:27 UTC, apptie commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/ClassScanner.java
> +    }
👍

2023-09-19 07:28 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>          }
ViewResolver에서 view를 찾지 못한 경우 null을 반환해주는 상황입니다 

Jsp를 반환하는 경우와 같이 리소스를 반환할 것을 명시했지만, 해당 리소스를 찾지 못하는 경우라고 봐주시면 될 것 같습니다

2023-09-19 07:28 UTC, apptie commented on app/src/test/java/com/techcourse/support/web/adapter/AnnotationHandlerAdapterTest.java
> +        final Object invalidHandler = null;
귀찮아서...ㅎㅎ..; 말씀해주신대로 변경하도록 하겠습니다

2023-09-19 07:36 UTC, apptie commented on app/src/test/java/com/techcourse/support/web/adapter/HandlerAdaptersTest.java
> +            softAssertions.assertThat(handlerAdapters.getHandlerAdapter(new LoginController())).isNotNull();
그렇네요 삭제하도록 하겠습니다

2023-09-19 07:36 UTC, apptie commented on app/src/test/java/com/techcourse/support/web/adapter/ManualHandlerMappingAdapterTest.java
> +        final boolean actual = adapter.supports(new ManualHandlerMappingWrapper());
귀찮았어서..ㅎㅎ..; 말씀하신대로 수정하도록 하겠습니다

2023-09-19 07:39 UTC, apptie commented on app/src/test/java/com/techcourse/support/web/mapping/HandlerMappingsTest.java
> +            softAssertions.assertThat(handlerMappings.getHandler(request)).isNotNull();
테스트 코드에...퀄리티가 ㅎㅎ; 삭제하도록 하겠습니다

2023-09-19 07:41 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>  public class DispatcherServlet extends HttpServlet {
넵 동의합니다 
저도 그래서 바꾸려고 했는데...
이게 3단계 미션의 요구사항이더라고요 
그래서 일단 방치시켜놨는데, 지금 진행하는게 좋을까요?

2023-09-19 07:42 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private final transient HandlerAdapters adapters = new HandlerAdapters();
transient는 직렬화를 할 때 대상에서 제외하는 역할로 알고 있습니다 
역직렬화를 할 때, 해당 필드는 존재하지만 값이 null로 되는 것으로 알고 있습니다

해당 코드의 경우 어떤 adapter를 사용하고 handler를 사용하는 것까지 직렬화의 대상으로 둘 이유가 없다고 판단해 제거해주었습니다

2023-09-19 07:49 UTC, apptie commented on app/src/main/java/com/techcourse/support/web/resolver/JsonViewResolver.java
> +        return acceptHeaderValue != null && acceptHeaderValue.contains(APPLICATION_JSON_VALUE);
일단 accept 헤더의 유무에 따라 404인지 뷰인지는 의도한 부분이 맞습니다 
accept 헤더가 없다면 서버의 재량껏 반환해줘도 되는 것으로 알고 있는데, 그냥 404를 반환하고 싶었습니다..

accept 타입이 없을 경우 추가적으로 서버가 대응할 수 있도록 리펙토링 하도록 하겠습니다

2023-09-19 07:50 UTC, apptie commented on app/src/main/java/com/techcourse/support/web/adapter/HandlerAdapters.java
> +        final AnnotationHandlerAdapter annotationHandlerAdapter = new AnnotationHandlerAdapter();
맞습니다 이거는 제가 놓친 부분이네요 리펙토링 하도록 하겠습니다 감사합니다

2023-09-19 07:52 UTC, apptie commented on app/src/main/java/com/techcourse/support/web/mapping/ManualHandlerMappingWrapper.java
> +    private final ManualHandlerMapping mappings = new ManualHandlerMapping();
해당 코멘트를 보고 Google Java Style Guide를 확인해봤는데 s는 문자열같은 곳에서만 사용하는 것이었군요..
몰랐습니다 ㄷㄷ 
변경하도록 하겠습니다 감사합니다

2023-09-19 07:55 UTC, apptie commented on app/src/main/java/com/techcourse/support/web/adapter/ManualHandlerMappingAdapter.java
> +    }
LoginController에서 세션에 저장하는 User 도메인 같은 경우를 렌더링할 때 써먹으려고 했었습니다...

2023-09-19 10:08 UTC, hectick commented on app/src/main/java/com/techcourse/support/web/mapping/ManualHandlerMapping.java
>      }
아하 그렇군요.
저는 기존 컨트롤러 코드를 유지하면서 어노테이션 컨트롤러도 동작할 수 있게 하라는 의미로 이해해서 궁금했던 것이었어요!

2023-09-19 10:09 UTC, hectick commented on app/src/main/java/com/techcourse/support/web/adapter/ManualHandlerMappingAdapter.java
> +    }
> 알고보니 아니더라고요...

요부분이 궁금한데요!?

2023-09-19 10:10 UTC, hectick commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +            final HandlerExecution handlerExecution = new HandlerExecution(handler, method);
생성은 처음 한번이면 되지만 조회는 애플리케이션이 돌아가는 한 여러번하기 때문이군요..! 좋습니다 👍👍👍

2023-09-19 10:12 UTC, hectick commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>          }
아하.
현재는 viewResolver에서 JsonView나JspView 객체 생성만 하고 있어서 궁금했어요

> Jsp를 반환하는 경우와 같이 리소스를 반환할 것을 명시했지만, 해당 리소스를 찾지 못하는 경우

이 부분은 3단계때 마저 구현되는 것이죠?

2023-09-19 10:14 UTC, hectick commented on app/src/test/java/com/techcourse/support/web/adapter/AnnotationHandlerAdapterTest.java
> +        final Object invalidHandler = null;
귀차니즘 이겨낼 수 있습니다💪💪

2023-09-19 10:27 UTC, hectick commented on app/src/main/java/com/techcourse/support/web/mapping/ManualHandlerMappingWrapper.java
> +    private final ManualHandlerMapping mappings = new ManualHandlerMapping();
앗.. 저는 단지 
1. 일반적으로 클래스 명과 변수 명을 같게 하고 (클래스명이 Mapping이니 변수명도 단수가 아닐까 싶었죠..~)
2. dispatcherServlet에서 HandlerMappings의 변수명을 mappings 복수형으로 하셨길래
확인차 물어본 것이었어요!

2023-09-19 10:33 UTC, hectick commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>  public class DispatcherServlet extends HttpServlet {
오호.. View 구현하는 것만 있는 줄 알았더니 그런 요구사항도 있었네요.
제가 요구사항을 면밀히 관찰하지 못했습니다..

> Legacy MVC를 제거하고 나서 DispatcherServlet도 app 패키지가 아닌 mvc 패키지로 옮겨보자.

DispatcherServlet이 아닌 것들 중에 미리 옮겨볼 수 있는 것이 있을 것 같아요!
예를들어 resolver들이나, annotation 관련한 클래스들말이지요

2023-09-19 10:52 UTC, hectick commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private final transient HandlerAdapters adapters = new HandlerAdapters();
transient 키워드에 대해 잘 알고 계신 것 같아용 👍
저는 인텔리제이에 깔아둔 코드 분석 툴이 trasient를 붙이라길래 붙이긴 했지만,
DispatcherServlet이 직렬화의 대상이 될거란 생각이 들지 않아 안붙여도 괜찮지 않을까 생각해요.
지토는 DispatcherServlet이 직렬화의 대상이 될 수 있다고 생각하시나요?

2023-09-19 10:53 UTC, hectick commented on app/src/main/java/com/techcourse/support/web/resolver/JsonViewResolver.java
> +        return acceptHeaderValue != null && acceptHeaderValue.contains(APPLICATION_JSON_VALUE);
> accept 헤더가 없다면 서버의 재량껏 반환해줘도 되는 것으로 알고 있는데, 그냥 404를 반환하고 싶었습니다..

서버의 재량이었다니.. 존중하도록 하겠습니다!
다만 */* 타입에도 대응할 수 있게 해주세요!

2023-09-19 15:15 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>          }
넵 맞습니다! 3단계 때 진행할 예정입니다!
그대로 유지할 수 있었으면 좋겠네요 ㅎㅎ;

2023-09-19 15:26 UTC, apptie commented on app/src/main/java/com/techcourse/support/web/mapping/ManualHandlerMappingWrapper.java
> +    private final ManualHandlerMapping mappings = new ManualHandlerMapping();
어...제가 본 내용은 Google Java Style Guide의 한글 번역본이었고, `Users -> UserCollection`과 같은 방식으로 쓰는 걸 권장한다는 예시였는데...저도 원본으로 볼 때에는 안보이네요..?

계속 찾아보니 `computedValues`와 같은 예시가 있는 것을 보면, 제가 의도치 않게 속인 것 같습니다...죄송합니다..

2023-09-19 15:27 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>  public class DispatcherServlet extends HttpServlet {
말씀하신 부분들은 모두 변경이 가능하겠네요 리펙토링을 하도록 하겠습니다

2023-09-19 15:37 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private final transient HandlerAdapters adapters = new HandlerAdapters();
저도 논리적으로는 DispatcherServlet은 직렬화의 대상이 되지 않는다고 생각합니다 
프레임워크에 속하게 될테니 애플리케이션 기준으로는 어떤 애플리케이션이라도 동일한 DispatcherServlet이기 때문에 의미가 없다고 생각합니다

다만 HttpServlet이 확장하고 있는 GenericServlet이 Serializable을 구현하고는 있어서 직렬화가 코드 상으로는 가능한데, 여기서 serialVersionUID를 필드로 갖게 되서 현재 코드 상으로는 DispatcherServlet이 직렬화의 대상이 된 것 같습니다 

그래서 저도 만약 수정한다면 transient도 빼고...serialVersionUID도 뺄 것 같습니다
하지만 일단 기존 코드에 있었으니 방치하는 걸로...

2023-09-19 15:41 UTC, apptie commented on app/src/main/java/com/techcourse/support/web/resolver/JsonViewResolver.java
> +        return acceptHeaderValue != null && acceptHeaderValue.contains(APPLICATION_JSON_VALUE);
아 `*/*`는 고려하지 못했었네요
해당 부분은 JsonView가 처리하도록 하겠습니다 감사합니다 👍

2023-09-20 18:21 UTC, hectick requested changes
안녕하세요 지토! 변경된 부분 확인했습니다! 👏
다만 리팩터링 하겠다고 하신 부분중에 아직 확인이 안되는 부분이 보여서 질문을 달아놨어요!
리팩터링 커밋 or 답변을 해주시고 다시 pr요청을 보내주시면 확인하고 바로 approve 하도록 하겠습니다!!

2023-09-20 18:34 UTC, hectick commented on app/src/main/java/com/techcourse/support/web/resolver/JsonViewResolver.java
> +        return acceptHeaderValue != null && acceptHeaderValue.contains(APPLICATION_JSON_VALUE);
`*/*` 이부분도 커밋이 없는 것 같은데요!
view 관련된 부분은 3단계때 변경이 어떻게 일어날지 몰라서, 아직 안하셨다면 3단계때 하셔도 좋을 것 같아요!

2023-09-21 01:43 UTC, apptie commented on app/src/main/java/com/techcourse/support/web/mapping/HandlerMappings.java
> +    private final List<HandlerMapping> mapping = new ArrayList<>();
앗 제가 오락가락해버리는 이슈가.....제대로 적용하겠습니다..죄송합니다..

2023-09-21 01:43 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private final transient HandlerAdapters adapter = new HandlerAdapters();
아닙니다 제가 정신이 오락가락했던 이슈였던 것 같습니다..저야말로 정말 죄송합니다..

2023-09-21 01:50 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServletInitializer.java
> +                         .addHandlerAdapter(new AnnotationHandlerAdapter());
넵 맞습니다 자꾸 뭐 하려다가 빼먹네요 정말....정신이 없네요...

2023-09-21 04:41 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
>  public class DispatcherServlet extends HttpServlet {
해당 부분은 제가 이상한...PR을 날렸기 때문에 발생한 이슈였습니다
사실 이리내가 해주신 이 코멘트를 보고 깨달을 수 있었습니다..
해당 부분...그 정리하고 다시 PR 보내면서 정리해서 답변드리겠습니다..

2023-09-21 05:30 UTC, closed without merging