[MVC 2단계] 헙크 미션 제출합니다
woowacourse/jwp-dashboard-mvc pull request #449
Opened 2023-09-16 14:50 UTC by HubCreator

안녕하세요 홍고!
DispatcherServlet 쪽에서 `HandlerMapping`과 `HandlerAdapter`를 만들어봤습니다. 괜찮은 방식인지 홍고의 의견을 듣고 싶습니다 ㅎㅎㅎ
저번 리뷰에서 말씀해주셨던 `HandlerExecution`에서 굳이 instance를 필드로 두지 않고, method로부터 `getDeclaringClass`를 사용하도록 하는 부분도 적용해봤습니다. 사실 그렇게 하지 않았을 때 `object is not an instance of declaring class` 라는 메시지와 함께 오류가 발생하는 경우가 생기더라구요ㅠㅠㅠ 그래서 조금 더 정합성을 맞추기 위해 홍고가 말씀해주신 방법이 떠올라 해결했습니다. 감사합니다 ㅎㅎㅎ

2023-09-16 15:08 UTC, HubCreator commented
에고 .. 일단 컨플릭트 나는 것은 주중에 바로 해결해보겠습니다

2023-09-18 11:53 UTC, hgo641 requested changes
안녕하세요, 헙크!
코드가 너무 깔끔해서 리뷰가 아니라 배우려는 마음으로 봤습니다ㅎㅎ 👍
`HandlerAdapter`를 추가해 레거시인 인터페이스 기반 컨트롤러와 어노테이션 기반 컨트롤러를 둘 다 사용할 수 있게 변경하셨군요! 좋은 구조인 것 같습니다!

궁금한 거 몇 개 코멘트로 남겼어요! 미션하시느라 고생 많으셨습니다!

2023-09-18 11:53 UTC, hgo641 commented on app/src/main/java/com/techcourse/support/web/adapter/ManualHanlderAdapter.java
> +    public ModelAndView handle(final Object handler, final HttpServletRequest request, final HttpServletResponse response) throws Exception{
별건아닌데 Exception{ 띄우면 어떨까요?!

2023-09-18 11:53 UTC, hgo641 commented on app/src/main/java/com/techcourse/support/web/mapping/HandlerMappings.java
> +        return null;
Optional을 반환하는 건 어떻게 생각하시나요?

2023-09-18 11:53 UTC, hgo641 commented on app/src/main/java/com/techcourse/support/web/adapter/ManualHanlderAdapter.java
> +public class ManualHanlderAdapter implements HandlerAdapter {
오타를 찾았습니다! 😎
ManualHanlderAdapter

2023-09-18 11:53 UTC, hgo641 commented on app/src/main/java/com/techcourse/support/web/mapping/ManualHandlerMapping.java
> +        log.debug("Request Mapping Uri : {}", request);
uri가 아니라 객체가 출력되고 있는 것 같아요!

2023-09-18 11:53 UTC, hgo641 commented on app/src/main/java/com/techcourse/support/web/adapter/AnnotationHandlerAdapter.java
> +public class AnnotationHandlerAdapter implements HandlerAdapter {
`HandlerAdapter`의 구현체인 `AnnotationHandlerAdapter`와 `ManualHanlderAdapter` 를 app패키지 하위에 두신 이유가 궁금해요~~

2023-09-19 03:00 UTC, HubCreator commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            if (Objects.isNull(handler)) {
넵! 가독성 때문입니다!! 그냥 개인 취향..?! 입니다 ㅎㅎㅎ

2023-09-19 03:06 UTC, HubCreator commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        } catch (final Throwable e) {
기존 제공 코드를 손대지 않긴 했는데, 확실히 어색하네요. Throwable 하위에 Error와 Exception이 존재하는데, 굳이 Error를 catch하여 애플리케이션 레벨에서 핸들링 할 수 있는 것이 없다고 생각됩니다. 이부분은 Exception으로 잡아주어도 좋을 것 같네요!! 꼼꼼하시네요 ㅎㅎㅎ

2023-09-19 03:14 UTC, HubCreator commented on app/src/main/java/com/techcourse/support/web/mapping/HandlerMappings.java
> +        return null;
좋아요!!!!

2023-09-20 16:15 UTC, HubCreator commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.getView().render(Collections.EMPTY_MAP, request, response);
저도 아 이건 다음 단계에서 하나보다 하고 EMPTY_MAP을 넘겨주었던 것 같아요 ㅎㅎㅎ 하지만 `ModelAndView` 쪽에 `getModel()`이 있다는 것을 알았는데, 이를 호출해서 이전에 이 model에 넣어줬던 값을 그대로 view쪽에 넘겨줄 수 있을 것 같습니다. `getModel()`을 호출하도록 수정하였습니다!

2023-09-20 16:43 UTC, HubCreator commented on app/src/main/java/com/techcourse/support/web/adapter/AnnotationHandlerAdapter.java
> +public class AnnotationHandlerAdapter implements HandlerAdapter {
패키지 간의 의존성을 고민하는 데에 조금 시간이 걸린 것 같습니다 ㅠㅠㅠ 저는 app에서는 mvc로 의존성을 가져도 되지만 그 반대인 mvc에서 app으로는 의존성을 가지면 안된다 라고 판단했습니다. app 패키지 같은 경우는 서비스의 특성에 따라 여러 개가 되고 비즈니스 로직이 집중되어 있을테지만, mvc의 경우 프레임워크의 코드가 존재하기에 여러 app에서 이를 가져다 쓸 것이라고 생각했습니다.

따라서 `Adapters`나 `Mappings`를 mvc쪽으로 이동하였습니다. 다만 `ManualHandlerMapping`같은 경우는 app에서 사용자가 직접 인터페이스를 구현하여 뷰와 컨트롤러를 매핑해주어야 하기 때문에, 프레임워크의 코드가 app에 침투될 수 밖에 없다고 생각했습니다. 따라서 해당 클래스 이외에는 모두 mvc쪽으로 이동시켰습니다!

2023-09-21 01:32 UTC, hgo641 approved these changes
안녕하세요, 헙크!
답변 달아주신 거 잘 확인했습니다 👍👍
2단계 고생하셨습니다! 3단계로 가시죠~ ~ 🚀

2023-09-21 01:32 UTC, merged