[MVC 구현하기 2단계] 베베(최원용) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #450
Opened 2023-09-16 17:39 UTC by wonyongChoi05

안녕하세요 엔델~~ 스프링 MVC 내부 구조에 익숙하지 않아서 이번에도 구현하는데 좀 어설펐네요 ㅠㅠ 부족한 부분 리뷰 잘 부탁드립니다!

2023-09-19 13:56 UTC, SproutMJ requested changes
안녕하세요, 베베 제가 시간이 좀 걸려서 리뷰가 늦어서 죄송합니다,,,
작성해주신 코드에서 흐름을 잘 볼 수 있어서 좋았던 것 같아요! 잘 해주셔서 제가 보기엔 대부분 스타일과 관련한 부분인 것 같습니다.
예를들어 안쓰이는 의존성, final(Optional) 키워드, 개행 통일 불일치가 주된 부분인 것 같은데요, 다시 리뷰요청 주시면 재확인하겠습니다.

감사합니다.

2023-09-19 13:56 UTC, SproutMJ commented on app/src/main/java/com/techcourse/controller/lagacy/LoginController.java
> +import context.org.springframework.stereotype.Controller;
안쓰이는 의존성인 것 같아요.

2023-09-19 13:56 UTC, SproutMJ commented on app/src/main/java/com/techcourse/controller/lagacy/LoginController.java
> +    @RequestMapping(value = "/login", method = GET)
다른 lagacy 패키지의 컨트롤러와 달리 @RequestMapping가 붙어있어요. 혹시 의도된 것일까요?
그리고 다른 곳에도 언급 했지만 로그인 로직이 들어있는데 GET 메소드로 되어 있는 것이 조금 의문입니다!

2023-09-19 13:56 UTC, SproutMJ commented on app/src/main/java/com/techcourse/controller/mvc/MvcLoginController.java
> +    @RequestMapping(value = "/login", method = RequestMethod.GET)
로그인할 때 GET 메서드로 하는 것이 맞는지 궁금합니다!

2023-09-19 13:56 UTC, SproutMJ commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        HandlerAdapter handlerAdapter = handlerAdapters.getHandlerAdapter(handler);
final이 누락되어 있네요...(이부분 포함)

2023-09-19 13:56 UTC, SproutMJ commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerMapper.java
> +    void initialize();
HandlerAdapter와 통일성있는 개행이 있으면 좋을 것 같습니다!

2023-09-19 13:56 UTC, SproutMJ commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerMappers.java
> +public class HandlerMappers {
HandlerMappers는 app 모듈의 DispatcherServlet에서만 사용되는 것 같고, HandlerAdapters와 위치가 다르게 되어있는데 혹시 이유를 알려주실 수 있나요?

2023-09-19 13:56 UTC, SproutMJ commented on app/src/main/java/com/techcourse/support/handler/HandlerAdapters.java
> +            .orElseThrow(() -> new IllegalArgumentException("Handler adapter Not Found: " + handler));
이부분에서 사용할 adapter를 찾는 것 같네요. 다형성을 이용해 if를 사용하지 않아도 되어서 좋은 것 같습니다.

2023-09-19 14:53 UTC, wonyongChoi05 commented on app/src/main/java/com/techcourse/controller/lagacy/LoginController.java
> +    @RequestMapping(value = "/login", method = GET)
LoginViewController와 같이 만들다보니 헷갈렸네요! 알려주셔서 감사합니다 ㅎㅎ

2023-09-19 14:53 UTC, wonyongChoi05 commented on app/src/main/java/com/techcourse/controller/mvc/MvcLoginController.java
> +    @RequestMapping(value = "/login", method = RequestMethod.GET)
https://github.com/woowacourse/jwp-dashboard-mvc/pull/450#discussion_r1330268446

2023-09-19 14:56 UTC, wonyongChoi05 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerMappers.java
> +public class HandlerMappers {
이 부분도 실수였네요 ㅠ

2023-09-20 04:28 UTC, SproutMJ approved these changes
일단 제가 남긴 코멘트를 빠른 시간에 해결해 주셔서 감사합니다.
이번 단계는 넘어가도 좋을 것 같아요!

사실, HandlerMappers에 아직 안쓰이는 import java.util.Objects;가 있기는 한데요. 
이미 아실지도 모르지만 인텔리제이의 코드 최적화 단축키를 폴더에 대고 하면 폴더 안의 파일에 전부 최적화가 적용이 됩니다. 참고하시면 좋을 것 같아요.

그럼, 다음 단계에서 뵙겠습니다.

2023-09-20 04:28 UTC, merged