[MVC 구현하기 2단계] 가비(이준희) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #461
Opened 2023-09-17 17:53 UTC by iamjooon2

2023-09-19 15:04 UTC, MoonJeWoong requested changes
안녕하세요 가비, 히이로입니다! 🎵

전반적으로 스프링의 구조를 따라 미션을 잘 수행해주신 것 같습니다. 그래서 따로 변경을 요구하는 리뷰는 하나 정도만 제안드리고 나머지는 가비와 의견을 나눠볼 수 있는 내용을 질문드려봤습니다. 데모데이 준비로 많이 바쁘실텐데 시간 되시는대로 편하게 답글 달아주시면 확인하겠습니다 ㅎㅎ. 

혹시 추가적으로 얘기 나눠보고싶으신 부분 생기시면 댓글이나 DM으로 연락 주세요! 🙇

2023-09-22 10:00 UTC, iamjooon2 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java
> +    }
히이로와 얘기를 나눌 정도로.. 고민을 오래하고 구현한 부분은 아닙니다🥲
직관적으로 떠올랐고, 가장 간편한 방법이라 선택했습니다

데모데이가 끝난 지금 여유롭게 다시 생각해보니

```java
public boolean supports(Object handler) {
    return handler.getClass().equals(HandlerExecution.class);
}

```
요런식으로 클래스를 비교해서 사용할 수도 있을 것 같습니다.! 
더 좋은 의견 있으시면 좋은 부탁드립니다

2023-09-22 11:10 UTC, iamjooon2 commented on app/src/main/java/com/techcourse/ManualHandlerMapping.java
> +        String requestURI = request.getRequestURI();
> 이번 미션을 진행하면서 기존 controller들과 더불어서 이 ManualHandlerMapping도 하나의 레거시라고 생각하고 수정하지 못한다는 제약조건을 생각하며 진행했었습니다.

와 전혀 생각하지 못했습니다

아마 위 제약조건을 꼭 지켜야 한다 생각한다면, ManualHandlerMapping은 다형성을 적용하지 않고 그대로 두었을 것 같습니다..만
지금 미션의 경우는 변경에 들어가는 리소스가 매우 적은 편이라고 생각합니다.
그리고 그 들이는 리소스에 반해, 얻을 수 있는 이득이 훨씬 클 것 같습니다.
제약조건이 걸려있는게 아니라면 다시 미션을 진행하더라도 공통되게 추상화를 했을 것 같네요.

리뷰 남겨주셔서 감사합니다! 생각 못했던 부분이었어요

2023-09-22 11:12 UTC, iamjooon2 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerMappings.add(new AnnotationHandlerMapping("com.techcourse.controller"));
오 좋습니다!
LMS를 보니 HandlerAdapaterRegistry라는 일급 컬렉션 비스무리한 친구가 있군요

2023-09-22 11:13 UTC, iamjooon2 commented
안녕하세요 히이로!
5차 데모데이가 끝나서, 코멘트 답변 및 리뷰 반영하였습니다~!

오늘 발표 고생하셨어요 :D

2023-09-22 13:29 UTC, iamjooon2 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerMappings.add(new AnnotationHandlerMapping("com.techcourse.controller"));
분리 완료하였습니다!

2023-09-23 16:30 UTC, MoonJeWoong commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java
> +    }
instanceOf가 아니라 isInstance 메서드가 있는지는 이번에 처음 알았네요 새로 배워갑니다 ㅎㅎ...
처음에 instanceOf의 성능이 일반적으로 메서드 호출을 통한 타입 검사보다 속도가 많이 느리다고 알고 있었기에 스프링에서도 그렇고 왜 이렇게 사용했을까를 고민했었습니다. 저는 이번 미션을 진행하면서 instanceOf를 사용하지 않기 위해 최대한 다형성을 활용해서 풀어내려고 했었거든요.

![image](https://github.com/woowacourse/jwp-dashboard-mvc/assets/31722737/55cb4050-069a-4e59-9a10-385565fbe73c)

여러 레퍼런스를 찾아봐도 일반적으로 크게 따질 필요 없는 수준의 성능 차이라고만 하길래 실제로 테스트해본 결과 isInstance가 instanceOf보다 빨랐습니다. instanceOf는 개인적으로 한 요청에 있어서 여러번에 걸쳐 수행되면 성능 상 문제가 될 수도 있을 가능성이 있을 거 같다는 생각이 들었습니다. 하지만 현재 발생한 문제는 아니기도 하고  isInstance로도 충분한 개선이 된 것 같다고 생각합니다. 함께 생각해주셔서 감사해요~ 👍

2023-09-23 16:41 UTC, MoonJeWoong approved these changes
2단계 피드백 반영하시느라 고생하셨어요 가비!
사실 별다른 검토사항은 없었어서 빠르게 merge 시켜드렸어야 했는데 발표도 그렇고 instanceOf 사용에 대해 좀 생각해보려다가 오래 걸려버렸네요 ㅎㅎ... 🙇 

얼른 3단계 미션까지 빠르게 진행해보시죠!

2023-09-23 16:41 UTC, merged