[MVC 구현하기 - 2단계] 쥬니(전정준) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #483
Opened 2023-09-18 12:36 UTC by cpot5620

안녕하세요 땡칠 ~!
HandlerMapping / HandlerAdaptor 인터페이스를 구현하여 레거시 코드에 대응하는 방법으로 구현해보았습니다.

추가적으로, 이전 PR 요청에서 달아주신 코멘트 반영 완료했으니 확인 부탁드려요 !

한 가지 이야기 나누어보고 싶은게 있는데요.
`AnnotationHandlerMapping` 클래스를 어느 패키지에 두는 것이 자연스러운지 잘 모르겠어요.
(사실 패키지 분리에 대한 지식이 부족해서 ㅠㅠ)
Annotation 관련된 클래스(인터페이스)를 mvc 하위 패키지에 둔 상태긴 합니다만, app 패키지에서 mappings / adaptors 등을 구현하고 있습니다. 그래서, 해당 `AnnotationHandlerMapping` 클래스도 app 패키지에 두어야 하나 싶어요.

해당 클래스를 app 패키지에 둘 경우, 리플렉션과 관련된 의존성도 추가해주어야 해서, 구구의 숨겨진 의도가 있을까 싶기도 하구요.

질문이 조금 멍청(?)해보이기도 하고, 답변하기 곤란하실 것 같으면 답변 안 해주셔도 됩니다 ! 그냥 의견이 듣고 싶었어요 ㅎㅎ

좋은 리뷰 미리 감사합니다 ~!

2023-09-18 12:50 UTC, 0chil reviewed
> 한 가지 이야기 나누어보고 싶은게 있는데요.
AnnotationHandlerMapping 클래스를 어느 패키지에 두는 것이 자연스러운지 잘 모르겠어요.
(사실 패키지 분리에 대한 지식이 부족해서 ㅠㅠ)
Annotation 관련된 클래스(인터페이스)를 mvc 하위 패키지에 둔 상태긴 합니다만, app 패키지에서 mappings / adaptors 등을 구현하고 있습니다. 그래서, 해당 AnnotationHandlerMapping 클래스도 app 패키지에 두어야 하나 싶어요.
> 
> 해당 클래스를 app 패키지에 둘 경우, 리플렉션과 관련된 의존성도 추가해주어야 해서, 구구의 숨겨진 의도가 있을까 싶기도 하구요.
> 
> 질문이 조금 멍청(?)해보이기도 하고, 답변하기 곤란하실 것 같으면 답변 안 해주셔도 됩니다 ! 그냥 의견이 듣고 싶었어요 ㅎㅎ

저도 살짝 고민이 있었던 내용이었습니다~~ 전혀 이상하지 않고, 오히려 좋은 고민을 해보셨다고 생각해요.
제 생각부터 말씀드려보자면, 
저는 현재 패키지 구조가 app과 mvc로 나뉜 것은 '프레임워크의 영역이냐, 아니면 개인(혹은 단체) 어플리케이션의 영역이냐?' 가 기준이라고 생각합니다.

`HandlerMapping`, `HandlerExecution` 인터페이스 등을 포함한, 'mvc' 패키지의 클래스들은 쥬니의 웹 프레임워크 사용자라면 꼭 필요한 공통적인 내용이고,

'app' 패키지에 있는 `LoginController`, `ManualHandlerMapping` 과 같은 클래스들은 쥬니 프레임워크 사용자라면 누구나 자신의 목적에 맞게 커스텀하고 싶은 영역이라고 생각해요.

이 기준에서 보면 `AnnotationHandlerMapping`은 어디에 있으면 좋을까요?

--- 

리뷰는 이 커멘트와 별도로 남길게요~!

2023-09-18 17:57 UTC, 0chil requested changes
안녕하세요 쥬니~ 땡칠입니다!
주말 잘 보내셨나요?

2단계도 잘 구현해주셨습니다.
저는 이번 단계 목표가 'Controller 인터페이스와 app 패키지 코드를 최대한 변경하지 않기' 였는데, 쥬니도 Adaptor를 통해 잘 달성하신 것 같아요.
Adaptor 코드를 리뷰하다가 instanceof도 의도에 맞게 사용해야 한다는 것을 새로 알게 되었네요.
기존보다 더 구체화된 예외처리도 좋아요 👍

쥬니 코드를 리뷰하다보니 코드 상에서 '핸들러'에 대한 정의가 조금 헷갈렸어요 🥲
클래스 구조 그림과 함께 커멘트 남겼으니 제가 잘못 이해했다면 말씀해주세요.

그 외엔 작은 커멘트 몇 개 남겼으니, 확인해주시고 필요한 건 반영해주세요!

--- 

그리고 아래는 제가 고민하고 있는 커멘트인데, 쥬니도 생각나는 것이 있다면 글 남겨주시면 감사하겠습니다~
(좀 길어요 ㅠㅠ)
https://github.com/woowacourse/jwp-dashboard-mvc/pull/462#discussion_r1328134327

2023-09-19 06:03 UTC, cpot5620 commented on app/src/main/java/com/techcourse/controller/RegisterAnnotationController.java
> +    public ModelAndView show(HttpServletRequest request, HttpServletResponse response) {
기존 뼈대 코드에서는 메서드를 기준으로 컨트롤러를 구분하지 못하도록 설계되었던 것 같아요 !
그래서, 하나의 페이지(URL)와 관련된 기능임에도 불구하고 메서드에 따라 컨트롤러가 분리되어 있었구요.

어노테이션 기반으로 바뀜에 따라 동일한 URL이더라도 메서드 기반으로 다른 동작을 하도록 처리하려고 했었는데...
이렇게 할거였으면 `login.jsp` 파일도 수정했어야겠네요 ㅎㅎ

기존 구조로 수정하였습니다 !

2023-09-19 06:06 UTC, cpot5620 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
> +        requestDispatcher.forward(request, response);
`forward`라는 이름에서, 다음 단계(?)에게 넘겨준다는 느낌적인 느낌이 드는 것 같아요.
만약, 다음 처리 순서의 dispatcher에게 넘겨준다면, 자신이 처리하지 못한 혹은 다음 dispatcher가 처리해야할 attribute들이 존재할 수 있기 때문 아닐까요 ㅎㅎ? 
그래서 `request.setAttribute()`를 수행하지 않을까..라는 예측을 해봅니다.

순수 뇌피셜이기 때문에, 땡칠이 공부해서 알려주세요. 리뷰어잖아요 히힛

2023-09-19 06:21 UTC, cpot5620 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
위 상황에서는 인스턴스를 생성할 때, 검증 등의 문제로 생성자 내부에서 오류가 발생하는 경우에는 복구 가능한 예외로 볼 수 있을 것 같아요.

해당 클래스 내부에서 어떤 예외를 던지고 있을지 몰라서, `RuntimeException`으로 다시 던져주었습니다 ㅎㅎ

2023-09-19 06:22 UTC, cpot5620 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    private boolean isValidateParameterType(Class<?>[] parameters) {
지금 저 영어 못한다고 무시하시는건가요 ?????????????????????????????????????????

장난이구, 해당 사항 반영했습니다 !

2023-09-19 06:25 UTC, cpot5620 commented on app/src/main/java/com/techcourse/support/web/adaptor/HandlerAdaptors.java
> +                .orElseThrow(() -> new NoSuchElementException("처리할 수 있는 핸들러가 존재하지 않습니다."));
오해를 불러일으켜 죄송합니다 ㅠㅠ

Handler 클래스에서 `orElseThrow()` 라인을 그대로 복사 붙여넣기 해버렸네요 .. 😢

예외 메세지의 `핸들러 -> 어댑터` 로 키워드 수정 하였습니다.

2023-09-19 06:48 UTC, cpot5620 commented on app/src/main/java/com/techcourse/support/web/adaptor/HandlerAdaptors.java
> +    }
해당 사항 반영했습니다 ~!

2023-09-19 06:50 UTC, cpot5620 commented on app/src/main/java/com/techcourse/support/web/adaptor/ManualHandlerAdaptor.java
> +    }
레벨 1 체스 미션 진행하면서, 읽었던 글이네요 ㅎㅎ

감사합니다 😄

2023-09-19 06:54 UTC, cpot5620 commented on app/src/main/java/com/techcourse/support/web/mapping/HandlerMappings.java
> +    }
왐마.... 이런 구조적인 설명은 제가 따로 준비해서, 설명드렸어야 하는 부분인데 죄송하고 고맙습니다 땡칠 !

이해하신 부분이 맞고, 기존 메서드에 대한 메서드 명을 신경쓰지 못했네요 !

`getController -> getHandler`로 변경하였습니다 !

2023-09-19 07:58 UTC, cpot5620 commented
안녕하세요 07 !! 
역시나 좋은 리뷰.. 정성적인 리뷰 감사합니다 😉 

> 저도 살짝 고민이 있었던 내용이었습니다~~ 전혀 이상하지 않고, 오히려 좋은 고민을 해보셨다고 생각해요.
제 생각부터 말씀드려보자면,
저는 현재 패키지 구조가 app과 mvc로 나뉜 것은 '프레임워크의 영역이냐, 아니면 개인(혹은 단체) 어플리케이션의 영역이냐?' 가 기준이라고 생각합니다.

HandlerMapping, HandlerExecution 인터페이스 등을 포함한, 'mvc' 패키지의 클래스들은 쥬니의 웹 프레임워크 사용자라면 꼭 필요한 공통적인 내용이고,

'app' 패키지에 있는 LoginController, ManualHandlerMapping 과 같은 클래스들은 쥬니 프레임워크 사용자라면 누구나 자신의 목적에 맞게 커스텀하고 싶은 영역이라고 생각해요.

이 기준에서 보면 AnnotationHandlerMapping은 어디에 있으면 좋을까요?

저는 제가 제공하는 프레임워크가 어노테이션 기반 프레임워크라고 생각해요.
이와 동시에, 제 프레임워크를 사용하고자 하는 사용자들이 정의한 핸들러와의 호환을 위해 interface도 제공하는거죠 ㅎㅎ
그래서 고민 끝에 내린 제 결론은, 어노테이션 기반 프레임워크이기 때문에 구현체까지 mvc 패키지에 두는 것이 옳다고 생각해요 ! 

땡칠도 저와 같으신가욥 !?@#$%^&*(?

2023-09-20 07:11 UTC, 0chil commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
> +        requestDispatcher.forward(request, response);
제가 예상한 바와 비슷하네요 ㅎㅎ
ㅋㅋㅋㅋ 다음 단계에서 공부해서 알려드릴게요

2023-09-20 07:14 UTC, 0chil commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    private boolean isValidateParameterType(Class<?>[] parameters) {
ㅋㅎㅎㅎ 👍

2023-09-20 07:27 UTC, 0chil commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
> 해당 클래스 내부에서 어떤 예외를 던지고 있을지 몰라서, RuntimeException으로 다시 던져주었습니다 ㅎㅎ

`throw new RuntimeException(e);` 를 수행하면
상위 try-catch에서 'e'의 type으로 예외가 잡히나요? 아니면 RuntimeException type으로 잡히나요?

정말 궁금합니다~!

2023-09-22 01:13 UTC, 0chil approved these changes
>저는 제가 제공하는 프레임워크가 어노테이션 기반 프레임워크라고 생각해요.
이와 동시에, 제 프레임워크를 사용하고자 하는 사용자들이 정의한 핸들러와의 호환을 위해 interface도 제공하는거죠 ㅎㅎ
그래서 고민 끝에 내린 제 결론은, 어노테이션 기반 프레임워크이기 때문에 구현체까지 mvc 패키지에 두는 것이 옳다고 생각해요 !
>
>땡칠도 저와 같으신가욥 !?@#$%^&*(?

![L9CyC_FTqT](https://github.com/woowacourse/jwp-dashboard-mvc/assets/39221443/423f102b-d345-4d78-ab8b-9a3a289dd447)
네 저도 동의합니다~~

제가 질문드렸던 내용도 도움이 많이 되었습니다 ㅎㅎ 감사합니다 쥬니~

미션 잘 구현하시고 요구사항도 잘 충족해주셔서 이만 머지하겠습니다!
수정하고 싶은 부분이 있다면 수정해주시고, 다음 단계에서 만나요~!

질문 하나 남겼는데 혹시 알고 계시다면 알려주세요!

2023-09-22 01:13 UTC, merged

2023-09-23 05:50 UTC, cpot5620 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
> 제가 생각하기에 IllegalStateException은 복구가 가능해보여서 여쭤봤어요.
그냥 예외처리해도 상관은 없지만, setAccessible(true) 로 바꾼 후 다시 시도해도 되지 않을까요?

오 !! 이런 방법도 있었네요 ㅎㅎ
해당 사항을 적용해볼까 ? 고민해보았는데, 우리가 만드는 프레임워크를 사용하기 위한 스펙(?)으로 보아도 될 것 같아요.
JPA를 사용할 때, 지켜야 하는 제약들 처럼요 ㅎㅎ

> throw new RuntimeException(e); 를 수행하면
상위 try-catch에서 'e'의 type으로 예외가 잡히나요? 아니면 RuntimeException type으로 잡히나요?

와.. 저는 당연하게 'e'의 타입으로 잡힐거라고 생각했어요.
그런데 테스트를 작성해보니까 RuntimeException으로 잡히네요.. 
이럴 경우, 예상치 못한 동작(예외 처리)을 할수도 있겠군요... ㅠ_ㅠ

2023-09-26 00:56 UTC, 0chil commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +        }
1. 'private 까지는 접근하지 않는다'라는 스펙을 만드는 거군요~
2. 다음에 예외처리할 때 참고하면 좋을 것 같습니다. 쥬니 덕분에 저도 새로 알게되었네요!