[MVC 구현하기 - 2단계] 오도(문민혁) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #490
Opened 2023-09-18 14:27 UTC by odo27

안녕하세요 연어!
1단계 때 리뷰 꼼꼼히 해주셔서 정말 감사합니다 👍
1단계 리뷰 반영한 부분까지 포함해서 이번 pr 남겼습니다
2단계도 잘 부탁드립니다 😊

2023-09-20 11:51 UTC, nuyh99 requested changes
오도 2단계도 반갑습니다ㅎㅎㅎ

`Front Controller` 패턴에 대해 깊게 학습하신 것 같아요.
전체적으로 객체지향적으로 잘 짜신 것 같습니다!
새로운 인사이트들이 있어서 배울 점이 많네요.

궁금한 점이나 개인적인 생각을 간단하게 코멘트로 남겼습니다.
반영은 자유롭게 해주시고 요청 주세요!
감사합니다😃

2023-09-20 11:51 UTC, nuyh99 commented on app/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.10.0'
ㅋㅋㅋㅋㅋ저도 추가할까 고민만 했었네요

2023-09-20 11:51 UTC, nuyh99 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.render(request, response);
`HandlerMapping`, `HandlerAdapter` 두 인터페이스를 가지고 얼마든지 확장할 수 있는 구조가 됐군요!

사실 어댑터 패턴이 아니라 그냥 `ModelAndView`를 리턴하는 `Handler`라는 인터페이스를 구현하게끔 해도 되지 않나요??
```java
Handler handler = handlerMappings.getHandler(request);
ModelAndView modelAndView = handler.handle(request, response);
modelAndView.render(request, response);
```
이런 식으로요!

스프링 프레임워크는 왜 어댑터 패턴을 사용했을까요??

2023-09-20 11:51 UTC, nuyh99 commented on app/src/test/java/com/techcourse/support/mvc/HandlerAdaptersTest.java
> +    }
메서드명이 `ManualHandlerAdapter`로부터 `HandlerAdapter`를  얻는다는 의미로 해석이 됩니다!

실질적인 테스트는 `request`로 `getHandler()`를 했을 때, 해당하는 어댑터가 `ManualHandlerAdapter` 타입인지 검증하는 것 같아요.

메서드명이나 테스트 로직 내부가 처음 봤을 때 한 눈에 의미 파악이 조금 힘들었어요ㅠㅠ
BDD 스타일의 주석까지는 아니더라도 좀 더 쉽게 파악이 가능하면 좋겠습니다!

2023-09-20 11:51 UTC, nuyh99 commented on app/src/test/java/com/techcourse/support/mvc/HandlerMappingsTest.java
> +        HttpServletRequest request = mock(HttpServletRequest.class);
반복된 `mock` 객체 생성 부분을 뽑아낼 수 있을 것 같아요!

2023-09-20 11:51 UTC, nuyh99 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    private List<Method> getAnnotatedMethods(Class<?> clazz) {
시그니처만 봤을 때는 어노테이션이 존재하는 메서드를 다 가져오는 것 같아요.
실제로는 `RequestMapping`만 취급하는데 말이죠!

세부 구현 사항이라고 생각하셔서 은닉하신 걸까요??

2023-09-20 11:51 UTC, nuyh99 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
>      }
`Map#containsKey`도 좋을 것 같네요!

2023-09-20 11:51 UTC, nuyh99 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
>      private final String viewName;
필드와 상수는 분리하면 좋을 것 같습니다!

2023-09-20 11:51 UTC, nuyh99 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java
> +
`View`의 구현체 중 하나인 `JspView`의 생성 책임도 `ModelAndView`에 할당하신 것 같군요!

여러 `View`가 추가된다면, 해당 부분들도 모두 여기에 추가하실 예정이신가요?
만약 `JspView`의 생성만 추가하신 것이라면 어떤 기준인지 궁금합니다.

추상적인 `View`에 의존하는 `ModelAndView`가 구현체에도 의존하는 것이 단점이 많다고 생각해서요!

2023-09-21 01:46 UTC, odo27 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.render(request, response);
다양한 라이브러리와 서비스를 통합하고 다양한 환경에서 동작할 수 있도록 설계된 스프링의 특성 상 어떤 라이브러나 서비스가 특정 인터페이스를 지원하지 않을 때 어댑터 패턴이 큰 장점을 가질 것 같아요!

먼저 현재 저희가 미션에서 경험한 것이 좋은 예시가 될 것 같아요. 기존의 Controller 인터페이스를 구현한 Controller가 있는 상황에서 HandlerMapping 인터페이스의 getHandler 메서드에서 Handler 를 반환하게 한다면 Controller 를 반환하던 HandlerMapping들을 모두 Handler 로 바꿔야하지만 어댑터 패턴을 적용하면 getHandler 에서 무엇을 반환하든 어댑터에서 적절한 처리를 하게 설계할 수 있을 것 같아요!

2023-09-21 02:16 UTC, odo27 commented on app/src/test/java/com/techcourse/support/mvc/HandlerAdaptersTest.java
> +    }
메서드명도 개선했고 given, when, then 주석도 활용해봤습니다 👍

2023-09-21 02:32 UTC, odo27 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    private List<Method> getAnnotatedMethods(Class<?> clazz) {
오 그렇네요! 파라미터로 Annotation을 받도록 변경해봤습니다 👍

2023-09-21 02:38 UTC, odo27 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java
> +
완전 동의합니다!

2023-09-21 02:40 UTC, odo27 commented
안녕하세요 연어!
연어의 꼼꼼한 리뷰 덕에 코드를 많이 개선할 수 있었습니다 👍👍
감사합니다 😊

2023-09-22 05:33 UTC, nuyh99 approved these changes
안녕하세요 오도!
바쁜 와중 미션도 빠르게 구현해주셨군요.

사실 처음 제출 때도 충분히 잘하셔서 리뷰가 도움이 됐을 지 모르겠네요ㅠ
DI 학습 테스트도 벌써 하셨군요ㅋㅋㅋㅋ
저도 열정 배워가겠습니다.

3단계에서 봐용~

2023-09-22 05:34 UTC, merged