[MVC 구현하기 2단계] 그레이(김동욱) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #495
Opened 2023-09-18 16:22 UTC by Kim0914

안녕하세요 아벨 !

미션과 팀 프로젝트를 병행하느라 너무 고생많으십니다 ㅎㅎ

저도 팀 프로젝트를 함께 진행한다고 2단계 미션 구현이 조금 늦어졌네요 😅

1단계에서 해주신 피드백은 적용했습니다 😀

이번 2단계에서는 기존에 존재하는 컨트롤러는 건드리지 않고 `HandlerMapping`을 추상화시켜 어노테이션과 기존 컨트롤러 모두 호환되도록 구현해보았습니다.

요청의 흐름을 간단하게 요약하면 다음과 같습니다.

1. 요청을 처리하기 위해 dispatcherServlet의 `service` 메서드 호출
2. dispatcherServlet이 가지고 있는 `HanlerMapping`을 순회하며 요청을 처리할 수 있는 핸들러 찾기
3. dispatcherServlet이 가지고 있는 `HandlerAdapter`를 순회하며 해당 핸들러의 동작을 처리할 수 있는 어댑터 찾기
4. `HandlerAdapter`에서 컨트롤러의 동작을 실행
5. view 반환

이번 리뷰도 잘 부탁드립니다 🙇🏻

2023-09-20 12:40 UTC, tjdtls690 requested changes
그레이! 코드를 굉장히 깔끔하게 잘 짜셔서 피드백 할 내용이 별로 없었던 것 같습니다. 몇 가지 피드백과 질문을 남겼는데 이에 대한 부분들만 소통이 완료되면 바로 머지하도록 할게요 :)

2023-09-20 12:40 UTC, tjdtls690 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingAdapter.java
> +public class AnnotationHandlerMappingAdapter implements HandlerAdapter {
Mapping과 Adapter의 역할은 다르다고 생각해서 클래스의 이름을 AnnotationHandlerMappingAdapter -> AnnotationHandlerAdapter 이렇게 바꿔보는 것은 어떨까요??

2023-09-20 12:40 UTC, tjdtls690 commented on app/src/main/java/com/techcourse/controller/NotFoundController.java
> +    public String execute(HttpServletRequest req, HttpServletResponse res) {
404 페이지 컨트롤러를 추가해서 500 에러 페이지가 안뜨도록 구현한 것이 정말 좋네요 :)

2023-09-20 12:40 UTC, tjdtls690 commented on app/src/main/java/com/techcourse/adapter/ControllerHandlerMappingAdapter.java
> +public class ControllerHandlerMappingAdapter implements HandlerAdapter {
여기도 마찬가지로 ControllerHandlerAdapter로 바꾸는 것이 어떨까요

2023-09-20 12:40 UTC, tjdtls690 commented on mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingAdapterTest.java
> +                TestController.class.getMethod("findUserId", HttpServletRequest.class, HttpServletResponse.class));
사소하지만

```suggestion
        HandlerExecution handlerExecution = new HandlerExecution(
                new TestController(),
                TestController.class.getMethod("findUserId", HttpServletRequest.class, HttpServletResponse.class)
        );
```

전 개인적으로 이렇게 개행을 하는 것이 좀 더 가독성이 좋아보이는데 어떻게 생각하시는지 궁금합니다!

2023-09-20 12:40 UTC, tjdtls690 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +public class AnnotationHandlerMapping implements HandlerMapping {
이건 구조적인 질문입니다. 어노테이션 기반 Mapping과 Adapter는 mvc 모듈에 있고 Controller 인터페이스 기반 Mapping과 Adapter는 app 모듈에 두셨는데 이렇게 위치시킨 이유가 무엇인지 궁금합니다 :)

2023-09-20 12:40 UTC, tjdtls690 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private final List<HandlerAdapter> handlerAdapters = new ArrayList<>();
Mappings와 Adapters를 각각 일급 콜렉션으로 포장해서 DispatcherServlet의 코드를 더 분리해볼 수 있을 것 같은데 어떻게 생각하시는지 의견이 궁금합니다!

2023-09-22 05:24 UTC, Kim0914 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingAdapter.java
> +public class AnnotationHandlerMappingAdapter implements HandlerAdapter {
좋네요 ㅎㅎ 네이밍이 중의적인 느낌이 드네요 !

반영하겠습니다 :)

2023-09-22 05:27 UTC, Kim0914 commented on mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingAdapterTest.java
> +                TestController.class.getMethod("findUserId", HttpServletRequest.class, HttpServletResponse.class));
좋네요 ㅎㅎ 이런 소소한 부분 꼼꼼하게 봐주셔서 너무 감사합니다 !

2023-09-22 05:29 UTC, Kim0914 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private final List<HandlerAdapter> handlerAdapters = new ArrayList<>();
좋습니다 ㅎㅎ

레벨 1때 배웠던 일급컬렉션을 잊고 있었네요 😭

2023-09-22 06:17 UTC, Kim0914 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +public class AnnotationHandlerMapping implements HandlerMapping {
우선 패키지 의존 방향을 단방향을 유지하는데 초점을 두었습니다.

mvc 모듈을 프레임워크 기반 도구라고 생각하고 app 모듈은 프레임 워크 도구를 이용한 애플리케이션이라고 생각했습니다.

어디까지를 프레임워크로 볼 것이냐의 차이라고 생각하는데요 !

요약하면 아래와 같은 기준으로 설정했다고 할 수 있을 것 같아요 :)

1. 의존성 문제가 발생하지 않는지 
2. 프레임워크의 범위를 어디까지 설정할 것인지

2023-09-22 06:27 UTC, Kim0914 commented
안녕하세요 아벨 !

꼼꼼한 리뷰 감사합니다 :)
리뷰 남겨주신 내용 반영해보았습니다.

추가적으로 현재 dispatcherServlet에 대한 테스트가 부족합니다.
DispatcherServlet을 어떤 방식으로 테스트할지 고민이 되네요.. (아직도 명확한 방법을 못찾았습니다..)

제가 고민했던 부분은 HttpServletRequest, HttpServletResponse 등과 같이 Http와 관련된 객체들을 모두 mock()으로 만들고 모킹을 한 후 테스트를 진행하니, 과연 이 테스트가 의미있는 테스트인지 의문이 들더라구요 ! (성공할 수 밖에 없도록 모킹을 했기 때문이라는 생각이 들었어요)

아벨은 어떤 방식으로 테스트를 진행했는지 궁금합니다 !

3단계 제출때는 해당 테스트를 추가해서 요청드릴게요 ㅎㅎ

2023-09-23 04:38 UTC, tjdtls690 approved these changes
역시 잘 반영해주셨군요 그레이!

사실 저도 DispatcherServlet 테스트는 구현하지 않았습니다. 하지만 전 개인적으론 mock을 통해 테스트를 하는 것에는 충분히 의의가 있다고 생각하고 있습니다.

mock을 통해 모든 협력 객체를 격리시키며 테스트를 하는 것이지만, 해당 메서드에 한해서는 내부의 동작이 의도대로 잘 동작하는지에 대한 테스트는 되고 있다고 생각하기 때문입니다 :)

그래서 결론은 수월하게 DispatcherServlet를 테스트하고 싶은 목적이라면, 전 개인적으론 mock을 써서 테스트하는 것도 충분히 의미가 있다고 생각합니다.

이만 머지하겠습니다! :)

2023-09-23 04:39 UTC, merged