[MVC 구현하기 - 2단계] 디노(신종화) 미션 제출합니다
woowacourse/jwp-dashboard-mvc pull request #496
Opened 2023-09-18 17:48 UTC by jjongwa

안녕하세요 그레이! 디노입니다~🦕

step2 제출이 생각보다 늦었네요.. 사실 2단계 구현의 범위가 어디까지인지도 모호해 우선 Mapping과 Adapter를 인터페이스로 추상화 하여 Manual과 annotation 모두 적용 가능하도록 하는 정도까지 완료했습니다!

새로 생성한 클래스들의 패키지 위치를 app으로 해야 할 지 mvc로 해야 하는지 잘 모르겠지만 우선 app이 legacy이고 mvc가 새로 작업하는 부분이라고 생각해 우선 mvc 내에 위치시켰습니다. 클래스의 위치에 대해 그레이의 의견 듣고 싶어요!

테스트도 최대한 작성해 보려 했는데, DispatcherSevlet은 어떻게 테스트 해야할지 아직 감이 오질 않네요..
조금 더 생각해 보고 이후에 추가해 보겠습니다..

부족한 부분이 정말정말 많을텐데 가감 없이 코멘트 남겨 주시면 감사하겠습니다!!🙇

2023-09-20 04:27 UTC, Kim0914 requested changes
안녕하세요 디노, 그레이입니다 !

2단계 미션도 구현 잘 해주셨네요 👏
객체를 적절하게 잘 분리해주셔서 코드 읽기가 너무 편했습니다 ㅎㅎ
궁금한 점과 생각해볼만한 부분 코멘트로 남겼어요 !

2023-09-20 04:27 UTC, Kim0914 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            final Controller controller = (Controller) findHandler(request);
`AnnotationHandlerMapping`은 `HandlerExcution`을 반환하고 있고, `ManualHandlerMapping`은 `Controller`를 반환하고 있는 것 같습니다 !!

여기서 Controller로 타입을 변환시킬 경우 발생할 수 있는 문제가 없을까요?!

2023-09-20 04:27 UTC, Kim0914 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            final ModelAndView modelAndView = adapter.handle(controller, request, response);
adapter에서 첫번째 파라미터로 Object를 받도록 잘 설계해주셔서 위에서 컨트롤러로 타입을 변환하지 않아도 될 것 같다는 생각이 들어요 😄

디노가 의도하신 부분이 있다면 말씀해주세요 !!

2023-09-20 04:27 UTC, Kim0914 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapters.java
> +                .orElse(null);
구구가 강의에서 null 반환하는 것을 지양하라고 했던 것 같아요 :)

null을 반환해서 외부에서 처리해도 괜찮지만 다른 방법도 고민해보시면 좋을 것 같아요 !

2023-09-20 04:27 UTC, Kim0914 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java
> +    private final Object object;
Object를 필드로 갖도록 해주셨네요 👍👍

2023-09-20 04:27 UTC, Kim0914 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        final String viewName = modelAndView.getViewName();
저의 개인적인 생각입니다 !

현재 각각의 adapter에서 적절한 `ModelAndView`를 만들어 반환하고 있습니다 !
`ModelAndView` 객체 내부에 `View` 객체가 있으므로 View 객체에게 render하는 책임을 부여할 수도 있을 것 같습니다 ㅎㅎ

구구가 남겨주신 힌트일 수도 있는데 View 구현체에 가면 render 메서드가 있고 `todo`가 있더라구요 !

2023-09-20 04:27 UTC, Kim0914 commented on mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapterTest.java
> +class AnnotationHandlerAdapterTest {
디노가 말씀해주신 DispatcherServlet 테스트에 대한 의견을 여기에 남겨둘게요 !

저도 DispatcherServlet을 어떤 방식으로 테스트할지 고민이 많았어요 ㅎㅎ (아직도 명확한 방법을 못찾았습니다..)

제가 고민했던 부분은 `HttpServletRequest`, `HttpServletResponse` 등과 같이 Http와 관련된 객체들을 모두 mock()으로 만들고 모킹을 한 후 테스트를 진행하니, 과연 이 테스트가 의미있는 테스트인지 의문이 들더라구요 ! (성공할 수 밖에 없도록 모킹을 했기 때문이라는 생각이 들었어요)

만약 DispatcherServlet을 테스트하는 목적이 의도한 대로 메서드들이 호출되는지 확인하기 위함이라고 하면 mock을 이용해서 테스트를 진행해도 괜찮지 않을까 라는 생각이 들어요 !

디노가 고민하고 있는 부분은 어떤 부분인지 궁금하네요 🤓

2023-09-20 04:27 UTC, Kim0914 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +import webmvc.org.springframework.web.servlet.mvc.tobe.HandlerMapping;
클래스 위치는 저도 디노와 동일하게 생각하고 있습니다 !

`Controller`는 프레임워크에 존재하기 때문에 그와 관련된 `Manual..Mapping`등 은 app 패키지에 두었고 나머지는 mvc 패키지에 두었습니다.

DispatcherServlet 패키지 위치에 대한 디노의 생각도 궁금하네요 ㅎㅎ

2023-09-20 16:17 UTC, jjongwa commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            final Controller controller = (Controller) findHandler(request);
아이구 Object로 주고받고 할 수 있게 설계하고 작성했는데 왜 이랬을까요..
변경했습니다! [efactor: 변수 선언 타입 및 null 처리 방식 변경](https://github.com/woowacourse/jwp-dashboard-mvc/pull/496/commits/20f17499af0364e3e79091c263c3e35ea8c7e578)

2023-09-20 16:18 UTC, jjongwa commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            final ModelAndView modelAndView = adapter.handle(controller, request, response);
위 답변과 같이 Object로 변경했습니다🥲

2023-09-20 16:20 UTC, jjongwa commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapters.java
> +                .orElse(null);
orElseThrow로 ServletException을 반환하게 바꿨습니다! https://github.com/woowacourse/jwp-dashboard-mvc/pull/496/commits/20f17499af0364e3e79091c263c3e35ea8c7e578

2023-09-20 16:21 UTC, jjongwa commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        final String viewName = modelAndView.getViewName();
아차차 그러네요..
해당 로직 그대로 render 메서드로 옮겼습니다! https://github.com/woowacourse/jwp-dashboard-mvc/pull/496/commits/02f12c15d4dd5c8097f37729505963f9cf7790bf

2023-09-20 16:25 UTC, jjongwa commented on mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapterTest.java
> +class AnnotationHandlerAdapterTest {
(mock 테스트를 선호하지 않는 입장에서) 저도 그레이와 같은 생각입니다!
하지만 복잡한 메서드 내에서의 분기 처리 또는 함수의 호출 여부를 파악하는 정도를 위해 테스트를 작성한다면 
그으래도 없는것보단 낫다? 라는 느낌이 들기도 하네요..

이 부분은 조금 더 생각해 보고 다시 의견 나눠 보고 싶네요ㅎㅎ 조금 더 공부해 보겠습니다.!

2023-09-20 16:31 UTC, jjongwa commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +import webmvc.org.springframework.web.servlet.mvc.tobe.HandlerMapping;
오늘 수업에서도 언급했지만 결국 
`어디까지를 프레임워크로 보느냐`와 
`의존성 문제가 발생하지 않는가`

이 두 가지를 최우선 기준으로 잡고 분리해야 하겠다는 생각이 들었습니다.
해당 부분도 조금 더 공부가 필요하겠지만 현재는 패키지를 이동해야 할 만한 클래스가 보이지 않는것 같다는 결론입니다.
스텝 3 까지 진행해 보면 생각이 달라질수도 있겠죠..? 그럼 그 때 다시 제 생각 코멘트로 첨부하겠습니다..!ㅎㅎ

2023-09-20 16:36 UTC, jjongwa commented
안녕하세요 그레이!

꼼꼼한 리뷰 정말정말 감사합니다ㅎㅎ
코멘트 남긴 부분에 대한 리팩터링과 답글 남겼어요!

리팩터링 하던 도중 `DispatcherServletInitializer`라는 클래스를 발견했는데요.
쓰이는 곳이 없어서 이걸 어떻게 활용해야 하는지, 스텝 3에서 필요한 클래스인지 고민해 봤는데
아직 어디에 써야 할 지 해답을 찾지 못했습니다.. 혹시 그레이는 사용하셨는지 궁금하네요..ㅎㅎ

나머지 리뷰도 잘 부탁드립니다.!🙇🙇

2023-09-21 10:36 UTC, Kim0914 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    );
add 동작을 초기화하는 과정에 포함될 수 있을까에 대한 관점의 차이인 것 같은데요..!!

저는 `dispatcherServlet`을 사용할 준비가 되도록 초기화한다는 의미에 add가 포함된다고 생각해서 괜찮은 것 같습니다 ㅎㅎ

2023-09-21 10:37 UTC, Kim0914 commented on mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapterTest.java
> +class AnnotationHandlerAdapterTest {
좋은 아이디어 있으시면 꼭 알려주십쇼 ㅎㅎ

2023-09-21 10:38 UTC, Kim0914 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +import webmvc.org.springframework.web.servlet.mvc.tobe.HandlerMapping;
좋아요 ! 다음 단계도 기대하겠씁니다 :)

2023-09-21 10:39 UTC, Kim0914 commented
`DispatcherServletInitializer`은 저도 아직 사용하고 있지 않아요 !

퍼즐 맞춰가는 느낌이라고 할까요..?!
3단계를 해보면 알 수도 있지 않을까 생각합니다 ㅎㅎ

2023-09-21 10:41 UTC, Kim0914 approved these changes
고생많으셨습니다 디노 ㅎㅎ
반영해주신부분 모두 확인했어요 !
다음 단계도 기대하고 있을게요 😙

2023-09-21 10:42 UTC, merged