[MVC 구현하기 - 2단계] 웨지(성시형) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #50
Opened 2021-09-11 15:36 UTC by sihyung92

안녕하세요 현구막~~
1단계 때 다양한 질문과 꼼꼼한 리뷰를 해준 현구막 덕에 즐거웠습니다!
1단계 때 당부한 꼭꼭꼭 대답은 
https://github.com/woowacourse/jwp-dashboard-mvc/pull/8#discussion_r706569127
https://github.com/woowacourse/jwp-dashboard-mvc/pull/8#discussion_r706567735
두 개의 코멘트에 달아놓았습니다. 

2단계로 미룬 반영을 마치고, 추가적으로 코기의 코드를 리뷰하다 재밌어 보였던 동적 파라미터 바인딩을 구현해보았습니다!
그리고 스트릿 우먼 파이트 보세요. 너무 재밌어.. 재미의 덫에 빠져버렸습니다.

리뷰 잘 부탁드립니다!

2021-09-11 23:25 UTC, ecsimsw commented
```
이름은.. ParameterResolver라고 지었습니다. 왜 ArgumentResolver가 아니냐구요?
제 마음입니다.
```

이 부분 인상 깊네요!!! PR 잘봤습니다.
다만 왜 이름이 ArgumentResolver가 아니고 ParameterResolver인가요?

이 부분 확인 부탁드릴게요~

2021-09-11 23:33 UTC, sihyung92 commented
@ecsimsw 
https://stackoverflow.com/questions/1788923/parameter-vs-argument
parameter는 메소드 시그니처에 표현되는 인자, argument는 메소드를 호출할 때 전달하는 인자입니다. 메소드 시그니처에 표현한대로 받아주는 resolver이므로, parameterResolver가 맞지않나? 생각했습니다.
거짓말입니다. 그냥 느낌가는대로 했습니다.

2021-09-12 03:15 UTC, Hyeon9mak requested changes
헬로우 웨지!? 코기가 리뷰를 하다 마셨네요. 남자가 칼을 뽑았으면 감자라도 썰어야지... 🔪 🥔 

이미 코드 수준과 완성도가 너무 높아 어쩌지 어쩌지 하다가
뭐라도 적고 체인지 리퀘스트를 보내봅니다!!! 
너무 빨리 Approve 드리면 재미 없잖아요?! 하하하하하하!!

1단계 피드백 중 반영되지 않은 몇 가지는 웨지의 취향으로 존중!! 😄 

---

> 아하! 전 두개의 클래스가 관계가 없다고 생각합니다 ^_^  
> 핸들러 어댑터의 역할은 컨트롤러 인터페이스를 DispactherServlet에서 사용할 수 있도록 변환하는 용도입니다.
> 매뉴얼 핸들러 맵핑은 핸들러 맵핑을 등록하는 역할입니다.
> 
> 핸들러 맵핑은 프레임워크를 사용하는 개발자의 영역입니다. 매핸맵이 앱 패키지에 드러나는 것이 맞다고 생각하지만, 컨핸어의 경우엔 사용하는 개발자가 등록한 컨트롤러가 프레임워크에서 어떤 식으로 동작하는지 알 필요가 없다고 생각합니다. 캡슐화와도 맞닿아있네용 ^_^;   
> 그러므로 컨핸어는 컨트롤러 인터페이스와 동일 패키지에, 메핸맵은 앱 쪽 환경설정 쪽 패키지에 있는 게 맞지 않을지요~

오!! 웨지는 DispatcherServlet이 커스텀 핸들러의 동작방식을 이해하고 거기에 맞춰 어댑터를 준비해서 사용한다는거 같아요! 제가 제대로 이해한게 맞을까요??!?

저는 어댑터가 핸들러 맵핑과 함께한다고 생각했어요. 개발자가 커스텀 핸들러와 맵핑을 만들었을 때 DispatcherServlet이 그 커스텀 핸들러의 동작방식을 알 필요가 없다고 생각했습니다. 그래서 개발자가 커스텀 핸들러 어댑터까지 준비해줘야한다고 생각했어요!!

'누구를 위한 어댑터인가?' 관점 차이일까요?!?!
(혹은 제가 DispatcherServlet을 잘 몰라 이런 생각을 했을지도 😭 ..)

---

코드 많이 뜯어보면서 배우겠습니다~ ❤️ 
우주최강감자 웨지 화이팅!!!! 👍 👍 👍

2021-09-12 04:11 UTC, sihyung92 commented on app/src/main/java/com/techcourse/controller/TestController.java
>          final ModelAndView modelAndView = new ModelAndView(new JspView(viewNameWithoutExtension + JSP_EXTENSION));
꼼제!!
사실 파라미터 리졸버 테스트 하느라고 ㅎ

2021-09-12 04:18 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>      }
음 마찬가지 의미입니다! 어떤 생성자에서 만들더라도 기존 자료구조가 있고, 몇몇가지 parameterResolver를 세팅해놓는 형태로 구성하고 싶었습니다. 기본 생성자로 만들거나 모든 인자를 주는 생성자로 만들거나 공통 로직으로 수행하고 싶게  하고 싶었기 때문에 인스턴스 초기화블럭을 사용했습니다. 

주생성자 / 부생성자나 정적 팩토리메소드 를 활용해도 무관하다고 생각하지만, 생성자에 할당 이상의 복잡한 로직이 있으니 불편하더라구요 
메소드로 추출해서 깔끔하게 만들면 주생성자/부생성자도 좋은거 같아요!

요즘 of 같은 정적팩토리 메소드는 손이 안 가네요 ^^; 요새는 new 가 더 명확하다고 느껴집니다

2021-09-12 04:25 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
>      }
'_' 생각 안 해본 주제긴한데, 극단적으로 말하자면 mvc의 모듈 내에선 모든 객체가 HttpServletRequest, HttpServletResponse를 알아도 된다고 생각합니다. 왜냐면 J2EE 규격에서 정해준 규격이잖아여? List 인터페이스는 변치않을 것이라 믿고 모든 객체에서 받아다 쓰듯이, `썹리`들은 `잘 변하지 않는 것` 에 해당한다고 생각합니다. HttpServletRequest, HttpServletResponse와 프로젝트의 결합도가 어마어마하지만 추상화된 것(인터페이스)이므로 비교적 변경 여파로부터 자유롭구요

2021-09-12 04:26 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
>      }
그래서 HttpServletRequest, HttpServletResponse에서 값을 꺼내 쓸 일 있으면 고민 안 하고 HttpServletRequest, HttpServletResponse 객체 자체를 주는 식으로 코딩했던거 같습니다ㅋ_ㅋ

2021-09-12 04:28 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
>      }
없습니다!! 걍 메소드 필요했는데 눈앞에 보이는 거에 getter를 뚫어주는 안일한 코딩입니다!

2021-09-12 04:29 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
>      }
아 ㅋㅋ 속았네 이 메소드 reflection api의 메소드입니다! httpMethod아닙니다!

2021-09-12 04:34 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/ParameterResolver.java
> +}
?_? 파라미터는  HandlerExcution 메소드의 파라미터고, 이 정보는 request에서 추출할 수 없습니다. request를 통해 파라미터를 알아내려면  ParameterResolver에서 핸들러맵핑을 참조하는 구조로 코딩해야 할텐데 이 방향을 말씀하시는게 맞을까요?

2021-09-12 04:34 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
>      }
아? 너무 구체적으로 틀렸네 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 죄송합니당..

2021-09-12 04:34 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/ParameterResolverExecutor.java
> +
정멤클활

2021-09-12 04:35 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/handler/HandlerAdapters.java
> +    }
Agree

2021-09-12 04:35 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/controller/tobe/ParameterResolver.java
> +}
https://github.com/woowacourse/jwp-dashboard-mvc/pull/50#discussion_r706727687

이거랑 똑같이 오해했습니다 ㅎㅎ; 😇

2021-09-12 04:35 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/handler/HandlerMappings.java
> +    }
Agree

2021-09-12 04:48 UTC, sihyung92 commented
> '누구를 위한 어댑터인가?' 관점 차이일까요?!?!
(혹은 제가 DispatcherServlet을 잘 몰라 이런 생각을 했을지도 😭 ..)

오홍 넴 신선하네요 전 `컨트롤러 인터페이스를 사용하거나, annotation Mapping을 활용해라` 그리고 `핸들러 맵핑은 ModelAndView를 반환해라` 이 부분들이 제 서버의 기본 골조라고 봤습니다. 컨트롤러 인터페이스같은 핸들러 오브젝트도 유저가 자유롭게 코딩하여 활용할 수 있다면, 어댑터도 직접 구현하는게 맞다고 보겠지만요~~
이 프레임워크에서 지원하고자 하는게 `편한 mvc 구현` 이고, 제가 정해준 두 가지 방식(인터페이스 구현, 어노테이션 붙이기) 중에 골라써야하기때문에, `어댑터`는 두 가지 중 무얼 골라쓰든 `ModelAndView를 리턴하는 컨트롤러` 역할을 할 수 있도록 도와주는 도우미 역할이라고 봤습니다.

좋은 관점 감사합니당~~

2021-09-12 11:43 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>      }
저도 정적 팩터리 메서드보다 new 생성자를 더 선호하는 편인데, '객체가 생성되는 순간부터 책임을 떠맡게 하고 싶다!' 라는 생각 때문에 생성자 쪽에 이런저런 로직을 넣어주다보니 저도 모르게 정적 팩터리 메서드를 자주 사용하게 되네요. 😭 

저는 인스턴스 초기화가 '여러 생성자에서 사용하는 중복로직을 암시해준다'고 생각해서 '단일 생성자에서 써도 괜찮나?' 라는 걱정도 드네용. 하지만 어디까지나 저의 취향일뿐, 웨지 의견 OK임다!!!

2021-09-12 11:58 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
>      }
결합도를 낮추려는 이유가 유지보수성 향상을 위해서인데, 결합도가 어마어마한 프로젝트에서 변경 여파로부터 자유롭다 하시는게 어떤 의미인지 헷갈리네용 😵  HTTP 버전 업데이트에 수준의 변경 여파를 말씀하시는 걸까요?!
만일 프로토콜 자체를 교체하게 된다면 mvc 모듈의 모든 객체를 관리포인트로 보아야할 것 같아요!!!
이 부분은 웨지의 이야기가 더 들어보고 싶어요!!

2021-09-12 12:06 UTC, Hyeon9mak commented
주말 밤은 역시 웨지 포테이토!! 2단계 마지막 리뷰 남김니당!!

- [인스턴스 초기화 블럭](https://github.com/woowacourse/jwp-dashboard-mvc/pull/50#discussion_r706824594)
- [HttpServletRequest 결합도](https://github.com/woowacourse/jwp-dashboard-mvc/pull/50#discussion_r706826400)

`HttpServletRequest` 결합도를 이야기해주신 것에 궁금한게 생겨서 추가 의견 부탁드리고 싶어요!
귀찮으시죠? 걱정마세요, 저는 괜찮아요!!

웨지 화이팅!

2021-09-12 12:25 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
>      }
넹! RFC의 변경 여파 정도 일겁니다. 그런데 HttpServletRequest 인터페이스가 변할 상황이라면, Http 프로토콜이 폐기되는 상황정도라고 생각합니다! 왜냐하면 Http2.0이나 QUIC도 HTTP 시멘틱(상태코드, method 등)을 공유한다고 알고 있는데, 그렇다면 HttpServletRequest 인터페이스를 변경시킬 정도는 아니라고 생각합니다. 👀 
표현을 `프로젝트의 결합도가 어마어마하지만` 이라고 잘 못 한거 같은데, 결합도를 줄이기 위한 패턴 중 하나가 DIP(의존역전)이고, 추상화 된 것에 구체적인 것들이 의존하게 했으니 지금도 충분히 유연한 코드라고 생각합니다!(2.0, QUIC도 커버 가능한 사례에서 볼 수 있듯이) 

approve 주셈

2021-09-12 12:27 UTC, sihyung92 reviewed
코멘트 남겼습니다~~ 확인해주셔요!

2021-09-12 12:27 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>      }
아 기본 생성자 있는 줄? 현재는 필요없어서 만들지 않겠지만, 기본 생성자가 생겼을 때에도 적용되야하는 초기화 블록(중복로직)이므로 그대로 두겠습니다람쥐

2021-09-12 12:54 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
>      }
슬슬 드려볼까.. 더 괴롭힐까.. 😄

2021-09-12 13:10 UTC, Hyeon9mak approved these changes
더 많은 의견 물어보고 더 많이 귀찮게 하고 싶은데,
2단계 첫 제출부터 이미 잘 짜여진 코드에 의도도 명확해서 괴롭히기 어렵네요...

이게 아닌데... 내가 상상한건 제발 Approve 해달라고 하는건데...

우선은 Approve 드리겠습니다... 3단계에서 더 강해져서 돌아올 것임 👿

2021-09-12 13:10 UTC, merged