[MVC 구현 2단계] 리오(오영택) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #532
Opened 2023-09-22 07:40 UTC by Jaeyoung22

안녕하세요 콩하나! 리뷰 요청이 많이 늦어져서 죄송합니다... 
구조에 대해서 오프라인으로 설명 드릴게요!
잘 부탁드립니다~

2023-09-23 14:50 UTC, kong-hana01 approved these changes
안녕하세요 리오! 콩하나입니다 ㅎㅎ
최대한 빨리 리뷰를 해드리려고 했는데, 오늘 하루종일 자다가 이제야 리뷰를 끝냈네요!

코드 확인했습니다!
직접 만나서 말씀해주신 구조 덕분에 더 수월하게 리뷰할 수 있었습니다!
구조도 듣고, 실제 코드도 확인해보니 이번 미션을 통해 리오가 어떤 부분을 집중하셨는지 느껴지더라고요!

패키지 구조와 의존성 분리 부분을 많이 신경쓰신 듯 했습니다!
덕분에 구조가 깔끔해져서 코드 이해가 빨라졌습니다!

몇 가지 질문과 제안 사항들을 남겨드렸습니다!
일단 미션에서 요구하는 사항들은 모두 해결하셨다고 느껴져서 바로 머지하도록 하곘습니다!
답변은 늦게 달아주셔도 좋아요~~

3번째 미션도 화이팅해보시죠!!

2023-09-23 14:50 UTC, kong-hana01 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +        HandlerExecution handler = handlerMappings.findHandler(request);
`handlerMappings`에서 `findHandler()` 반환 타입이 `HandlerExecution`으로 되게끔 구현하셨군요!

2023-09-23 14:50 UTC, kong-hana01 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +            move(mv, request, response);
덕분에 서블릿 코드에서는 분기처리를 하지 않아도 이렇게 간단하게 ModelAndView 객체를 받아올 수 있겠네요!

2023-09-23 14:50 UTC, kong-hana01 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/HandlerMappings.java
> +    private Set<HandlerMapping> mappings;
여러 핸들러 매핑을 가지고 있고, 이 객체를 통해서 Handler를 반환해주고 있군요!
핸들러 매핑 과정을 캡슐화해서 이 객체에게 위임해주고 있어서 `핸들러 매핑이라는 책임 분리`가 잘 이뤄진 것 같네요 ㅎㅎ

2023-09-23 14:50 UTC, kong-hana01 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/HandlerMappings.java
> +        mappings = new HashSet<>();
핸들러 매핑들을 여기에 등록을 해주고 있군요!

스프링 빈들을 생각해보니까 `@Order`라는 어노테이션이 있던 게 기억나네요!
빈들의 우선순위를 조정해서 의존성 주입을 해줄 수 있던 것으로 기억이 나는데요.
핸들러 매핑을 할 때에도 `한 요청에 대해 지원이 가능한 핸들러 매핑이 여러 개`가 있을 수 있어서 이 부분도 지원이 가능하게 하면 좋을 것 같아요!
findHandler 메소드에서 스트림을 돌며 findfFirst() 메소드를 호출해주고 있으니
`new LinkedHashSet()`을 사용해 핸들러 매핑 간의 순서(우선순위)를 보장해주는건 어떨까요?

2023-09-23 14:50 UTC, kong-hana01 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/InterfaceBasedHandlerMapping.java
> +    }
`initialize()` 메소드를 통해 `ForwardController`를 넣어주고 있군요.

위쪽에서 `addController()` 메소드를 통해서도 컨트롤러를 넣어줄 수 있는데,
`initialize()` 메소드를 통해서 ForwardController만 따로 넣어주고 있는 이유가 있으신가요?

현재 `InterfaceBasedHandlerMapping` 클래스는 `정적 메소드를 통해서 외부에서 컨트롤러를 추가`할 수 있도록 지원하고 있는데, 
객체를 생성한 뒤, initialize()를 따로 호출해야지 ForwardController를 컨트롤러를 추가해주고 있네요.

컨트롤러를 핸들러 매핑에 등록하는 지점이 두 개 이상이고, 방법(정적 메소드와 일반 메소드) 또한 혼용되고 있어서 사용하는 데 어려움이 있을 것 같아요!!

이를 한번 개선해보는건 어떨까요?
정적 메소드만 지원할 예정이시라면 생성자를 private 하게 막고, new ForwardController()를 외부에서 호출하게 해주시거나,
정적 메소드를 지원하지 않고, 다른 핸들러 매핑처럼 지원하실 예정이시라면 `리플렉션`을 활용해볼 수 있겠네요!

저라면 후자의 방법을 선택해볼 것 같아요.
핸들러 매핑 객체들 간에 `핸들러 등록 방법을 통일`한다면 추후에 핸들러 매핑이 여러 개로 늘어나더라도
이해하는데 큰 어려움 없이 쉽게 사용할 수 있을 것 같거든요!
하지만 핸들러 등록 방법이 다르다면 각 핸들러마다 등록 방법을 확인해보고 따로 관리해줘야하니 어려움도 있을 것 같아요.

2023-09-23 14:50 UTC, kong-hana01 commented on app/src/main/java/com/techcourse/Application.java
> +
그리고 main() 메소드에서 직접 핸들러를 등록해줄 필요도 없어보이고요!

이건 간단한 질문인데요.
메인 함수에서 핸들러를 등록해주기로 하신 이유가 있으실까요? ㅎㅎ
디스패처 서블릿 내에서 해당 핸들러들을 추가해주면 의존성이 양방향으로 일어나기 때문에 그러셨던 걸까요? ㅎㅎ

2023-09-23 14:50 UTC, kong-hana01 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/annotation/HandlerExecution.java
> -package webmvc.org.springframework.web.servlet.mvc.tobe;
asis 패키지나 tobe 패키지는 모두 없애셨군요 ㅎㅎ
저는 그대로인데,,, 저도 반영해봐야겠네요!

2023-09-23 14:50 UTC, kong-hana01 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/InterfaceBasedHandlerMapping.java
> +        }
`support() 메소드가 호출되지 않고, getHandler()`메소드만 따로 호출되더라도 이 부분 덕분에 안정성이 더 높아지겠네요!

2023-09-23 14:50 UTC, kong-hana01 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
> +        requestDispatcher.forward(request, response);
뷰를 띄워주는 로직을 서블릿에서 이 쪽으로 옮기셨군요! 👍

2023-09-23 14:50 UTC, kong-hana01 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +        modelAndView.getView().render(modelAndView.getModel(), request, response);
`modelAndView에 render라는 메소드`를 넣어주면 사용하는 측에서는 더 간단하게 써볼 수 있을 것 같네요!

```java
modelAndView.render(request, response);

// ModelAndView 클래스
public void render(HttpServletRequest request, HttpServletResponse response) {
    view.render(model, request, response);
}
```
이런 느낌으로다가요!

2023-09-23 14:50 UTC, kong-hana01 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +    private transient HandlerMappings handlerMappings;
transient 키워드를 붙여주신 이유가 있으실까요?

HttpServlet 클래스를 타고 가보니 상위 클래스에서 직렬화 인터페이스를 구현하고 있군요!
![image](https://github.com/woowacourse/jwp-dashboard-mvc/assets/79015120/27fe1654-3a69-4bfe-8d87-8800579e9321)
이 부분 때문에 해당 키워드를 추가해주고 계신건가요?

2023-09-23 14:50 UTC, kong-hana01 commented on app/src/main/java/com/techcourse/DispatcherServletInitializer.java
> -        registration.setLoadOnStartup(1);
`setLoadOnStartup()`는 무슨 메소드일까요? ㅎㅎ
이를 없애주신 특별한 이유가 있으실까요?

2023-09-23 14:51 UTC, kong-hana01 requested changes
안녕하세요 리오! 콩하나입니다 ㅎㅎ
최대한 빨리 리뷰를 해드리려고 했는데, 오늘 하루종일 자다가 이제야 리뷰를 끝냈네요!

코드 확인했습니다!
직접 만나서 말씀해주신 구조 덕분에 더 수월하게 리뷰할 수 있었습니다!
구조도 듣고, 실제 코드도 확인해보니 이번 미션을 통해 리오가 어떤 부분을 집중하셨는지 느껴지더라고요!

패키지 구조와 의존성 분리 부분을 많이 신경쓰신 듯 했습니다!
덕분에 구조가 깔끔해져서 코드 이해가 빨라졌습니다!

몇 가지 질문과 제안 사항들을 남겨드렸습니다!
일단 미션에서 요구하는 사항들은 모두 해결하셨다고 느껴져서 바로 머지하도록 하곘습니다!
답변은 늦게 달아주셔도 좋아요~~

3번째 미션도 화이팅해보시죠!!

2023-09-23 14:51 UTC, merged

2023-09-25 04:56 UTC, Jaeyoung22 commented on app/src/main/java/com/techcourse/DispatcherServletInitializer.java
> -        registration.setLoadOnStartup(1);
이게 왜 없어졌지?

2023-09-25 04:57 UTC, Jaeyoung22 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +    private transient HandlerMappings handlerMappings;
네! DispatcheServlet은 직렬화가 되지만 HandlerMappings는 그럴필요가 없다고 생각했어요 그래서 추가해주었습니다!

2023-09-25 04:58 UTC, Jaeyoung22 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +        modelAndView.getView().render(modelAndView.getModel(), request, response);
좋습니다! ModelAndView 객체 안으로 넣어볼게요!

2023-09-25 05:17 UTC, Jaeyoung22 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/HandlerMappings.java
> +        mappings = new HashSet<>();
한 요청에 대해 지원 가능한 핸들러 매핑이 여러개가 있을 수 있나요?? 혹시 확인해주실 수 있으실까요?

2023-09-25 05:27 UTC, Jaeyoung22 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/InterfaceBasedHandlerMapping.java
> +    }
앗 어쩐지 하나가 비는 느낌이었는데 저걸 안 뺐었네요...! 저 부분은 실수가 맞습니다ㅠㅠ

그런데 혹시 리플렉션을 어떻게 사용해야할까요?
저는 app 모듈에서 리플렉션을 사용하지 않는 걸로 이해를 해서, 추가적인 의존성을 설정 안했거든요..
mvc가 app을 의존하면 순환참조로 컴파일 자체가 안되더라구요..
mvc가 app을 의존하지 않게 하고 리플렉션으로 Controller의 구현체들을 불러올 수 있는 방법이 있나요?!

2023-09-25 05:55 UTC, Jaeyoung22 commented on app/src/main/java/com/techcourse/Application.java
> +
원래는 DispatcherInitializer가 mvc 모듈에 있었어가지고, 어쩔 수 없이 메인 함수에 있었는데요
지금은 app 모듈로 빼왔기 때문에 DispatcherInitializer 안에 있는 것이 더 맞네요! 감사합니다!