[MVC 구현하기 - 2단계] 로건(정다빈) 미션 제출합니다
woowacourse/jwp-dashboard-mvc pull request #542
Opened 2023-09-23 08:56 UTC by 70825

안녕하세요 지토!

<img src="https://github.com/woowacourse/jwp-dashboard-mvc/assets/79046106/f0a8cc98-08e4-4f36-b683-0c968769f95c" width="300" height="300">

일단 PR 보내는게 늦을 것 같다고 이야기를 했는데, 괜찮다고 해서 압도적 감사합니다

이번에 점진적인 리팩터링이라 최대한 기존 코드를 유지하는 상태에서 어떻게 코드를 만들어야할지 고민이 많이 들었습니다.
이전에 아래 리팩터링 관련 컨퍼런스 영상을 재밌게 봤었는데, 지토도 심심할 때 보면 좋을 것 같아요. 발표자 분들이 발표를 재밌게해서 재밌게 들었어요
- [당신도 할 수 있는 레거시 프로젝트 개선 이야기](https://youtu.be/pZYZAMToenE?si=NlTaukAGShBZf_px)
- [대규모 엔터프라이즈 시스템 개선 경험기 - 1부 (달리는 기차의 바퀴 갈아 끼우기)](https://youtu.be/UwAoUshVpgM?si=aHnUOmFue_GZlkUr)

사실 스프링 코드를 그대로 만드는 것도 고민을 했지만, 이번주에 너무 바빠 시간상 못만들어서 최소한의 코드만 변경하여 만들 수 있도록 바꿨습니다.

가장 최신의 세 개의 커밋이 어노테이션 기반으로 동작하도록 개선하는 코드들입니다.

감사합니다.

2023-09-23 11:37 UTC, apptie requested changes
안녕하세요, 로건! 
5차 데모데이 때문에 정신없는 와중에 미션까지 진행하시느라 정말 고생하셨습니다

소소하게 제 생각과 로건의 의도를 질문드리는 쪽으로 리뷰를 진행했습니다 
Request changes로 할 거기는 한데, 바쁘시거나 서비스에 집중하고 싶으시다면 리뷰는 굳이 반영하지 않으셔도 됩니다! 

다음 PR 요청 시 Approve 하도록 하겠습니다

2023-09-23 11:37 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerMappings = new ArrayList<>();
`init()`을 호출하지 않았을 경우에는 고려하지 않아도 괜찮은 것일까요?
`DispatcherServletInitializer`에서 호출하고는 있지만, 해당 클래스 내에서는 이를 강제하거나 검증하는 로직이 없어 NPE가 발생할 수도 있을 것 같습니다.
개인적으로는 해당 클래스 자체만으로 비정상적으로 종료되는 것을 막아야 한다고 생각하는데,  로건의 생각은 어떤가요?

2023-09-23 11:37 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private static final List<String> LEGACY_NAMES = List.of("/", "/login", "/login/view", "/logout");
레거시 컨트롤러와 어노테이션 기반 컨트롤러의 공존을 위해서 추가해주신 부분 같습니다.
그런데 어떤 요청을 어떤 컨트롤러로 처리할 수 있는지는 `HandlerMapping`의 관심사라는 생각이 듭니다.
51번째 줄, 56번째 줄과 같이 `DispatcherServlet`은 요청을 처리할 수 있는 컨트롤러를 전달받아서 실행만 하면 되지 않을까요?

2023-09-23 11:37 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.getView().render(modelAndView.getModel(), request, response);
DispatcherServlet이 viewName과 ModelAndView를 처리해야해서 분기가 생긴 것으로 보입니다.
이를 하나로 묶어서 분기를 없앨 수 있는 방법은 없을까요?

2023-09-23 11:37 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private Object[] basePackage;
해당 필드는 어노테이션 기반의 컨트롤러를 스캔할 때 패키지 위치를 지정한 것으로 보입니다.
이를 DispatcherServlet에서 관리하는게 자연스러울까요?
DispatcherServlet은 HandlerMapping이 찾아준 컨트롤러를 실행하는 관심사만 갖는 것이 자연스럽지 않을까요?
저는 어떠한 패키지를 스캔해야 하는지에 대한 정보는 AnnotationHandlerMapping에서 관리하는게 더 자연스러워 보이는데, 로건의 생각이 궁금합니다!

2023-09-23 11:37 UTC, apptie commented on app/src/main/java/com/techcourse/controller/RegisterController.java
> +    @RequestMapping(value = "/register", method = RequestMethod.POST)
테스트를 위해서 일부 컨트롤러만 어노테이션 기반으로 변경하신걸까요? 좋은데요? 👍

2023-09-23 11:37 UTC, apptie commented on app/src/main/java/com/techcourse/ManualHandlerMappingAdapter.java
> +            handlerExecutions.put(handlerKey, handlerExecution);
해당 클래스의 이름만으로는 레거시 컨트롤러에 관한 내용만 있을 것 같은데 살펴보니 아닌 것 같네요!
왜 `Map<HandlerKey, HandlerExecution> handlerExecutions`를 필드로 두고, 해당 `Map`에 값이 없는 경우 `put`을 해주었는지 궁금합니다!

2023-09-23 11:37 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            if (Objects.nonNull(handlerExecution)) {
`Objects.nonNull()`은 문서에서는 `This method exists to be used as a Predicate, filter(Objects::nonNull)`라고 표현하고 있는데, 직접 `null`을 비교하지 않고 해당 메서드를 사용하신 이유가 궁금합니다!

2023-09-23 13:18 UTC, 70825 reviewed
안녕하세요 지토!
고치려는 코멘트랑 제 이야기를 한 코멘트가 전부 pending이 되어서 일단 코멘트만 달아둘게요!
코드 변경할 예정이라 나중에 다시 요청보내면 그때 approve 고려하시면 될 듯 합니다!

2023-09-23 13:18 UTC, 70825 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private Object[] basePackage;
> DispatcherServlet은 HandlerMapping이 찾아준 컨트롤러를 실행하는 관심사만 갖는 것이 자연스럽지 않을까요?

동의합니다! 그러면 필드 저장없이 생성자에 있는 파라미터를 그대로 넘겨주면 될 것 같아요!

2023-09-23 13:18 UTC, 70825 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private static final List<String> LEGACY_NAMES = List.of("/", "/login", "/login/view", "/logout");
> 레거시 컨트롤러와 어노테이션 기반 컨트롤러의 공존을 위해서 추가해주신 부분 같습니다.

네 정확합니다!

> 그런데 어떤 요청을 어떤 컨트롤러로 처리할 수 있는지는 HandlerMapping의 관심사라는 생각이 듭니다.
51번째 줄, 56번째 줄과 같이 DispatcherServlet은 요청을 처리할 수 있는 컨트롤러를 전달받아서 실행만 하면 되지 않을까요?

천재시네요 지토..
이 부분은 `ManualHandlerMappingAdapter`로 이동할게요!

2023-09-23 13:28 UTC, 70825 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerMappings = new ArrayList<>();
지토 저 궁금한 점이 생겼는데요
코드 수정하면서 디버그 모드로 확인해보니까 init은 apache 패키지에서 호출하고 있는데, 제가 위 답변을 잘못한 것 같아가지구요
혹시 제가 이해를 잘못한거라면 예시로도 설명해주실 수 있나요?

2023-09-23 13:34 UTC, 70825 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private Object[] basePackage;
이 부분은 생성자로 코드를 이동할 생각이었는데, [이 코멘트](https://github.com/woowacourse/jwp-dashboard-mvc/pull/542#discussion_r1335006723)로 인해 일단 보류할게요!

2023-09-23 14:47 UTC, 70825 commented on app/src/main/java/com/techcourse/ManualHandlerMappingAdapter.java
> +            handlerExecutions.put(handlerKey, handlerExecution);
`HandlerExecution.java` 코드를 수정했습니다!
제가 2단계 코드에서 컨트롤러 클래스에 `ModelAndView`를 반환하는걸 못보고 지나쳤네요

2023-09-23 14:49 UTC, 70825 reviewed
안녕하세요 지토!
수정할 부분은 수정했는데, 수정하려다가 제가 잘못 이해한 부분이 있는지 궁금한 부분도 있고, 제 생각 듣고 싶은 부분은 따로 코멘트 남겨두었어요

수정할 남은 부분은 3단계 진행하면서 같이 진행해도 될까요??

감사합니다!

2023-09-24 02:52 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerMappings = new ArrayList<>();
init() 메서드를 apache 패키지에서 호출하고 있다는게 이 부분 말씀하시는게 맞을까요?

```
1. mvc 모듈에 있는 jakarta.servlet.ServletContainerInitializer로 인해서 톰캣이 서블릿 컨테이너를 읽어오면서 WebApplicationInitializer.onStartup() 호출 
2. DispatcherServletInitializer이 WebApplicationInitializer를 구현하고 있으므로 onStartup() 호출 
3. DispatcherServletInitializer이 DispatcherServlet의 initialize() 호출
```

위에 언급한 내용이 맞다면 `initialize()` 메서드는 지우면 안 되는 거기는 합니다!
다만 제가 말씀드리고 싶었던 부분은 저희가 현재 프레임워크를 일부 개발하고 있다고 생각해서 말씀드리고 싶은 부분이었습니다 

프레임워크 영역을 개발하고 있으니 apache에서 initialize을 호출하고 있기는 하지만 최소한의 방어 로직이 필요하다고 생각했었습니다
그래서 저 같은 경우는 그냥 `handlerMappings = new ArrayList<>();`를 필드 레벨에 선언해주거나 생성자 위치에서만 언급하면 충분하다고 생각하고 이러한 부분에서 로건의 의견을 묻고 싶었습니다

2023-09-24 02:56 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private Object[] basePackage;
넵 코멘트는 동의하는 바이고 뭔가 제가 말씀을 좀 헷갈리게 잘못 전달한 것 같습니다!

첫 번째 코멘트는 해당 위치에 달았으니 생략하고, 해당 부분의 경우 DispatcherServlet가 아니라 AnnotationHandlerMapping이 가지고 있으면 어떨까하는 의견이었습니다! 

만약 그렇다면 DispatcherServlet에 위치한 handlerMappings을 초기화할 수 있는 별도의 방법이 필요할텐데, DispatcherServlet.init()에서는 `handlerMappings.forEach(HandlerMapping::initialize);`나 `manualHandlerMapping.initialize();`와 같이 `초기화`하는 로직에만 집중하고 `handlerMappings.add()`와 같이 `HandlerMapping`에 뭔가를 추가하는 로직은 별도의 메서드로 수행할 수 있지 않을까 생각했습니다!

그래서 순서는 대충 
```
1. DispatcherServlet.addHandlerMapping()으로 HandlerMapping 추가 
2. addHandlerMapping()으로 추가한 HandlerMapping은 아직 initialize()가 되지 않았으므로 DispatcherServlet.init() 호출
```

요런 방식이 되지 않을까 생각했습니다

2023-09-24 02:59 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            modelAndView.getView().render(modelAndView.getModel(), request, response);
아하 그런 의미였군요! 
`점진적인`이란 단어에 집중했다면 로건이 왜 이렇게 진행했는지 이해가 되네요!

전 점진적인 리펙토링을 커밋으로 표현하고, 그 결과를 미션 2단계에서 제출하는 것으로 이해하고 있었습니다
근데 말씀 들어보고 3단계를 확인해보니 로건이 말씀해주시고 적용한 부분이 미션의 의도와 조금 더 가까운 것 같네요!

잘 배우고 갑니다 👍

2023-09-24 03:02 UTC, apptie commented on app/src/main/java/com/techcourse/ManualHandlerMappingAdapter.java
> +            handlerExecutions.put(handlerKey, handlerExecution);
로건의 의도를 말씀해주셔서 해당 클래스에 대해 이해를 할 수 있었던 것 같네요!
변경하신 내용도 깔끔한 것 같고요 ㅎㅎ

의견 공유 감사합니다

2023-09-24 03:06 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            if (Objects.nonNull(handlerExecution)) {
로건의 의견을 공유해주셔서 감사합니다!

이거 제가 `Objects`의 정적 메서드로 사용하신 분들에게 항상 질문드리는 부분인데 대부분의 분들이 `!=`을 통한 직접 비교보다는 `Objects`를 활용하는게 가독성이 더 좋다고 판단하시더라고요 ㅎㅎ
가독성은 개인의 입장이니 저는 일관성 있게 사용하면 좋다고 생각하는 편입니다(가독성은 거기서 거기인 것 같아서 저는 잘 모르겠습니다...)

`Predicate`에서만 사용하는걸 권장하는데 왜 `Objects`에 있는지는 저도 항상 의문이 들기는 합니다..
다만 `Objects`에서 다양한 널 체크 로직이 있고, 이걸 어디에다가 때려박을지 애매해서 그냥...모든 인스턴스에서 사용하라는 의미로 넣은건가? 싶기는? 합니다 뇌피셜이라 잘 모르겠긴 하지만요..

2023-09-24 03:10 UTC, apptie approved these changes
고생하셨습니다 로건! 상당히 빠르시네요 ㄷㄷ...
로건의 의견을 공유해주셔서 감사합니다! pending은 왜 발생한건지 잘 모르겠네요..

뭔가 제가 헷갈리게 쓴 것 같은 코멘트...에 대한 내용은 추가했고 변경해주신 코드도 확인했습니다! 변경해주신 부분은 딱히...리뷰할 내용이 없이 잘 작성해주신 것 같아서..? 생략했습니다 ㅎㅎ; 

로건이 말씀하신 `점진적인` 리펙토링을 3단계에서 어떤 식으로 진행할지 기대하겠습니다!

2023-09-24 03:10 UTC, merged

2023-09-24 03:16 UTC, 70825 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +        handlerMappings = new ArrayList<>();
아하 이해 완료 했습니다!
저는 해당 로직을 완전히 생성자 로직에 전부 넣으라는줄 알아서 제가 잘못 이해를 했었네요
상세한 설명 감사합니다 👍

2023-09-24 03:19 UTC, 70825 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +    private Object[] basePackage;
완벽 이해했습니다!
꼼꼼한 책임 분리까지 알려주셔서 너무 좋네요
이러면 `HandlerMapping`을 추가하는 로직만 생성자에 추가하면 될 것 같아요!
완전 자세한 설명 감사합니다

2023-09-24 05:13 UTC, 70825 commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            if (Objects.nonNull(handlerExecution)) {
이것도 1단계에 물어본 enum에 `클래스명.values()`랑 비슷한 맥락인 것 같아요!
- `Objects.nonNull(...)` → null이 아니다 + 특정 값이
- `... != null` → 특정 값이 + 아니다 + null이

저는 이쪽에 더 확신을 가지게 됐던 이유가 지금 프로젝트에서 테스트 코드를 전체적으로 리팩터링을 진행 했었는데요
읽는 단어 한 개, 한번씩 다시 생각하는 부분, 한번씩 다시 눈길이 되돌아가는 부분 이런거 하나하나 제거하도록 만드니까 티끌 모아 태산처럼 코드 읽는 피로감이 확실히 줄어들긴 하더라구요.
물론 문제점도 있는데, 아무래도 레벨1, 레벨2에 작성한 테스트 코드와 코드가 달라져서 팀원들과 동기화가 더 중요해진 점이었어요. 근데 우테코에서는 팀원들간 동기화가 중요하니 이건 문제점이 아닌걸로...

테스트 코드 수정한 방법 궁금하시다면 [제가 다른 활동에서 발표](https://www.slideshare.net/DaBeenJeong/hello70825testcodefinalpdf )한건데 이거 후반부 보시면 될 것 같아요

2023-09-24 08:11 UTC, apptie commented on app/src/main/java/com/techcourse/DispatcherServlet.java
> +            if (Objects.nonNull(handlerExecution)) {
좋은 자료 공유 감사합니다! 상당히 활발하게 외부 활동을 진행하셨군요...리스펙합니다