[MVC 구현 - 3단계] 포이(김보준) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #555
Opened 2023-09-24 07:09 UTC by poi1649

이오 안녕하세요! 
이번 미션에서는 DI를 활용해 요구사항을 진행하기 위해 WebApplicationContext라는 클래스를 만들게 되었습니다.
이 클래스는 mvc에서 사용되는 모든 Bean을 초기화 한 후, 필요한 곳에서 적절하게 빈을 제공해주는 역할을 합니다.
이 과정에서 AnnotaionHandlerMapping처럼 다른 Bean에 대한 의존을 가진 녀석을 어떻게 처리할까 고민을 많이 했습니다. 혼자서는 결론이 나지 않아 스프링을 뜯어보다 ApplicationContextAware 이라는 인터페이스에 대해 알게되었습니다.
Bean의 정보가 필요한 클래스들은 이 인터페이스를 구현하고 setApplicationContext라는 메서드를 통해 이를 먼저 주입받은 후 필요한 Bean들을 가져오게 되는 것 같아 저도 이와 같은 구조를 사용해보았습니다.

 ++ 아래의 요구사항은 requeset Body로 Json 형태를 받는 것을 JsonView에서 처리하게 하라는 것일까요? JsonView는 일단 Json을 응답하는 형태로 구현하였는데 이오는 어떻게 생각하시는지도 궁금하네요!

> HTTP Request Body로 JSON 타입의 데이터를 받았을 때 어떻게 자바에서 처리할지 고민해보고 JsonView 클래스를 구현해보자.

아, 패키지 이동으로 인해 커밋이 굉장히 보기 힘드실 것 같습니다 차라리 pull을 받아서 보시는 게 편할지도 모르겠네요...🤔
이번에도 잘부탁드립니다!

2023-09-24 13:09 UTC, LJW25 commented
안녕하세요 포이! 주말에 수고하십니다😀
내일 오후 3시 이전에 리뷰 드릴 예정입니다. 
혹시 더 빠른 리뷰가 필요하시다면 DM 주세요!🙌

2023-09-25 05:53 UTC, LJW25 requested changes
안녕하세요 포이, 이오입니다!
이번 미션도 수고하셨습니다.

`WebApplicationContext`을 활용한 구조로 구현해주셨는데, 저는 생각해 보지 못한 방식이라 덕분에 많이 배워갑니다. 
몇가지 사소한 리뷰 (제가 고민중이라🙃) 의견을 나눠보고 싶은 질문 한가지 남겼습니다.
코드의 퀄리티는 이미 충분하지만 혹시 더 이야기 나눠 볼 부분 있을까 싶어 request changes 하겠습니다!

오늘도 화이팅입니다! 😀

---

> 아래의 요구사항은 requeset Body로 Json 형태를 받는 것을 JsonView에서 처리하게 하라는 것일까요? JsonView는 일단 Json을 응답하는 형태로 구현하였는데 이오는 어떻게 생각하시는지도 궁금하네요!
> > HTTP Request Body로 JSON 타입의 데이터를 받았을 때 어떻게 자바에서 처리할지 고민해보고 JsonView 클래스를 구현해보자.

-> 이 부분에 대해서 저도 포이가 구현하신 형태와 동일하게 생각하였습니다. 현재 입력을 json 형태로 받는 api가 없어서 의도를 파악하기 어렵기도 하고, view는 응답 하는 용도라고 생각해서 Json을 응답하는 형태가 적절했다고 생각합니다.

2023-09-25 05:53 UTC, LJW25 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/context/WebApplicationContext.java
> +    );
`java.util`을 명시해줄 필요가 있을까요?

2023-09-25 05:53 UTC, LJW25 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/DispatcherServlet.java
> +        view.render(mv.getModel(), request, response);
`ModelAndView`에서 `view`와 `model`을 각각 꺼내오는데, 객체 내에서 수행한다면 책임 분리를 명확히 할 수 있지 않을까요?

2023-09-25 05:53 UTC, LJW25 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/DispatcherServlet.java
>      }
포이의 코드에 대한 피드백은 아니고, 이번 미션에서 고민하던 내용인데 포이의 의견도 듣고싶어서 남깁니다! (무시하셔도 됩니다😌)

2단계에서 3단계로 넘어오면서, handler와 handlerAdapter가 하나밖에 남지 않게 되어 사실 mapping이 무의미해졌는데요.
저는 이게
1. 확장성&유연성이므로 보존해야한다
2. 이 또한 legacy이므로 삭제해야한다

중에 고민이 되더라구요. 
저는 일단 1번으로 구현하긴 했는데 마땅히 납득되는 이유가 떠오르진 않아서, 혹시 포이는 어떻게 생각하시는지 의견을 묻고싶습니다!😃

2023-09-25 05:53 UTC, LJW25 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/view/JsonView.java
> +    }
렌더링 방식이 변경되면서 `viewName`을 외부로 노출시킬 필요도 없어졌을 것 같습니다 😃

2023-09-25 05:53 UTC, LJW25 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/view/RedirectView.java
> +    }
`RedirectView`를 별도의 클래스로 구현하여 불필요하게 반복되는 redirect 부분을 제거하셨네요! 배워갑니다 👍👍

2023-09-25 05:53 UTC, LJW25 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/view/JsonView.java
> +    }
`#컨벤션` 메소드 순서를 호출된 순서에 맞게 정렬하는건 어떨까요?

2023-09-25 07:16 UTC, poi1649 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/context/WebApplicationContext.java
> +    );
커밋 설정이 이상하게 바뀌어 있었네요.. 수정했습니다 !🫡

2023-09-25 07:19 UTC, poi1649 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/DispatcherServlet.java
>      }
`스프링 프레임 워크를 만든다.` 라는 것이 목적이라면 그들의 철학을 따라서 확장을 열어두는 편이 좋아보이네요!
저는 부가적으로 스프링의 구조도 학습하며 왜 이렇게 썼는지 느낄 수 있는 기회라고 생각하기도 해서 열어두었습니다.

2023-09-25 07:21 UTC, poi1649 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/view/JsonView.java
> +    }
앗 확실히 순서를 바꿔주는게 좋겠네요

2023-09-25 07:26 UTC, poi1649 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/DispatcherServlet.java
> +        view.render(mv.getModel(), request, response);
사실 처음에는 `ViewResolver`를 구현하고 알맞은 View를 선택하는 책임을 넘겨줬었는데, 힌트에 있는 코드에서 그냥 Controller에서 View를 선택하길래 다시 삭제했습니다...😂 이 과정에서 modelAndView를 수정하지 않았네요! 확실히 지금의 구조에서는 굳이 외부로 꺼내서 작업할 필요는 없어보여 수정했습니다!

2023-09-25 07:27 UTC, poi1649 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/view/JsonView.java
> +    }
위와 동일한 이유네요! 수정하였습니다!

2023-09-25 07:31 UTC, merged