[MVC 구현 - 3단계] 도치(김동흠) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #559
Opened 2023-09-24 08:44 UTC by hum02

안녕하세요 로건!
3단계 구현해보았어요. 잘 부탁드려요~~

2023-09-24 14:04 UTC, 70825 requested changes
안녕하세요 도치~

2단계 고칠 부분도 잘 반영해주시고, `final`, `final 없는 코드`가 섞여져 있는 곳도 다 규칙성있게 바뀌어서 읽기 더 좋아졌습니다!
이 부분을 언급 했던 이유는 저는 보통 `final`을 쓰게 되는 경우, `final`이 없는 변수의 경우엔 추후에 값이 바뀔 수 있다는 뜻이 내포되어 있다고 생각하는데요. 그런 의미에서 `final`을 규칙성 있게 적용함으로써 코드 읽는게 좀 더 빨라지게 된 것 같습니다!
저는 이렇게 생각해서 `final`을 붙이게 되는데, 도치도 비슷한 생각이신지, 아니면 다른 계기로 인해 `final`을 붙이게 되신건지 궁금해지네요

이제 마지막 단계라 월요일 마감이니 시간이 좀 남아가지고, 이전 단계에서 못물어봤던 부분도 여기에 코멘트를 달아놨어요!

고생하셨어요~

2023-09-25 05:59 UTC, hum02 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DispatcherServlet.java
> +            final ModelAndView modelAndView = (ModelAndView) handlerAdapters.execute(handler, request, response);
흠 handlerAdapters.execute()의 반환값을 이제는 modelAndView로 정할 수 있죠! 
굳이 수정하지 않은 이유는 지금이 더 확장성 있게 작성된 상태라고 생각해서에요.
레거시 controller를 지운 지금 상태에서는 사실 handlerMapping, handlerAdpater가 다 필요없는 상태라고 생각해요. 그럼에도 남겨둔 것은 앞으로도 다른 형식의 controller가 추가되도 지원할 여지를 남기기 위해서라 생각해서 이 부분도 타입을 정하진 않았습니다.
합리적인 생각일까요?

2023-09-25 06:02 UTC, hum02 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapters.java
> +    private final Set<HandlerAdapter> handlers = new HashSet<>();
중복된  HandlerAdpater를 저장할 필요는 없다고 생각해서 set을 사용했어요!
이러면 같은 adapter가 중복 저장되어 저장공간 낭비, 같은 요청인데 때에 따라 다른 adapter로 처리될 위험을 피할 수 있겠다 생각했습니다

2023-09-25 06:18 UTC, 70825 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapters.java
> +    private final Set<HandlerAdapter> handlers = new HashSet<>();
아하 그거까지 고려하셨군요..
저도 다음미션이나 다다음 미션때 한 번 사용해봐야겠어요
감사합니다!

2023-09-25 06:29 UTC, hum02 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java
> +}
질문 감사해요!
우선 레거시 코드가 지워져서 handlermapping이나 handleradapter를 구현할 필요는 없는데에도 이번에 적용한 것은 확장성 있는 구조를 위해서라 생각해주시면 되겠습니다.

로건이 언급해주셔서 어댑터 패턴에 대해서 저도 더 공부해볼 수 있었어요!
그런데 이번 구현은 어댑터 패턴을 써봐야겠다고 생각하지는 않았습니다.. 
이름이 오해를 유발하도록 지어졌군요..

저는 여러   handler/ handler의 실행/ 형식을 지원하기 위해 추상화를 한단계 더 해야겠다는 생각으로 구현했어요! 때문에 기존, 새로운 handler 모두가 인터페이스를 구현하게 됩니다.

adapter패턴도 고려해볼 만한 방식이라 생각해요. 하지만 3개 이상의 형식에 대한 확장성에서는 불리하다 생각합니다. 새로운 handler가 기존의 handler의 형식에 adapt하려 할때마다 class하나씩이 더 필요하죠. ex) a, b,c, 클래스에서 d가 추가되면 d-cdpater, d-b adapter, d-a adapter
가 다 필요하게 될 수 있다.
때문에 차라리 모든 것이 하나의 인터페이스를 구현하도록 형식을 통일하는게 형식의 개수가 많을 수록 더 유리하다 생각했어요.

제가 어댑터 패턴을 맞게 이해했나요?

2023-09-25 06:48 UTC, hum02 commented on app/src/main/java/com/techcourse/controller/UserController.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 회원입니다."));
꼼꼼하시군요!
저는 존재하지 않는 회원에 대한 조회 api의 경우 에러를 반환하는 건 부적절하다 생각해
빈 문자열을 응답하도록 수정했어요.
웹페이지에 대한 api도 아니고 json조회 api에서 존재하지 않는 회원 조회가 not found에러를 발생시키는 건 사용자가 기대하는 동작이 아닐거라 생각합니다.
이 부분 관련해서 로건의 생각도 묻고 싶네요. 예외발생? 빈 문자열 반환? 로건의 생각은 어떤가요?

2023-09-25 06:50 UTC, hum02 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DispatcherServlet.java
> +        final AnnotationHandlerMapping annotationHandlerMapping = new AnnotationHandlerMapping("com.techcourse");
app모듈에 속하는 모든 어노테이션을 스캔하고 싶었어요! controller패키지로 지정하는 게 나을 수도 있다는 뜻이신가요?

2023-09-25 06:55 UTC, 70825 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java
> +}
> 저는 여러 handler/ handler의 실행/ 형식을 지원하기 위해 추상화를 한단계 더 해야겠다는 생각으로 구현했어요! 때문에 기존, 새로운 handler 모두가 인터페이스를 구현하게 됩니다.

아하 이해 완료 했습니다

> adapter패턴도 고려해볼 만한 방식이라 생각해요. 하지만 3개 이상의 형식에 대한 확장성에서는 불리하다 생각합니다. 새로운 handler가 기존의 handler의 형식에 adapt하려 할때마다 class하나씩이 더 필요하죠. ex) a, b,c, 클래스에서 d가 추가되면 d-cdpater, d-b adapter, d-a adapter
가 다 필요하게 될 수 있다.
때문에 차라리 모든 것이 하나의 인터페이스를 구현하도록 형식을 통일하는게 형식의 개수가 많을 수록 더 유리하다 생각했어요.

아래 내용이 제가 이해한게 맞을까요?
```
클래스 A, B, C가 레거시 클래스 D를 사용하는 중인데, 레거시 D를 대체할 새로운 버전의 클래스 NEW D으로 교체할 예정이다.
이때 D는 A에 맞는 어댑터, B에 맞는 어댑터, C에 맞는 어댑터의 클래스를 만들게 되니 차라리 범용적인 인터페이스를 만들어서 관리할 수 있도록한다.
```

<br/>

제가 이해한게 맞다면 보통 저희가 코딩할 때 아래처럼 관리되는게 아닐까 생각되는데요

<br/>

예시로 `A Service`, `B Service`, `C Service`에서는 `D Repository`를 주입 받는데, 만약 `NEW D Repository`로 교체하게 되는 경우를 예시로 들어볼게요.
이때 어댑터 패턴을 사용하게 될 경우, 저라면 `NEW D Repository`과 `D RepositoryAdapter`를 합치는 하나의 인터페이스를 만들 것 같아요. 이건 `Integration Repository`로 부를게요
그러면 `A Service`, `B Service`, `C Service` 에서는 `A-D Adapter`, `B-D Adapter`, `C-D Adapter`로 만들 필요 없이 각 서비스에서 `Integration Repository`로 코드만 교체해도 되지 않을까 생각이 들었어요

2023-09-25 06:57 UTC, hum02 commented
>! 저는 이렇게 생각해서 `final`을 붙이게 되는데, 도치도 비슷한 생각이신지, 아니면 다른 계기로 인해 `final`을 붙이게 되신건지 궁금해지네요
> 

이 부분은 우선 기존 코드에 final이 붙어있었기에 컨벤션 통일의 목적으로 달아야겠다 생각했어요.
물론 final을 붙이면 변수가 변하지 않는다는 걸 보장할 수 있다는 장점이 있다고 생각해요.
이로인해 읽는 게 빨라지는 건 저는 잘 모르겠지만(아직도 느립니다.. ㅠ) 
안전성을 높일 수 있다고 생각해요! 무의식적인 재할당을 막아주니까요

2023-09-25 07:07 UTC, 70825 commented on app/src/main/java/com/techcourse/controller/UserController.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 회원입니다."));
> 웹페이지에 대한 api도 아니고 json조회 api에서 존재하지 않는 회원 조회가 not found에러를 발생시키는 건 사용자가 기대하는 동작이 아닐거라 생각합니다

저도 동의합니다! 근데 이 부분은 미션 범위 경계선에 있는 것 같아서 500에러 페이지에서 404에러 페이지로 보여주는게 그나마 차선책이라고 생각했어요

확실히 에러 페이지를 보여주는 것보다 빈 문자열 반환하는게 더 좋다고 생각해요!

저는 아예 api 호출에서 에러가 발생하는건 json으로 반환하도록 했어요
근데 API 에러 반환할 때마다 에러 메시지도 상황에 맞게 만들어야하니 생각도 많이해야하고, 변경된 파일도 많아서 괜히 한 것  같더라구요 ㅠㅠ
```
{"message": "[ERROR] 존재하지 않은 회원입니다."}
```

2023-09-25 07:11 UTC, 70825 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DispatcherServlet.java
> +        final AnnotationHandlerMapping annotationHandlerMapping = new AnnotationHandlerMapping("com.techcourse");
아녀 이 부분은 3단계를 진행하게 되면서 `DispatcherServlet`이 mvc 패키지로 이동하게 된 점 때문에 그렇습니다
실제로 프로덕션 코드를 작성하게 될 때에는 저희가 `DispatcherServlet`을 건들지 못하는 것으로 알고 있는데요
이런 상황에서 `DispatcherServlet`에 `"com.techcourse"`를 두게 된다면 스프링 프레임워크가 프로덕션 코드를 알고 있게 되는 상황이 발생해요
그렇기 떄문에 요 부분은 무조건 수정을 하는게 맞다고 생각이 들어요

2023-09-25 07:19 UTC, 70825 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DispatcherServlet.java
> +            final ModelAndView modelAndView = (ModelAndView) handlerAdapters.execute(handler, request, response);
이거는 그러면 나중에 `ModelAndView`를 포함하는 상위 클래스가 추가된다는 이야기로 들리는데 제가 이해한게 맞을까요?
저는 `ModelAndView`가 `View`를 가지고 있기 때문에 오히려 `View`에서 처리할 수 있다는 생각이 드네요

2023-09-25 07:25 UTC, 70825 requested changes
안녕하세요 도치!

수정된 커밋을 살펴봤는데, 여기에 드릴 코멘트는 없는 것 같아요 👍
이전에 달아둔 코멘트에 답글 남겼는데 확인부탁드려요~

제가 생각하기엔 무조건 고쳐야할 부분이 1개 있어서 한 번 확인해주세요
나머지는 코멘트만 다신 다음 다시 리뷰 요청 눌러주시면 됩니다!

2023-09-25 07:25 UTC, 70825 commented on app/src/main/java/com/techcourse/controller/UserController.java
> +                .ifPresent(u -> modelAndView.addObject("user", u));
오 빈문자열로 반환하게 된다면 간단하게 처리할 수 있네요 👍

2023-09-25 07:56 UTC, hum02 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java
> +}
로건 짱👍

2023-09-25 07:58 UTC, hum02 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DispatcherServlet.java
> +            final ModelAndView modelAndView = (ModelAndView) handlerAdapters.execute(handler, request, response);
호호 그냥 나중에 handler가 추가된다면 그때 상황에 따라 수정될 부분이라 생각한건데
view로 추상화해서 처리할 수도 있겠네요

2023-09-25 08:06 UTC, hum02 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DispatcherServlet.java
> +        final AnnotationHandlerMapping annotationHandlerMapping = new AnnotationHandlerMapping("com.techcourse");
아하 이 부분이군요! 확실히 프레임워크가 어플리케이션에 대하 하드코딩된 식으로 알고 있다니
말이 안됩니다. 
놓쳐버린 부분이네요. 감사합니다!!!!

2023-09-25 08:21 UTC, 70825 approved these changes
안녕하세요 도치!

이번 단계에서 서로 생각을 많이 공유하게 되어서 좋았어요 🥳

고생하셨습니다!

2023-09-25 08:21 UTC, merged