[MVC 구현하기 - 1단계] 라이언(권영훈) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #56
Opened 2021-09-12 17:21 UTC by YounghoonKwon

영이 하이염~~
많이 늦었네요 ㅠ

일단 돌아가게만 구현했습니다,,

제가 늦은만큼 리뷰도 천천히 주셔도 됩니다,,

2021-09-12 23:57 UTC, choijy1705 requested changes
안녕하세요 라이언.
미션 진행하느라 고생많았습니다. 몇가지 피드백 남겼는데 확인부탁드려요.
그리고 @Controller를 사용하기 위해 UserController를 만드셨는데 현재 구조에서는 이용이 안되고 있는것 같습니다. LoginController, LoginViewController 대신 UserController가 이용되도록 구현되면 좋을 것 같아요

2021-09-12 23:57 UTC, choijy1705 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            return getManualHandler(request);
이미 `handlerMapping.getHandler(request)` 에서 handler를 가져왔는데 getManualHandler 에서 똑같은 작업을 반복하는거 같아요. null 체크와 분리하여 진행하면 중복 작업을 안해도 될것같습니다

2021-09-12 23:57 UTC, choijy1705 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>                  .map(Controller.class::cast)
이 부분을 잘 활용하면 getHandler에서도 for 문을 활용안할 수 있지 않을까요?

2021-09-12 23:57 UTC, choijy1705 commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +                        handlerExecutions.put(handlerKey, new HandlerExecution(method.getDeclaringClass().getConstructor().newInstance(), method));
`requestMapping.method()[0]` 만 하면 하나만 등록이 될것 같아요. 같은 url로 get, post 등이 들어온다면 처리를 해줘야할 것 같습니다.

2021-09-12 23:57 UTC, choijy1705 commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
>          // todo
DispatcherServelt에서 view를 rendering 하고 있는것 같은데 view에서 redering 하도록 해보면 좋을 것 같습니다.

2021-09-13 02:09 UTC, YounghoonKwon commented on learning/src/test/java/reflection/ReflectionTest.java
> +        final Constructor<?> secondConstructor = questionClass.getConstructor(String.class, String.class, String.class);
오 좋습니다!!

2021-09-13 02:15 UTC, YounghoonKwon commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            return getManualHandler(request);
이부분은, 55번째줄 getHandler부분이 annotation이용한 핸들러 가져오는 부분이고,
가져온 핸들러가 null일 경우에는 manual이용해서 핸들러 가져오는 부분입니당

annotation에 등록되지 않은 핸들러가 있을 시 manual에 등록된 핸들러를 가져오는 로직이에요!!

2021-09-13 02:29 UTC, YounghoonKwon commented on mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java
> +                        handlerExecutions.put(handlerKey, new HandlerExecution(method.getDeclaringClass().getConstructor().newInstance(), method));
get 이외에도 등록 됩니다!

2021-09-13 02:34 UTC, YounghoonKwon commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>                  .map(Controller.class::cast)
수정완료!

2021-09-13 02:38 UTC, YounghoonKwon commented on mvc/src/main/java/nextstep/mvc/view/JspView.java
>          // todo
완료! 2단계인줄 알았네용 ㅠ

2021-09-13 04:19 UTC, choijy1705 approved these changes
라이언 피드백 반영 확인하였습니다. 
피드백 반영 하시면서 안쓰는 부분이 생긴거 같은데 (dispatcherServlet.move())해당 부분은 2단계 진행하면서 지워주세요

2021-09-13 04:19 UTC, merged