[MVC 구현 - 3단계] 매튜(김재연) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #566
Opened 2023-09-24 10:09 UTC by kpeel5839

헤이나아아아아~~~!!

2단계 머지하면서 주신 코멘트들도 적용해봤어요!

아쉬운 것은, 힘들게 `Adapter` 도입했는데 `Legacy Code` 를 지우라는 요구사항이 있더군요..

눈물을 머금고 지웠습니다.

그러면서 `ManualHandlerAdapter`, `ManualHandlerMapping` 도 지웠어요! 쓰지 않는 거대한 코드를 남겨 놓는다면 코드를 읽는 사람으로 하여금 혼란을 불러일으킬 수 있을 것 같아서요!

이번 리뷰도 잘 부탁드려요 알러뷰 헤이나~! 주말에 리뷰 너무 고마워요~~~❤️

2023-09-25 06:24 UTC, hyena0608 requested changes
매튜매튜~~~ 미션 고생하셨어요!
훨씬 더 유연한 코드를 이렇게 이쁘게 빼주셔서 재밌게 잘봤습니다 😊

너무 잘하셔서 커멘트 남길게 많지 않네요 👍
커멘트 살짝만 남겼으니 확인부탁드릴게요 매류매류!

2023-09-25 06:24 UTC, hyena0608 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java
> +    public void render(
텍스트를 전송할 때 OutputStream 대신 PrinterWriter를 사용해보시는거는 어떤가요?

2023-09-25 06:24 UTC, hyena0608 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    public Object getHandler(HttpServletRequest request) {
HandlerExecution이 아닌 Object를 반환하니 이후에 다른 객체의 타입을 반환해도 처리해줄 수 있네요! 👍👍

AnnotationHandlerMappingTest도 수정해주시면 될 거 같아요!

2023-09-25 06:24 UTC, hyena0608 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapter.java
> +public interface HandlerAdapter {
HandlerAdapter를 구현해주셨군요!
고생하셨어요 매튜매튜~

2023-09-26 03:09 UTC, kpeel5839 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java
> +    public void render(
바로 수정하도록 할게요!

2023-09-26 03:09 UTC, kpeel5839 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java
> +    public Object getHandler(HttpServletRequest request) {
이거를 신경 못썼네요.. 호호

2023-09-26 03:09 UTC, kpeel5839 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapter.java
> +public interface HandlerAdapter {
알러뷰

2023-09-26 03:29 UTC, kpeel5839 commented
헤이나 헤이나!

말씀해주신 부분들 다 수정해봤어요!

이번에도 잘 부탁드려요~~!! 알러뷰

2023-09-26 07:35 UTC, hyena0608 requested changes
매튜매튜~~ JsonView 조금만 수정부탁드립니다!
커멘트 하나 남겼습니다~ 마지막 수정 화이팅 👍👍👍

2023-09-26 07:37 UTC, kpeel5839 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java
> +        response.getWriter().write(responseBody);
알러뷰 헤이나!

2023-09-26 11:17 UTC, kpeel5839 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java
> +        response.getWriter().write(responseBody);
헤이나의 리뷰는 환상적이에요!

2023-09-26 11:18 UTC, kpeel5839 commented
헤이나 리뷰 반영했어요오오오오

잘 부탁드립니다~!

2023-09-27 01:03 UTC, hyena0608 approved these changes
매튜매튜매튜매튜매튜~
마지막까지 진짜 고생많으셨어요!
커멘트 하나하나 읽고 적용하시려고 하시는 모습이 너무 감동이었습니다!

미션은 머지할게요! 고생하셨어요!

2023-09-27 01:03 UTC, hyena0608 commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java
> +        return objectMapper.writeValueAsString(model);
굿굿 매튜매튜!!! 다른 미션도 바쁘실텐데 고생하셨어요! 👍✨👍✨👍✨👍✨👍✨

2023-09-27 01:03 UTC, merged