[MVC 구현하기 3단계] 우가(윤정욱) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #570
Opened 2023-09-24 11:41 UTC by wugawuga

안녕하세요 달리!! 3단계도 많이 헤맨것 같습니다ㅠㅠ

이번에 집중한 부분은 의존성 분리였습니다.
레거시를 어떻게 제거를 해나가야 최대한 오류없이 의존성도 깔끔하게 관리될까가 고민이었는데요.

DispatcherServletInitializer 는 app 모듈에서 뺄 수가 없더라구요.
이 부분 달리 의견이 궁금합니다.

그리고 mvc 모듈에서 TomcatStarter 와 DispatcherServlet 의 위치인데요.
web 패키지 안에 servlet 패키지와 TomcatStarter.class
servlet 패키지 안에 DispatcherServlet.class 가 있습니다.

달리는 패키지를 어떻게 나누셨는지 아직 못하셨다면 어떻게 나누는게 좋을지 의견이 궁금합니다.

2023-09-25 11:35 UTC, waterricecake commented
저도... 헤매고 헤매고 헤매다가 일단 추후에 리펙터링을 하더라도 일단 내야지 하고 제출했습니다. 
저도 우가처럼 mvc와 관련된 모든 class를 옮기고 싶었지만 `ServletContainerInitializer`가 어떤 식으로 작동되는지를 이해를 못해서 못옮기는 중이었습니다. `DispatcherServletInitializer`을 app패키지에서 mvc 패키지로 옮기니 `SpringServletContainerInitializer`에서
`INFO: No Spring WebApplicationInitializer types detected on classpath`라는 log가 생기는 것이 보여 확인해 보니 `WebApplicationInitializer.class`를 찾지 못하여 initializers 가 비어서 생기는 문제인 것 같습니다. 저도 이걸 어떻게든 찾아보고 싶은데 내부 로직이 생각보다 복잡하더라고요. 그래서 못옮기고 있었습니다.

2023-09-25 12:13 UTC, waterricecake requested changes
우가! 수고하셨습니다!
우가가 어떤 것을 고민했는지 해결했는지 잘 보이는 코드였습니다.
구조가 너무 깔끔하여 리뷰남길 것이 없네요.
대신 제가 하다가 고민했던 부분에서 우가와 차이가 있어 질문 남겨 봅니다.

2023-09-25 12:13 UTC, waterricecake commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +        view.render(model, request, response);
view와 model이 둘다 ModelAndView에 있는데 이 render과정을 ModelAndView 내부에서 해결하는 것은 어떤가요?

2023-09-25 12:13 UTC, waterricecake commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        }
오 이 부분은 생각도 못했네요. 정말 좋은것 같습니다.👍

2023-09-25 15:39 UTC, wugawuga commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +        view.render(model, request, response);
확실히 내부에서 하면 SRP 를 잘 지키는 것 같습니다 ㅎㅎ 감사합니다

2023-09-25 16:19 UTC, wugawuga commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        return modelAndView;
Handler 가 반환하는게 Map<String, ?> 라고 가정을 한다는 게 어떤 말씀인지 와닿지가 않는 것 같습니다!
이미 addObject 로 모델이 반환될 경우 집어 넣어주고 있습니다. 하나씩 넣는 것도 어떤 말씀인지 이해가 잘 되지 않아요ㅠㅠ

코드로 보여주실 수 있으신가요?

2023-09-25 16:20 UTC, wugawuga commented
감사합니다! 달리
달리 코멘트에 잘 와닿지 않는 부분이 있어서 코드로 요청드립니다!

2023-09-26 01:29 UTC, waterricecake commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        return modelAndView;
```suggestion
                if(result instanceof Map){
            for(Entry entry: ((Map<String,?>) result).entrySet()){
                final ModelAndView modelAndView = new ModelAndView(new JsonView());
                modelAndView.addObject((String) entry.getKey(),entry.getValue());
            }
            return new ModelAndView(new JsonView());
        }
        throw new IllegalAccessException();
```
이런식으로 json도 key:value 형태이니 이런 형식의 타입으로 넣어주는 것은 어떤가요?

2023-09-26 02:14 UTC, wugawuga commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        return modelAndView;
다른 객체를 반환하게 될 땐 동작을 하지 않겠군요

Controller 에서 Json 으로 반환하기 위한 다양한 객체가 있을 것 같은데,
달리가 말씀하신 부분은
다른 객체를 반환하게 되면 또 그에 맞춰서 instanceof (dto or response 등등) 하나하나 만들어 줘야 합니다.

2023-09-26 02:15 UTC, wugawuga commented
달리가 작성해주신 코드에 대한 [답변](https://github.com/woowacourse/jwp-dashboard-mvc/pull/570#discussion_r1336549756)입니다!!!

2023-09-26 02:20 UTC, wugawuga commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        return modelAndView;
![image](https://github.com/woowacourse/jwp-dashboard-mvc/assets/91244090/1f4b96bc-ff8b-4508-aa64-ed1ab9dd2977)

또 다른 궁금한 점이 있습니다.

modelAndView 를 생성해서 model 을 차곡차곡 담은 다음에,
새로운 modelAndView 를 반환하는 이유가 궁금합니다!! 모델이 하나도 없을 것 같아서요.

2023-09-26 02:38 UTC, waterricecake approved these changes

2023-09-26 02:38 UTC, waterricecake commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        return modelAndView;
아 제가 잘못 적었군요;;
```
 private ModelAndView getModelAndJsonView(Map<String, ?> result){
        final ModelAndView modelAndView = new ModelAndView(new JsonView());
        for(Entry entry: result.entrySet()){
            modelAndView.addObject((String) entry.getKey(),entry.getValue());
        }
        return modelAndView;
    }
```
입니다.

>다른 객체를 반환하게 될 땐 동작을 하지 않겠군요
Controller 에서 Json 으로 반환하기 위한 다양한 객체가 있을 것 같은데,
달리가 말씀하신 부분은
다른 객체를 반환하게 되면 또 그에 맞춰서 instanceof (dto or response 등등) 하나하나 만들어 줘야 합니다.

저는 Map이나 List와 같이 util에 있는 클래스의 경우와 dto, response는 다른 경우의 수라고 생각을 했습니다. Map의 경우 instanceof로 그 경우를 잡을 수 있고 또 key:value형태의 json type으로 쉽게 나타낼 수 있으니 좋지 않을 까 하여 적어보았습니다. 그저 Spring에서 Map<> 형태를 Json형태로 편하게 반환하기에 한번 여쭤보았던 것입니다. 근데 다시 생각해보니 ObjectMapper가 이를 다 해결해주겠네요. 저는 dto나 response라면 reflection을 통해 따로 필드를 읽어와서 해결해와야지 않나 생각하고 있었는데 제 생각이 짧았던것 같습니다.

2023-09-26 02:55 UTC, wugawuga commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        return modelAndView;
맞습니다. reflection 을 따로 구현했어야 합니다

하지만 jsonView 에서 쓰기 쉽게 HandlerAdaptors 에서 만들어 넣어주는 것은 어댑터 역할은 아닌 것 같다는 생각이 드네요.

필요한 데이터를 가공하는 것 또한 JsonView 에서 진행하면 좋을 것 같은데 달리는 어떻게 생각하시나요?

2023-09-26 04:34 UTC, waterricecake commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        return modelAndView;
우가의 말대로 데이터를 가공하는 것은 어댑터의 역할인 것 같습니다. View의 역할은 받은 데이터를 클라이언트가 받을수 잇는 형태로 가공하여 보내는 역할을 하는 것이라고 생각을 하엿습니다. 그 이유는 render라는 메서드 명을 보고 파악하였습니다.
그렇다면 View가 받는 매개변수가 Map<String,?>으로 되어있는 이유는 무엇이라고 생각하나요?? 만약 model이 어떤 형태이든 ObjectMapper로 해결할 수 있다면 `Map<String,?>` 이 아닌 `Object model` 이나 `Object... models`로도 충분했을거라고 생각하는데... 저는 ModelAndView에서 model field의 타입이 'Map<String,Object>'인 것과 연관이 있지않을까 생각을 했었습니다. 물론 코치님들의 기존 코드가 실제 설계와 같지 않을 경우도 있겠지만요

2023-09-26 05:12 UTC, wugawuga commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        return modelAndView;
> 필요한 데이터를 가공하는 것 또한 JsonView 에서 진행하면 좋을 것 같은데 달리는 어떻게 생각하시나요?

어댑터의 역할이라고 잘못 이해하신 것 같네요. 
JsonView 라고 생각을 하고 있습니다.

render 메소드 자체가 View 인터페이스의 메소드를 구현해야하기 때문에 Model<String, ?> 으로 받았습니다.
Object 였다면 달리 말씀대로 넘겼을 거에요.

주어진 View 인터페이스도 그대로 사용하는 것이 미션의 요구사항 아닐까요?
달리는 View 인터페이스의 render 메소드를 리팩터링해서 Object 나, Object ... 로 하셨는지 궁금합니다.

달리 의견에 대한 답변입니다.
최대한 JspView 랑 JsonView 를 추상화 하기 위해선 Map<String, ?> 으로 해결이 되지 않을까요?
Jsp 는 Map 으로 Json 은 Object 로 해야한다면, View 인터페이스를 만들어주신 의미가 퇴색된 것 같네요

> 만약 model이 어떤 형태이든 ObjectMapper로 해결할 수 있다면 Map<String,?> 이 아닌 Object model 이나 Object... models로도 충분했을거라고 생각하는데... 저는 ModelAndView에서 model field의 타입이 'Map<String,Object>'인 것과 연관이 있지않을까 생각을 했었습니다.

달리 말씀대로면 Model 과 View 자체를 분리하고 Model 인스턴스 필드에 Object 를 둬야할 것 같습니다.
그러면 JspView 에서 다시 Object 를 Map 으로 형변환을 해야하고 Json 에선 그대로 사용을 해야합니다.

이 두 과정을 한번에 묶을 수 있는게 Map 형태이고 JsonView 에서 그냥 필요한 걸 꺼내쓰면 되지 않을까요?
달리 의견이 궁금합니다.

2023-09-26 10:26 UTC, waterricecake commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        return modelAndView;
>어댑터의 역할이라고 잘못 이해하신 것 같네요.
JsonView 라고 생각을 하고 있습니다.

이게 맞는것 같네요. 제가 잘못 생각했습니다.

>달리는 View 인터페이스의 render 메소드를 리팩터링해서 Object 나, Object ... 로 하셨는지 궁금합니다.

저는 그대로 Handler에서 반환되는 객체가 Map이라는 가정하에 Map으로 하나씩 넣어주었습니다.
JspView의 render 메서드를 보면
```
        model.keySet().forEach(key -> {
            log.debug("attribute name : {}, value : {}", key, model.get(key));
            request.setAttribute(key, model.get(key));
        });
```
와 같이 사용이 model에서 값을 꺼내어 request에 넣어주는데 다른 view를 구현한다고하면 이런 식으로 각 key마다 값을 넣는 상황이 있을 수 도 있다고 생각하여 ModelAndView의 Model에 나누어 넣게 되었습니다.


>Jsp 는 Map 으로 Json 은 Object 로 해야한다면, View 인터페이스를 만들어주신 의미가 퇴색된 것 같네요

이 말은 동의합니다. 제가 말하고 싶었던 것은
```
void render(Map<String, ?> model, HttpServletRequest request, HttpServletResponse response)
```
에서 model이 받는 값이 "model":Map<String,?> 의 model size 1개의 map을 가지고 있어서, 이런 식으로 model이 어떤 타입이든 넣는 방식때문에 Map<String,Object>를 사용할 것이라면 Object를 사용하는 것이 더 나은가 싶어서 말했던 것입니다.

>이 두 과정을 한번에 묶을 수 있는게 Map 형태이고 JsonView 에서 그냥 필요한 걸 꺼내쓰면 되지 않을까요?

이 말이 맞는 것 같습니다. Map<String,Object>가 사용되었길레  ModelAndView의 model을 그대로 넣으면 되지 않겠나라는 생각했는데, model 자체를 Map에 넣어 보관하는 것이 좀더 유연하게 다른 상황을 대처할 수 있을 것 같네요. 대표적으로 Controller의 반환값이 List<ResposeDto>의 형태일 경우 따로 이 List를 풀 필요없이 넣어주면 되니까요. 그러면 Controller의 반환값이 무엇이든지 해결할 수 있어 항상 유연하게 사용할 수 있을 것 같습니다.

2023-09-26 11:13 UTC, wugawuga commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        return modelAndView;
미션 중에 있어서 프레임워크 요구사항을 지키면서 확장성까지 챙기려고 했는데요
달리는 요구사항에만 집중하신 것 같네요 ㅎㅎ

서로 다른 시선이었기 때문에 더 재밌는 토론이었던 것 같습니다 ㅎㅎㅎ

2023-09-26 11:16 UTC, waterricecake commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlerAdaptor/HandlerAdaptors.java
> +        return modelAndView;
저도 이번 미션들은 혼자하다보니 뭔가 저만의 생각에만 빠진 느낌이었는데 우가 덕분에 더 넓게 볼 수 있었네요. 
ㅎㅎ 저도 재밌었습니다.

2023-09-26 11:18 UTC, waterricecake approved these changes
저도 이번 미션들은 혼자하다보니 뭔가 저만의 생각에만 빠진 느낌이었는데 우가 덕분에 더 넓게 볼 수 있었네요.
ㅎㅎ 저도 재밌었습니다. 이번 미션은 이만 머지하겠습니다. JDBC 미션도 화이팅입니다!

2023-09-26 11:19 UTC, merged