[MVC 구현하기 - 2, 3단계] 케로(김지현) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #578
Opened 2023-09-24 16:15 UTC by jyeost

안녕하세여 블랙캣.... 
... 감사합니다 ...

2023-09-26 02:26 UTC, Songusika requested changes
안녕하세요 케로!
코드가 전체적으로 깔끔해서 수정할 부분이 크게 없네요!
제가 궁금한 부분에 코맨트 남겨놓았습니다!

2023-09-26 02:26 UTC, Songusika commented on app/src/main/java/com/techcourse/support/web/filter/ResourceFilter.java
> +
어떤 예외가 발생할 수 있고 여기서 예외를 잡아주는 이유가 무엇인가요?

2023-09-26 02:26 UTC, Songusika commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +        }
404처리 👍

2023-09-26 07:27 UTC, jyeost commented on app/src/main/java/com/techcourse/controller/IndexController.java
> +    public ModelAndView show(HttpServletRequest req, HttpServletResponse res) {
머리로는 알지만... 마음은.... 귀찮아서 그랬습니다 함번만 봐주쇼

2023-09-26 07:32 UTC, jyeost commented on mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMapping.java
> +    RequestMethod[] method() default {RequestMethod.GET};
리팩터링을 하다가 get 메서드를 매번 지정해주기 귀찮아져서 
스프링의 `@RequestMapping` 의 메서드를 지정해주지 않아도 get처리 되는 것이 떠올라서 가장 쉬운 방법으로 구현했습니다. 
(실제 스프링에서는 어노테이션에서 디폴트 처리를 해주진 않습니다... )

2023-09-26 07:36 UTC, jyeost commented on app/src/main/java/com/techcourse/controller/RegisterController.java
> +        return new ModelAndView(new JspView("/register.jsp"));
사실 큰 차이는 없습니다 !!!
레거시 코드를 수정해가면서 이미 배포된 api라면 두가지 버전을 다 유지 시키는 게 맞지 않을까? 해서 /register/view uri를 살려봤습니다. 

블랙캣상도 안드로이드 팀인만큼 api가 바뀔때 어떤 처리를 해주고 계신지 궁금!!! 합니다!!!

2023-09-26 07:53 UTC, jyeost commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +    private final transient HandlerAdapterRegistry handlerAdapterRegistry;
소나가 자꾸 이 클래스가 직렬화 가능 클래스라고 해당 클래스의 필드가 직렬화 가능한지 명시해 달라며 경고창을 띄워서...
직렬화 할 필요 없다고 써 준 것입니다...
이 DispatcherServlet이 왜 직렬화 가능 클래스인지는 모르겟어오....

2023-09-26 07:57 UTC, jyeost commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/adapter/AnnotationHandlerAdapter.java
> +    public boolean isHandlerAdapter(final Object handler) {
support는 어떠신가용??

2023-09-26 07:58 UTC, jyeost commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/adapter/HandlerAdapterRegistry.java
> +    }
이 클래스를 사용하는 DispatcherServlet이 객체가 생성되면 init 메서드가 자동으로 실행되기 때문에 이에 맞춰서 생성 작업과 초기화 작업을 나누어서 생성 작업의 로직을 덜고자 했슴돠

2023-09-26 08:01 UTC, jyeost commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java
> +        }
헐 좋네유... !!!! 당장 도입!!!!!!! 갈겨!!!!!!

2023-09-26 08:16 UTC, jyeost commented on app/src/main/java/com/techcourse/support/web/filter/ResourceFilter.java
> +
기존 코드의 DispatcherServlet에서 예외를 로깅해주고 Servlet예외로 바꿔서 던져주는 것 때문에 메인 로직이 덜 보인다고 생각되어  필터에서 해주도록 옮겼슴돠!
아마 뷰를 그리는데 실패하거나... 덩덩 수많은 예외가 잇을수 잇겟습니다....

2023-09-26 08:23 UTC, jyeost commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +    }
ModelAndView가 View를 들고 있다고 해서 view를 render하는 기능까지 들고있어야 할 필요는 없다고 생각합니다 
지금 이 객체는 거의 Dto와 비슷한 역할을 하고 있는것 같슴돠

2023-09-26 11:35 UTC, Songusika commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/adapter/AnnotationHandlerAdapter.java
> +    public boolean isHandlerAdapter(final Object handler) {
거기에 **`is`** 까지 얹져보면 더 좋을거같은데요?

2023-09-26 12:21 UTC, Songusika commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +    private final transient HandlerAdapterRegistry handlerAdapterRegistry;
`HttpServlet` 은 `GenericServlet` 을 상속하고 있는데요!
`GenericServlet` 은 `Serializable` 를 구현하고 있습니다. 
따라서 소나에서 직렬화 대상에서 제외하라고 `transient` 키워드를 사용하라고 하는 것 같아요

다시 돌아와서 `GenericServlet`이 왜 직렬화 가능해야하는지는 잘 모르겠어요
2000년대 초반 질문 글을 찾아봐도 찾아봐도 옛날 레거시이다 등 잘 모르겠다는 대답이 대다수네요. 😭

2023-09-26 13:03 UTC, Songusika commented on app/src/main/java/com/techcourse/support/web/filter/ResourceFilter.java
> +
DispatcherServlet 에서 발생하는 예외를 Filter 에서 잡아준다고 이해하면 될까요...?

2023-09-26 13:13 UTC, Songusika commented on app/src/main/java/com/techcourse/controller/RegisterController.java
> +        return new ModelAndView(new JspView("/register.jsp"));
저희는 현재 안드로이드와 배포를 같이 하기 때문에 아직 api 버저닝을 하진 않습니다.
다만 고민을 해보면
1. api에 버전을 명시해서 api 명세를 작성하고 구버전 api 웹 어플리케이션 서버를 특정 기간동안 살려둔다.
   - nginX 와 같은 웹 서버를 통해서 프록시 처리를 한다.
2. 케로의 방법 처럼 하나의 웹 어플리케이션에 구버전 api 코드를 유지한다.

케로의 팀은 어떤 방식을 사용하시나요?

2023-09-27 00:55 UTC, Songusika commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java
> +    private static final ObjectMapper mapper = new ObjectMapper();
저도 처음에는 `ObjectMapper` 를 **static** 으로 두려고했었는데요 하지만 `ObjectMapper` 는 멀티 쓰레드 환경에서 **Thread-Safe** 하지 않다고 합니다. 이는 `setConfig()`, `setDateFormat()` 등의 객체 설정을 바꾸는 메서드가 존재해서입니다!

`ObjectMapper` 를 통해서 `ObjectWriter`, `ObjectReader` 만 따로 뽑을 수 있더라구요!
두 객체는 **Thread-Safe** 하다고 합니다! 추후에는 이런것도 적용해볼 수 있을 거같아요!

2023-09-27 00:57 UTC, Songusika approved these changes
안녕하세요 케로 
MVC 미션 고생하셨습니다! 🎉
코드가 전체적으로 깔끔해서 리뷰하기 좋았습니다!
몇가지 코멘트 달아서 확인해보시면 좋을것 같아요!

저번 **step1**에서 했던 이야기는 제가 DM으로 답변 드릴게요!
**step1** 혹은 **step2,3** 에 대해서 궁금한점 있으면 DM 주세요!
다음 미션도 화이팅입니다!

2023-09-27 00:57 UTC, merged

2023-09-27 03:50 UTC, jyeost commented on app/src/main/java/com/techcourse/controller/RegisterController.java
> +        return new ModelAndView(new JspView("/register.jsp"));
저희는 2번 방법인데 헤더에 특정 값을 넣어서 안드로이드 팀이랑 맞췄습니다 ㅎㅅㅎ
아직 버전2를 배포하지 않아서 두 버전 전부 유지 해본 경험은 없슴돠... 
한번 배포한 api를 닫는건 굉장히 어렵다고 들었는데,, 버전이 여러개라면 모든 서버를 동시에 유지하기엔 비용이 아까울 것 같아요 ...

2023-09-27 03:52 UTC, jyeost commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/DispatcherServlet.java
> +    private final transient HandlerAdapterRegistry handlerAdapterRegistry;
대신 답변해줘서 잘 얻어먹었습니다 ~~ 감사합니다 ^^*

2023-09-27 03:53 UTC, jyeost commented on app/src/main/java/com/techcourse/support/web/filter/ResourceFilter.java
> +
네엥~ 지금 하는 작업이 로깅바께 없는것 같아서 필터에서 잡아주는것이 더 낫겟다고 판단했스영

2023-09-27 03:53 UTC, jyeost commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java
> +    private static final ObjectMapper mapper = new ObjectMapper();
오 그렇군요!!!!!
덕분에 알아갑니다 감사합니당 !!!