[MVC 구현하기 - 3단계] 제나(위예나) 미션 제출합니다
woowacourse/jwp-dashboard-mvc pull request #615
Opened 2023-09-25 07:19 UTC by yenawee

안녕하세요 필립!

제가 PR 에 남긴 의문사항들이나 고민들에 대해서 길게 답변을 남겨주셔서 정말 감사했습니다!
특히 build.gradle 에서 의존성 확인할 수 있는거 정말 꿀팁이었어요 👍👍👍👍👍

플젝에 좀 더 신경쓰느라 3단계는 기능 요구사항만 겨우 충족되게 급하게 구현하게 되었습니다 ㅠㅠ
테스트에 대한 의견도 남겨주셨는데 이번에도 시간이 부족해서 적용을 못했네욥....😭

부족한 점이 많지만,,,, 3단계도 리뷰 잘 부탁드립니다 !! 🙇‍♀️

2023-09-25 11:59 UTC, pilyang requested changes
안녕하세요 제나!!

바쁘신데도 필요한 내용들 잘 구현되고, 지난 리뷰에서 남긴 코멘트도 잘 반영이 된 것 같네요!
전반적인 리팩터링이랑 잘 진행되어서 코드 보기 편했습니다!!

다만 json view구현된 부분에서 확인하셔야 할 것 같은 내용이 있어서 코멘트 남겼습니다.

바로 내일부터 다음미션에 들어가고, 프로젝트도 바쁠것 같아서 일단 힌트가 될만한 링크는 남겨두었습니다.
혹시 추가적인 키워드나 힌트 궁금한 내용이 있으시면 dm으로 편하게 연락 주세요!!

2023-09-25 11:59 UTC, pilyang commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java
> +        response.getWriter().write(jsonValue);
api 요청에서 json이 잘 생성이 되는지 확인해보는게 좋을 것 같습니다!!

지금 서버에
```
http://localhost:8080/api/user?account=gugu
```
로 요청을 보내면
```json
{"user":{"account":"gugu"}}
```

위와같이 데이터가 나오는것을 확인해 볼 수 있습니다.

여기서 고쳐야 할 부분이 2가지가 있을것 같습니다.

---

**첫번째**는 응답에서 사용자의 데이터가 account만 보인다는 문제가 있는것 같습니다.

`User` domain 을 보면 account뿐만 아닌 id, password, email의 데이터도 있는것을 볼 수 있습니다.
과연 이중에 왜 writeValueAsString으로 json형식으로 변환시 account만 나오게 되는지 생각을 해보고, 다른 값들도 json 형식으로 보이게 하려면 어떻게 해야할지 생각해보고, 구현해봐도 좋을 것 같습니다.

---

다음으로 미션요구사항 아래부분을 보면 
> model에 데이터가 1개면 값을 그대로 반환하고 2개 이상이면 Map 형태 그대로 JSON으로 변환해서 반환한다.
위와같은 문구가 있음을 확인할 수 있습니다.

저는 이 말을 Model map에 하나의 엔트리만 있으면 여기서는 user라는 하나의 entry만 있으면, 아래와 같은 형식으로 출력이 되어야 한다고 이해했습니다. (위의 첫번째 문제를 해결했다는 전제 하에)
```json
{"id":1,"account":"gugu","password":"password","email":"hkkang@woowahan.com"}
```

 model에 여러개의 entry가 등록이 되어있다면
```json
{"entry-key1":{ ... },"entry-key2":{ ... }}
```
위처럼 지금 제나의 코드에서처럼 응답이 되도록 하는 방식으로 출력이 되어야 한다고 생각했습니다.

이것에 대한 제나의 의견과, 어떤식으로 하면 이처럼 구현이 될 지 해보는게 어떨까요..?

2023-09-25 11:59 UTC, pilyang commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java
> +        response.getWriter().write(jsonValue);
첫번째 내용에 대한 힌트는 [밸덩 Jackson tutorial](https://www.baeldung.com/jackson)들 중에 [직렬화/역직렬화 필드에 관한 글](https://www.baeldung.com/jackson-field-serializable-deserializable-or-not)에서 찾아볼 수 있습니다.

2023-09-25 12:27 UTC, yenawee commented on mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java
> +        response.getWriter().write(jsonValue);
감사합니다 필립!! 프로젝트 하면서도 수없이 많이 직렬화/역직렬화를 했었는데 저희는 롬복을 사용해서 진짜 별 생각없이 알아서 되겠거니.. 하고 있었네요 !! 글 참고해서 getter() 로 private 한 필드들도 직렬화가 될수 있게 해봤어요

2023-09-25 12:40 UTC, yenawee commented
안녕하세요 필립!
급하게 미션을 진행하면서 잘 이해하지 못하고 넘어갔던 요구사항을 짚어주셔서 감사합니다!!

첨부해주신 힌트 글 보고 바로 private 필드도 직렬화되게 추가했고 model 의 데이터가 1개일때는 값을 그대로 반환하게 분기처리를 추가해봤어요!! 

리뷰해주시면서 너무 잘 챙겨주신것도 감사합니다 🥺🙇‍♀️

2023-09-25 14:07 UTC, pilyang approved these changes
리뷰 남긴거 엄청 빨리 반영해주셨네요!! 👍👍👍

충분히 잘 된것같아서 Approve 할께요!! 다음 미션이랑 프로젝트도 화이팅하세요!!!

추가적으로 그냥 제나의 의견이 궁금한 내용이 있어서 코멘트에 남기긴 했는데, 혹시 시간 되시면 확인하고 제나 의견도 들려주시면 감사하겠습니다!!!

2023-09-25 14:07 UTC, pilyang commented on app/src/main/java/com/techcourse/domain/User.java
> +
`getter`를 추가해주는 방식으로 해결해주셨네요! 👍👍👍

이전 코멘트에서 준 [링크](https://www.baeldung.com/jackson-field-serializable-deserializable-or-not#make-all-fields-globally-serializable)를 보면 `JsonView` 에서 
```java
mapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
```
와 같은 방식으로 private필드를 통해서 해주는 방법도 있는데 `getter`를 이용한 이유가 궁금합니다..!!

사실 저도 고민이고, 뭐가 좋인지에 대한 확신이 없어서 혹시 제나의 의견도 들려주실 수 있으면 감사하겠습니다.

만약 겟터를 이용한다면 도메인에서 objectMapper에서 직렬화 해 줄 필드들을 명시적으로 지정할 수 있다 라는 장점이 있을 것 같습니다.
하지만 그러면 이는 도메인에 필요해서가 아니라 api에서 단순히 값을 보여주기 위해 도메인에 겟터가 추가된건데 이것은 괜찮은것일까하는 고민도 있었습니다 전....

혹시 제나는 둘중에 어떤 방식이 좋다고 생각하는지 의견 있으면 남겨주실 수 있을까요..?

2023-09-25 14:07 UTC, merged

2023-09-26 04:24 UTC, yenawee commented on app/src/main/java/com/techcourse/domain/User.java
> +
사실 getter() 를 사용한 이유는
`mapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY); ` 보다 익숙해서였던 이유가 가장 컸습니다!! 
(프로젝트에서 @Getter 를 너무써서 그랬나봐요...)

또 getter 를 사용해서 필드를 추출해서 그 필드에 일을 시키는 방식이 아니라 단순 응답을 위해서 사용하는 getter 이므로 저는 사용해도 된다구 생각했습니다 이전 레벨 1 미션에서도 출력을 위한 getter 는 괜찮다는 말을 들은 기억이 어렴풋이 납니다..! 

그리고 뭔가 `mapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);` 이 함수에서도 getter 를 어떻게든쓸거같아서... (구현 코드를 보려고 했는데 너무 복잡하네요....)