[MVC 프레임워크 구현하기 - 2,3단계] 나봄(윤보민) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #62
Opened 2021-09-14 06:46 UTC by qhals321

안녕하세요 검프!! 저번에 너무나 꼼꼼하게 리뷰해주셔서 너무나 감사했습니당!!!
사실 1 단계 때에 2,3 단계도 거의 끝났던 상황이었던지라.. 어떤 것을 추가하지 많이 고민했습니다...
메서드에 @ResponseBody와 리턴타입을 ResponseEntity 혹은 String 을 주었을 때 JsonView 를 반환하도록 설계했습니다!

이번 단계에서는 정상으로 작동하는지 테스트도 포함이 되어 있어 어떻게하면 조금 더 편하게 mvc 테스트를 작성할 수 있을까를 고민했습니다!
제가 만들었던 DispatcherServlet을 MockDispatcherServlet을 만들어 테스트할 수 있는 환경을 만들어보았습니다!
HttpServletRequest와 HttpServletResponse는 인터페이스이기 때문에 java 에서 제공하는 다이나믹 프록시를 이용해 Mocking 했습니당!

이번에 고민이 되었던 건 HttpServletResponse.getWriter(); 부분이었습니다!ㅠ
어떻게하면 I/O 없이 객체로 결과를 저장할 수 있을까 생각하다 FakePrintWriter 를 이용해 해결하게 되었습니다!

항상 꼼꼼한 리뷰 너무나 감사합니당! 덕분에 생각의 사고가 넓어지네요!! =]!!!

2021-09-14 07:47 UTC, qhals321 commented
추가로 model이 여러개일 때와 하나일 때 비교하기 위해 api들 추가하고 테스트했습니당!!

2021-09-15 15:04 UTC, Livenow14 requested changes
안녕하세요 나봄! 리뷰어 검프입니다 ㅎㅎㅎ
레벨1에서도 이미 완벽한 프레임워크라 생각했어요. 그래서  더 추가될 것이 있나 했는데, Fake객체 제공을 통해 Test환경을 구축 할 수 있게 한점과, 이를 통해 테스트를 진행한 점이 정말 놀랐어요. 이번에도 많이 배워가요.
우선 전반적인 피드백을 드리자면,

### 레벨 3 요구사항 중 Legacy MVC 제거하기 부분이 완료되지 않음

`asis 패키지에 있는 레거시 코드를 삭제해도 서비스가 정상 동작하도록 구현하자.` 가 아직 완료되지 않은 것 같아요. 아직 Controller가 남아있네요. 이부분 수정해주시면 될것 같아요!!

간단한 피드백 남겼으니 괜찮다면 반영해주세요 :)

2021-09-17 02:35 UTC, qhals321 commented on app/src/main/java/com/techcourse/controller/MemberController.java
> +    }
/members/single 이라고 표현하는게 좋겠네요!
사실 원래는 /members/1 과 같은 표현을 하고 싶었는데 파싱하기가 워낙 힘이 많이 들 거 같아서ㅠ 임시방편으로 만들었습니당!!

model 같은경우는 실제로 사용할 api가 아니라 그냥 model을 사용할 수도 있다 라는 표현의 테스트 형식이었습니다!

2021-09-17 02:38 UTC, qhals321 commented on app/src/main/java/com/techcourse/domain/User.java
> +
감사합니당!!!!!

2021-09-17 02:57 UTC, qhals321 commented on app/src/main/java/com/techcourse/MemberNotFoundException.java
> +}
MemberNotFoundException은 스프링 관련 예외가 아닌 서비스 내부의 예외이기 때문에 독자적으로 예외가 존재해야 한다고 생각했어요~!

메시지 부분을 추가해서 디버깅하기 쉽게 하는게 좋은 생각이네용!!! 감사합니다~!

2021-09-17 03:04 UTC, qhals321 commented on app/src/test/java/com/techcourse/controller/MemberControllerTest.java
> +    public void membersTest() {
오 그러네요~!! 감사합니다~!!

2021-09-17 03:05 UTC, qhals321 commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +            }
오 ~ 감사합니당!!

2021-09-17 03:07 UTC, qhals321 commented on mvc/src/main/java/nextstep/mvc/controller/MethodParameter.java
>      }
이 부분은 외부에서 사용할 때 타입 추론 문제때문에 컴파일 문제가 아예 생기더라구여ㅠ
그래서 Object로 바꾸게 되었습니당!

2021-09-17 03:09 UTC, qhals321 commented
역시나 꼼꼼한 검프!! 덕분에 많이 배워가요!!!
ObjectMapper를 그냥 저렇게 access하게끔 하는 방법이 있었군용!! 감사합니다~!!!

2021-09-17 14:48 UTC, Livenow14 commented on mvc/src/main/java/nextstep/mvc/controller/MethodParameter.java
>      }
역시.. 제네릭 타입추론 문제였군요..

2021-09-17 14:56 UTC, Livenow14 approved these changes
안녕하세요 나봄. 
피드백 반영을 꼼꼼히 해주셨네요 :) 
요구사항 만족도 하고 코드도 더 깔끔해진거 같아요! 

나봄 코드를 리뷰 하며 많이 배워갔어요!! 고마워요 😊
수정해야하 사항이 더 보이지 않아, 이만 머지할게요 🙏🏻

2021-09-17 14:56 UTC, merged