[MVC 구현하기 - 3단계] 웨지(성시형) 미션 제출합니다
woowacourse/jwp-dashboard-mvc pull request #87
Opened 2021-09-16 00:07 UTC by sihyung92

hello 현구막~~
뷰리졸버와 기존 코드 이식 얼렁뚱땅 해봤습니다!
탈탈 털어주세요! 감사합니다!

2021-09-17 03:21 UTC, Hyeon9mak requested changes
헤이~ 잠콩지기~
백신 맞고 몸살나서 누워있다가 리뷰가 늦었네요.. 😭  🙏 
근데 백신 맞기 전에도 늦었던거 같음 ㅋㅋ..ㅈㅅ..ㅎㅎ!! 😄 👍 

**MVC 미션 3단계 - View 구현하기, Legacy MVC 제거하기**는 모두 충족하는 것을 확인했어요!!
다만!!! 관련된 테스트 코드가 없어서 직접 서버를 동작하고 하나하나 확인해야하는 점이 아쉬웠어요!!
그래서 테스트 코드를 추가해주시면 어떨까 해서 리첸(리챔 아님ㅋ)을 드립니다 하하하하하하하

인스턴스 초기화 블록에 대해 여전히 웨지의 취향을 존중하지만!! 현재 코드 상에서 인스턴스 초기화 블록이 중복로직 제거로 사용되지 않는 것 같았고, 인스턴스 초기화 블록에서 초기화 시키는 객체를 생성자에서는 DI 하려는 시도? 비슷한게 보여서 관련 리뷰를 남겼어요!!

혹시나 '나 이번 단계에 여기에 정성 쏟았는데 이건 왜 리뷰 안해줘?' 하시는 부분이 있다면 언제든지 코멘트 남겨주세요!!!!!!!!!
더 열심히 괴롭힐게요!!!!!!!!!! 크하하하!!!!!!!!

잠실최강 커피빈 지기 웨지 화이팅!!! ☕ 🥔

2021-09-17 03:21 UTC, Hyeon9mak commented on app/src/main/java/com/techcourse/controller/IndexController.java
> +}
꼼꼼한 관리 👍

2021-09-17 03:21 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/controller/AnnotationHandlerMapping.java
>  import java.lang.reflect.Constructor;
헉 꼼꼼한 패키지 정리 👍 💯

2021-09-17 03:21 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
아.. 매 JsonView 마다 오브젝트 매퍼를 할당할 필요는 없으니... 👍 👍 💯 
저도 리팩토링해야겠네요 😭

2021-09-17 03:21 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/view/ModelAndView.java
> +        return new ModelAndView(VoidView.CACHE);
객체 캐싱 👍 👍 👍

2021-09-18 01:01 UTC, sihyung92 commented on app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java
> +    }
홋홋

2021-09-18 01:02 UTC, sihyung92 commented on app/src/main/java/com/techcourse/controller/UserController.java
> +        modelAndView.addObject("user1", "user");
무언가 테스트해보려던 것의 잔재 아닐까요? 과거의 나 정답을 알려줘

2021-09-18 01:02 UTC, sihyung92 commented on app/src/main/java/com/techcourse/controller/RegisterController.java
>          return "redirect:/index.jsp";
DB 싹 뜯어고치기 완료!

2021-09-18 01:02 UTC, sihyung92 commented on app/src/main/java/com/techcourse/controller/LogoutController.java
>          session.removeAttribute(UserSession.SESSION_KEY);
오 맞아요!

2021-09-18 01:02 UTC, sihyung92 commented on app/src/main/java/com/techcourse/controller/LoginController.java
>      }
인터셉터 구현 고려해보겠습니다!

2021-09-18 01:03 UTC, sihyung92 commented on app/src/main/java/com/techcourse/controller/LoginViewController.java
> +            .orElse("/login.jsp");
지금 코드도 충분히 좋은거 같은걸요!? 어떤 개선방향이 있을까요?

2021-09-18 01:04 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/HandlerExecution.java
> +    }
넵!

2021-09-18 01:04 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/HandlerExecutionAdapter.java
> +        return ModelAndView.emptyView();
네엡!

2021-09-18 01:05 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        response.flushBuffer();
오 버퍼를 항상 비워주나보군요! 배워갑니다

2021-09-18 01:31 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        }
1. 동의하는 바지만 values() api의 자료구조가  Collections라 get이 없답니다.. iterator를 호출해야 하는 부분 👀
2. 상위 메소드로 throw 하라는 의미일까요??

2021-09-18 01:31 UTC, sihyung92 commented on mvc/src/test/java/nextstep/mvc/controller/ParameterResolverExecutorTest.java
>              assertParameterTypes(parametersClasses, parameters);
ㅎ_ㅎ 의존성 없이 해보려고 재미로 해봤습니당!! 애교로 봐주세요!

2021-09-18 01:32 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/ParameterResolverExecutor.java
>  }
그래볼까용??

2021-09-18 01:33 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/ParameterResolverExecutor.java
>      }
디폴트 세팅이란 느낌으로 해놨는데, DI를 받는 방향으로 리팩토링 하는 것이 맞다고 생각합니당

2021-09-18 01:36 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/ParameterResolverExecutor.java
>                  return resolver.resolveParameter(parameter, request, response);
"고유한 원소임이 증명" 부분 때문에 Set을 썼습니다! Resolvers의 경우 유저데이터 처럼 대량데이터를 다룰 컬렉션이 아니기때문에, `탐색시의 시간복잡도로 인한 효율성 저하` 보다 `동일한 Resolver가 두 번 들어가서 생길 버그가능성 제거` 가 더 높은 가치가 있다고 생각합니다.

2021-09-18 01:36 UTC, sihyung92 commented on app/src/main/java/com/techcourse/controller/IndexController.java
> +}
꼼관

2021-09-18 01:36 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/controller/AnnotationHandlerMapping.java
>  import java.lang.reflect.Constructor;
꼼패정

2021-09-18 01:36 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
캐슁캐슁

2021-09-18 01:37 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/view/ModelAndView.java
> +        return new ModelAndView(VoidView.CACHE);
캐슁

2021-09-18 05:40 UTC, Hyeon9mak commented on app/src/main/java/com/techcourse/controller/LoginViewController.java
> +            .orElse("/login.jsp");
`LoginController.java` 20~22 라인에 좋은게 있습니다 👍

2021-09-18 05:46 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        }
1. `toArray()`로 강제 배열 전환 후 0번 인덱스를 조회하는 방법도 있더라구요!! 취향이 담기는 부분이라 생각해서 웨지의 생각이 궁금했어요 👍 👍 
2. 아래 코드를 잘 표현 못했네요 😭 ... 저걸 무어라 불러야할지..
```java
private String ObjectToJson(Map<String, ?> model) throws JsonProcessingException {
    ...
}
```

2021-09-18 05:47 UTC, Hyeon9mak commented on mvc/src/test/java/nextstep/mvc/controller/ParameterResolverExecutorTest.java
>              assertParameterTypes(parametersClasses, parameters);
👍

2021-09-18 05:49 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/controller/ParameterResolverExecutor.java
>                  return resolver.resolveParameter(parameter, request, response);
확고한 의견 좋아요!!!

2021-09-18 12:39 UTC, sihyung92 commented on app/src/main/java/com/techcourse/controller/LoginController.java
>      }
깔끔하게 포기했습니다!

2021-09-18 12:46 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        }
1. for 내부의 return문, 위의 사이즈 1이면 충분한 내용전달이 되리라 생각합니다! 그래서  `첫 번째 원소를 꺼내서 사용한다' 는 게 꺼림칙하다기 보다 흘러가는대로 한 코딩이지만 굳이 변경점이라고 생각하진 않습니다 +_+  toArray하고 0번 인덱스를 잡아오는게 가독성이 더 좋을것이라는데는 동의합니다

2021-09-19 03:07 UTC, Hyeon9mak commented on app/src/main/java/com/techcourse/controller/LoginController.java
>      }
?!

2021-09-19 13:44 UTC, Hyeon9mak requested changes
헤웨! 폴리곤 덩어리가 싫은 막구현 입니다.

APP - Controller 테스트를 부탁드린거였는데 MVC쪽 테스트가 짱짱하게 짜여졌네요... 
조금 더 자세하게 말씀 드릴걸... 죄송해요...😰 
어쩌면 오히려 좋을지도...? 🚀 

`InMemoryUserRepository.java` 쪽에 AtomicLong이 의도와 다르게 동작하는 부분이 보여서 마지막 리첸 남겨봅니다!!

웨지 괴롭히기도 슬슬 끝이 보이네요.. 아쉽다..

2021-09-19 13:44 UTC, Hyeon9mak commented on app/src/main/java/com/techcourse/controller/IndexController.java
> +    }
👍

2021-09-19 13:44 UTC, Hyeon9mak commented on app/src/main/java/com/techcourse/controller/LoginViewController.java
> +        return "/login.jsp";
바로 이거쥬! 👍 💯

2021-09-19 13:44 UTC, Hyeon9mak commented on app/src/main/java/com/techcourse/controller/UserSession.java
> +    }
코드 자동정렬 때문에 내려오신거겠죠?!
생성자를 메서드 위로 올려주시면 가독성도 위로 올라간다는 이제 라임을 곁들인

2021-09-19 13:44 UTC, Hyeon9mak commented on app/src/main/java/com/techcourse/domain/Account.java
> +    }
👍 👍 👍 👍 👍 👍 VO값 생성자 검증 너무 좋아한다는 그런 개인적인 취향으로 따봉난무를 날린다는👍 👍 👍 👍 👍 👍

2021-09-19 13:44 UTC, Hyeon9mak commented on app/src/main/java/com/techcourse/domain/User.java
>      private final String email;
나머지도 VO 해주시면 어떻냐고 권유하려다 참습니다 하하하하

2021-09-19 13:44 UTC, Hyeon9mak commented on app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java
> +        return Optional.ofNullable(database.get(userId));
빠피반 👍

2021-09-19 13:44 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>      }
오! 빌더를 사용하신건 '요즘 정팩메 손이 안간다'의 그것 일까요?

2021-09-19 13:44 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/controller/HandlerExecution.java
> +        return method.invoke(handler, parameters);
유연해졌네용 😮

2021-09-19 13:44 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/controller/ResponseEntity.java
> +}
wow 👀

2021-09-19 13:44 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/handler/HandlerAdapter.java
> +        throws Exception;
`HandleExcution`도 Object로 바꼈으니 어댑터 인터페이스도 바뀌면 어떨까유?!

2021-09-19 13:44 UTC, Hyeon9mak commented on mvc/src/main/java/nextstep/mvc/resolver/modelandview/JustModelAndViewResolver.java
> +    }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 직관적 네이밍

2021-09-19 13:44 UTC, Hyeon9mak commented on mvc/src/test/java/nextstep/mvc/resolver/modelandview/ModelAndViewResolversTest.java
> +    }
짱짱한 리졸버 테스트 👍 ...

2021-09-20 00:30 UTC, sihyung92 commented on app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java
> +    private static final AtomicLong id = new AtomicLong(0);
대컨

2021-09-20 00:34 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
>      }
전 두개 이상의 필드가 nullable해지면 빌더를 고려합니당~~
생성자가 복잡해져서여!
constructor(a,b,c)
constructor(a,c)

2021-09-20 00:38 UTC, sihyung92 commented on mvc/src/main/java/nextstep/mvc/handler/HandlerAdapter.java
> +        throws Exception;
핸들러 어댑터의 역할은 Object찌꺼기들을 ModelAndView로 변환해주는 것이 목적이라고 생각합니다!

2021-09-20 02:06 UTC, Hyeon9mak approved these changes
월요일 좋아~ 사실 안좋아~
웨지 괴롭히기 123단계가 벌써 끝났네요...

정말로 괴롭히려고 괴롭힌건 아니고, 웨지 코드 수준이 높은데 제가 모르는건 많고...
그래도 성심성의껏 코드 리뷰는 하고 싶고.. 그러다보니 웨지를 많이 귀찮게 한거 같아요~ 껄껄~

리뷰이보다 리뷰어가 더 많이 배우는 PR 개이득 ^_^ 👍 💯 

사람 위에 개발 없으니 쉬엄쉬엄 추석 연휴 잘 보내시구요~ 🌕 
빠른 시일 내에 닭가슴살 + 스크램블에그 + 소주 조합 또 느껴보고 싶네유~ 👍 
우주 최강 보름달 감자 웨지 화이팅!!

2021-09-20 02:06 UTC, merged