[MVC 구현하기 - 2, 3단계] 와이비(허영범) 미션 제출합니다.
woowacourse/jwp-dashboard-mvc pull request #93
Opened 2021-09-16 11:32 UTC by hybeom0720

안녕하세요! 마크!
2, 3단계 미션으로 또 뵙게된 와이비입니다.
이번 미션에서는 JspView를 리팩토링할 뿐만이 아니라 JsonView를 만들어서 적용시켜 보았습니다.
이전 구조에서 레거시를 제거하고 제가 짠 코드의 로직을 이식하는 과정에서 레거시 구조가 이식하기 편한구조라 고생은 덜한 것 같습니다.
JsonView에 대해서는 테스트 코드를 짜고 싶은데, 테스트 로직은 생각나지만 테스트 코드 추가가 잘 되지 않네요 ㅜㅜ
연구를 하면서 추가를 해보록 하겠습니다.
감사합니다!

2021-09-18 16:28 UTC, binghe819 requested changes
안녕하세요 와이비!!~~

1단계 구현때 잘 구현해주셔서 2, 3단계 코드는 변경이 크게 발생하지 않고 잘 구현해주신 것 같아요 👍  💯 

제가 보기엔 크게 피드백 할 부분이 없는 것 같아서 몇가지 제 의견만 남겼습니다!

확인해보시구 편하게 의견 남겨주세요~~

> 리뷰 늦은 점 죄송해요 ㅠ

2021-09-18 16:28 UTC, binghe819 commented on README.md
> +# Step3
요구사항 정리 👍

2021-09-18 16:28 UTC, binghe819 commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        out.flush();
요구사항의 힌트를 보면 아래와 같은 내용이 있습니다!

`model에 데이터가 1개면 값을 그대로 반환하고 2개 이상이면 Map 형태 그대로 JSON으로 변환해서 반환한다.`

현재 데이터 개수와 관계없이 Map 형태로 반환하는 것 같아 의견 남겨요~~

2021-09-18 16:28 UTC, binghe819 commented on app/src/main/java/com/techcourse/controller/HomeController.java
> +    public ModelAndView execute(HttpServletRequest req, HttpServletResponse res) {
피드백이라기보다는 제가 리팩토링하며 가독성이 더 좋아지는 부분에 대한 의견을 남길려고합니다!

```suggestion
    public String execute(HttpServletRequest req, HttpServletResponse res) {
```

현재 컨트롤러에서 일괄적으로 `ModelAndView`를 반환하기 때문에 Jsp를 사용하기 위해선 전부 `new JspView(...)`를 반복해서 사용하는 것 같아요!

이 부분을 `String`으로 반환하도록하고 AnnotationHandlerAdapter`부분에서 Controller에서 반환받은 값이 `String`이면 JspView로 반환하도록 하면 더 가독성이 좋아지더라구요!

스프링 코드를 참고하면서 리팩토링한 부분 중 가독성이 좋아졌던 부분이라 피드백 남깁니다~~

2021-09-20 08:11 UTC, hybeom0720 commented on mvc/src/main/java/nextstep/mvc/view/JsonView.java
> +        out.flush();
앗 ToDo에 따로 정리해놨었는데, 같이 지워버렸군요 ㅜㅜ 
반영하였습니다!

2021-09-20 08:14 UTC, hybeom0720 commented on app/src/main/java/com/techcourse/controller/HomeController.java
> +    public ModelAndView execute(HttpServletRequest req, HttpServletResponse res) {
감사합니다!
안 그래도 ModelAndView 및 JspView가 계속해서 생성되는 것 같아서 조금 마음이 불편했는데
리뷰 남겨주신 부분을 참고하여 반영하였습니다.
JsonView도 처리하려고하였지만, 일반적으로 Spring Boot에서 ResponseEntity로 반환을 지정해준다는 점을 참고하여 작업을 수행하지 않았습니다.
또한 테스트 코드도 조금 보강했는데, 인수 테스트는 톰캣과 같은 부분도 주입을 해주어야하는 것 같아서 조금 더 공부를 하도록 하겠습니다.
감사합니다! 마크

2021-09-20 08:28 UTC, binghe819 approved these changes
와이비 리팩토링 한 부분 확인했습니다!~~~

기존에도 깔끔하게 잘 구현해주셔서 재밌게 보았습니다 👍 

그럼 이만 approve 하도록 할게요~

이번 미션 힘드셨을텐데 고생 많으셨어요!!! 즐추~~ 👍

2021-09-23 07:08 UTC, merged